/* SPDX-License-Identifier: GPL-2.0 or MIT */
/* Copyright 2026 ARM Limited. All rights reserved. */

#ifndef __PANTHOR_GPU_DISCOVER_REGS_H__
#define __PANTHOR_GPU_DISCOVER_REGS_H__

#define GPU_WIDE_ID					0x0
#define   GPU_WIDE_COMPAT				0xF
#define   GPU_WIDE_ARCH_MAJOR(x)			(((x) & GENMASK(63, 56)) >> 56)
#define   GPU_WIDE_ARCH_MINOR(x)			(((x) & GENMASK(55, 48)) >> 48)
#define   GPU_WIDE_ARCH_REV(x)				(((x) & GENMASK(47, 40)) >> 40)
#define   GPU_WIDE_PROD_MAJOR(x)			(((x) & GENMASK(39, 32)) >> 32)
#define   GPU_WIDE_VER_MAJOR(x)				(((x) & GENMASK(23, 16)) >> 16)
#define   GPU_WIDE_VER_MINOR(x)				(((x) & GENMASK(15, 8)) >> 8)
#define   GPU_WIDE_VER_STATUS(x)			((x) & GENMASK(7, 0))

#define DISCOVER_REVIDR					0x8
#define DISCOVER_GPU_FEATURES				0x20
#define   GPU_FEATURES_VARIABLE_RATE_SHADING		BIT(0)
#define   GPU_FEATURES_SIMD_STATE			BIT(1)
#define   GPU_FEATURES_CROSS_STREAM_SYNC		BIT(3)
#define   GPU_FEATURES_NX				BIT(4)
#define   GPU_FEATURES_RAY_TRAVERSAL			BIT(5)
#define   GPU_FEATURES_LD_LEA_TENSOR_INSTRUCTIONS	BIT(6)
#define DISCOVER_MCU_FEATURES				0x40
#define DISCOVER_PRFCNT_FEATURES			0x50
#define   PRFCNT_FEATURES_COUNTER_BLOCK_SIZE(x)		(((x) & GENMASK(7, 0)) << 8)
#define DISCOVER_DOORBELL_FEATURES			0x60
#define DISCOVER_MEM_FEATURES				0x100
#define DISCOVER_MMU_FEATURES				0x108
#define   MMU_FEATURES_AS_COUNT(x)			(((x) & GENMASK(23, 16)) >> 16)
#define DISCOVER_AMBA_FEATURES				0x120

#define DISCOVER_L2_FEATURES				0x128
#define DISCOVER_TILER_FEATURES				0x200
#define DISCOVER_CORE_FEATURES				0x300
#define DISCOVER_THREAD_FEATURES			0x320
#define DISCOVER_THREAD_MAX_THREADS			0x330
#define DISCOVER_THREAD_NUM_ACTIVE_GRANULARITY		0x334
#define DISCOVER_TEXTURE_FEATURES			0x360

#endif /* __PANTHOR_GPU_DISCOVER_REGS_H__ */
