# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_KMEMDUMP) += kmemdump.o
obj-$(CONFIG_KMEMDUMP_COREIMAGE) += kmemdump_coreimage.o
obj-$(CONFIG_KMEMDUMP_QCOM_MINIDUMP_BACKEND) += qcom_minidump.o
obj-$(CONFIG_KMEMDUMP_KINFO_BACKEND) += kinfo.o
