# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AMD_VERSAL_PCI)			+= versal-pci.o

versal-pci-$(CONFIG_AMD_VERSAL_PCI)		:= versal-pci-main.o \
						   versal-pci-comm-chan.o \
						   versal-pci-rm-queue.o \
						   versal-pci-rm-service.o
