# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for staging industrial I/O Magnetometer sensor devices
#
# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_QMC5883P)	+= qmc5883p.o
