# SPDX-License-Identifier: GPL-2.0
# Makefile for YNL tests

TEST_PROGS := \
	cli.sh \
	ethtool.sh \
# end of TEST_PROGS

TEST_FILES := \
	settings \
# end of TEST_FILES

TEST_INCLUDES := \
	$(wildcard ../lib/sh/*.sh) \
	../lib.sh \
# end of TEST_INCLUDES

include ../../lib.mk
