# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_USE_BUILTIN_DTB) += $(addsuffix .dtb.o, $(CONFIG_BUILTIN_DTB_SOURCE))

dtb-$(CONFIG_CPU_J2) += j2_mimas_v2.dtb
dtb-$(CONFIG_CPU_SUBTYPE_SH7751R) += landisk.dtb
dtb-$(CONFIG_CPU_SUBTYPE_SH7751R) += rts7751r2dplus.dtb
dtb-$(CONFIG_CPU_SUBTYPE_SH7751R) += usl-5p.dtb
