# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for AMD AI engine device driver

obj-$(CONFIG_DRM_ACCEL_AMDAIE)	+= amd-aie.o

amd-aie-$(CONFIG_DRM_ACCEL_AMDAIE) := \
	ai-engine-aie.o		\
	ai-engine-aieml.o	\
	ai-engine-aperture.o	\
	ai-engine-clock.o	\
	ai-engine-dev.o		\
	ai-engine-part.o	\
	ai-engine-res.o
