# SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause)

dtb-$(CONFIG_ARCH_GOOGLE) += \
	lga-blazer-mp1.dtb \
	lga-frankel-mp1.dtb \
	lga-mustang-mp1.dtb

lga-blazer-mp1-dtbs		:= lga-b0.dtb lga-blazer-mp1.dtbo
lga-frankel-mp1-dtbs		:= lga-b0.dtb lga-frankel-mp1.dtbo
lga-mustang-mp1-dtbs		:= lga-b0.dtb lga-mustang-mp1.dtbo
