# SPDX-License-Identifier: GPL-2.0
i3c-y				:= device.o master.o
obj-$(CONFIG_I3C)		+= i3c.o
obj-$(CONFIG_I3C)		+= master/
obj-$(CONFIG_I3C_SLAVE)		+= slave.o
obj-$(CONFIG_I3C_SLAVE_CONFIGFS)	+= i3c-cfs.o
