/* SPDX-License-Identifier: MIT */
/*
 * Copyright (C) 2025 Intel Corporation
 */

#ifndef __INTEL_CMTG_REGS_H__
#define __INTEL_CMTG_REGS_H__

#include "intel_display_reg_defs.h"

#define CMTG_CLK_SEL			_MMIO(0x46160)
#define CMTG_CLK_SEL_A_MASK		REG_GENMASK(31, 29)
#define CMTG_CLK_SELECT_PHYA_ENABLE	REG_FIELD_PREP(CMTG_CLK_SEL_A_MASK, 0x4)
#define CMTG_CLK_SEL_A_DISABLED		REG_FIELD_PREP(CMTG_CLK_SEL_A_MASK, 0)
#define CMTG_CLK_SEL_B_MASK		REG_GENMASK(15, 13)
#define CMTG_CLK_SELECT_PHYB_ENABLE	REG_FIELD_PREP(CMTG_CLK_SEL_B_MASK, 0x6)
#define CMTG_CLK_SEL_B_DISABLED		REG_FIELD_PREP(CMTG_CLK_SEL_B_MASK, 0)

#define TRANS_CMTG_CTL_A		_MMIO(0x6fa88)
#define TRANS_CMTG_CTL_B		_MMIO(0x6fb88)
#define  CMTG_ENABLE			REG_BIT(31)

#define _TRANS_HTOTAL_CMTG_A		0x6F000
#define _TRANS_HTOTAL_CMTG_B		0x6F100
#define TRANS_HTOTAL_CMTG(trans)	_MMIO_TRANS((trans), \
						    _TRANS_HTOTAL_CMTG_A, _TRANS_HTOTAL_CMTG_B)
#define _TRANS_HBLANK_CMTG_A		0x6F004
#define _TRANS_HBLANK_CMTG_B		0x6F104
#define TRANS_HBLANK_CMTG(trans)	_MMIO_TRANS((trans), \
						    _TRANS_HBLANK_CMTG_A, _TRANS_HBLANK_CMTG_B)
#define _TRANS_HSYNC_CMTG_A		0x6F008
#define _TRANS_HSYNC_CMTG_B		0x6F108
#define TRANS_HSYNC_CMTG(trans)		_MMIO_TRANS((trans), \
						    _TRANS_HSYNC_CMTG_A, _TRANS_HSYNC_CMTG_B)
#define _TRANS_VTOTAL_CMTG_A		0x6F00C
#define _TRANS_VTOTAL_CMTG_B		0x6F10C
#define TRANS_VTOTAL_CMTG(trans)	_MMIO_TRANS((trans), \
						    _TRANS_VTOTAL_CMTG_A, _TRANS_VTOTAL_CMTG_B)
#define _TRANS_VBLANK_CMTG_A		0x6F010
#define _TRANS_VBLANK_CMTG_B		0x6F110
#define TRANS_VBLANK_CMTG(trans)	_MMIO_TRANS((trans), \
						    _TRANS_VBLANK_CMTG_A, _TRANS_VBLANK_CMTG_B)
#define _TRANS_VSYNC_CMTG_A		0x6F014
#define _TRANS_VSYNC_CMTG_B		0x6F114
#define TRANS_VSYNC_CMTG(trans)		_MMIO_TRANS((trans), \
						    _TRANS_VSYNC_CMTG_A, _TRANS_VSYNC_CMTG_B)

#define _TRANS_SET_CTX_LATENCY_CMTG_A	0x6F07C
#define _TRANS_SET_CTX_LATENCY_CMTG_B	0x6F17C
#define TRANS_SET_CTX_LATENCY_CMTG(trans)	_MMIO_TRANS((trans), \
							    _TRANS_SET_CTX_LATENCY_CMTG_A, \
							    _TRANS_SET_CTX_LATENCY_CMTG_B)

#define _TRANS_VRR_CTL_CMTG_A		0x6F420
#define _TRANS_VRR_CTL_CMTG_B		0x6F520
#define TRANS_VRR_CTL_CMTG(trans)	_MMIO_TRANS((trans), \
						     _TRANS_VRR_CTL_CMTG_A, _TRANS_VRR_CTL_CMTG_B)
#define _TRANS_VRR_VMAX_CMTG_A		0x6F424
#define _TRANS_VRR_VMAX_CMTG_B		0x6F524
#define TRANS_VRR_VMAX_CMTG(trans)	_MMIO_TRANS((trans), \
						     _TRANS_VRR_VMAX_CMTG_A, \
						     _TRANS_VRR_VMAX_CMTG_B)
#define _TRANS_VRR_VMIN_CMTG_A		0x6F434
#define _TRANS_VRR_VMIN_CMTG_B		0x6F534
#define TRANS_VRR_VMIN_CMTG(trans)	_MMIO_TRANS((trans), \
						     _TRANS_VRR_VMIN_CMTG_A, \
						     _TRANS_VRR_VMIN_CMTG_B)
#define _TRANS_VRR_FLIPLINE_CMTG_A	0x6F438
#define _TRANS_VRR_FLIPLINE_CMTG_B	0x6F538
#define TRANS_VRR_FLIPLINE_CMTG(trans)	_MMIO_TRANS((trans), \
						     _TRANS_VRR_FLIPLINE_CMTG_A, \
						     _TRANS_VRR_FLIPLINE_CMTG_B)

#endif /* __INTEL_CMTG_REGS_H__ */
