// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (C) 2025 - Francesco Valla <francesco@valla.it>
 *
 * Driver for bootstage stash.
 *
 * This driver exposes bootstage stash generated by bootloader and/or firmware
 * stages that run before the Linux kernel.
 *
 */

#include <linux/debugfs.h>
#include <linux/io.h>
#include <linux/mm.h>
#include <linux/module.h>
#include <linux/of_reserved_mem.h>
#include <linux/platform_device.h>
#include <linux/seq_file.h>

#define BOOTSTAGE_MAGIC		0xb00757a3
#define BOOTSTAGE_MAX_VERSION	0

enum bootstage_id {
	BOOTSTAGE_ID_START = 0,
};

enum bootstage_flags {
	BOOTSTAGEF_ERROR	= 1 << 0,	/* Error record */
	BOOTSTAGEF_ALLOC	= 1 << 1,	/* Allocate an id */
};

struct bootstage_record {
	ulong time_us;
	u32 start_us;
	const char *name;
	int flags;
	enum bootstage_id id;
};

struct bootstage_hdr {
	u32 version;		/* Boostage stash version */
	u32 count;		/* Number of records */
	u32 size;		/* Total data size (non-zero if valid) */
	u32 magic;		/* Magic number */
	u32 next_id;		/* Next ID to use for bootstage */
};

struct bootstage_drvdata {
	struct bootstage_hdr *hdr;
	struct bootstage_record *records;

	u32 start_time_us;
	u32 end_time_us;

	struct dentry *debugfs_dir;
};

static struct dentry *bootstage_debugfs_dir;

static int stages_show(struct seq_file *m, void *d)
{
	struct bootstage_drvdata *drvdata = m->private;
	struct bootstage_hdr *hdr = drvdata->hdr;
	struct bootstage_record *rec;
	u32 prev = 0;
	int i;

	seq_printf(m, "%13s %13s  %s\n", "Mark (us)", "Elapsed (us)", "Stage");

	for (i = 0, rec = drvdata->records; i < hdr->count; i++, rec++) {
		if ((rec->id && !rec->start_us) || (i == 0)) {
			if (prev > rec->time_us)
				prev = 0;
			seq_printf(m, "%13lu %13lu  %s\n", rec->time_us,
				   rec->time_us - prev, rec->name);
			prev = rec->time_us;
		}
	}

	return 0;
}
DEFINE_SHOW_ATTRIBUTE(stages);

static int accumulated_time_show(struct seq_file *m, void *d)
{
	struct bootstage_drvdata *drvdata = m->private;
	struct bootstage_hdr *hdr = drvdata->hdr;
	struct bootstage_record *rec;
	int i;

	seq_printf(m, "%13s  %s\n", "Time (us)", "Stage");

	for (i = 0, rec = drvdata->records; i < hdr->count; i++, rec++) {
		if (rec->start_us)
			seq_printf(m, "%13lu  %s\n", rec->time_us, rec->name);
	}

	return 0;
}
DEFINE_SHOW_ATTRIBUTE(accumulated_time);

static void bootstage_debugfs_init(struct device *dev, struct bootstage_drvdata *drvdata)
{
	drvdata->debugfs_dir = debugfs_create_dir(dev_name(dev), bootstage_debugfs_dir);
	if (IS_ERR(drvdata->debugfs_dir))
		return;

	debugfs_create_file("stages", 0444, drvdata->debugfs_dir, drvdata, &stages_fops);
	debugfs_create_file("accumulated_time", 0444, drvdata->debugfs_dir, drvdata,
			    &accumulated_time_fops);
}

static void bootstage_debugfs_exit(struct device *dev, struct bootstage_drvdata *drvdata)
{
	debugfs_remove_recursive(drvdata->debugfs_dir);
}

static ssize_t start_time_us_show(struct device *dev, struct device_attribute *attr, char *buf)
{
	struct bootstage_drvdata *drvdata = dev_get_drvdata(dev);

	return sprintf(buf, "%u\n", drvdata->start_time_us);
}
static DEVICE_ATTR_RO(start_time_us);

static ssize_t end_time_us_show(struct device *dev, struct device_attribute *attr, char *buf)
{
	struct bootstage_drvdata *drvdata = dev_get_drvdata(dev);

	return sprintf(buf, "%u\n", drvdata->end_time_us);
}
static DEVICE_ATTR_RO(end_time_us);

static struct attribute *bootstage_attrs[] = {
	&dev_attr_start_time_us.attr,
	&dev_attr_end_time_us.attr,
	NULL,
};

static const struct attribute_group bootstage_attr_group = {
	.attrs = bootstage_attrs,
};

static int bootstage_parse(struct device *dev, struct bootstage_drvdata *drvdata,
			   resource_size_t size)
{
	const char *str_ptr = (const char *)(drvdata->records + drvdata->hdr->count);
	const resource_size_t calc_size = (resource_size_t)((void *)str_ptr - (void *)drvdata->hdr);
	struct bootstage_record *rec;
	u32 r;

	// Sanity checks on bootstage header
	if (drvdata->hdr->magic != BOOTSTAGE_MAGIC) {
		dev_err(dev, "wrong bootstage magic number %08Xh\n", drvdata->hdr->magic);
		return -EINVAL;
	} else if (drvdata->hdr->version > BOOTSTAGE_MAX_VERSION) {
		dev_err(dev, "bootstage version %u not supported\n", drvdata->hdr->version);
		return -EOPNOTSUPP;
	} else if (drvdata->hdr->size == 0) {
		dev_err(dev, "invalid bootstage stash (declared size is zero)\n");
		return -EINVAL;
	} else if (drvdata->hdr->size > size) {
		dev_err(dev, "invalid declared stash size %u (expected: <= %llu)\n",
			drvdata->hdr->size, size);
		return -EINVAL;
	} else if (calc_size > size) {
		dev_err(dev, "invalid calculated stash size %llu (expected: <= %llu)\n",
			calc_size, size);
		return -EINVAL;
	} else if (drvdata->hdr->count == 0) {
		dev_info(dev, "bootstage stash has no records\n");
		return 0;
	}

	// Set start time to invalid
	drvdata->start_time_us = 0xFFFFFFFF;

	// Associate names to records, which are placed at the end of the record area
	for (r = 0, rec = drvdata->records; r < drvdata->hdr->count; r++, rec++) {
		// Save minimum time, will be used as bootloader enter time
		if (rec->start_us < drvdata->start_time_us)
			drvdata->start_time_us = rec->time_us;

		// Save maximum time, will be used as bootloader exit time
		if (rec->time_us > drvdata->end_time_us)
			drvdata->end_time_us = rec->time_us;

		if (str_ptr > ((const char *)drvdata->hdr + size)) {
			dev_err(dev, "name for record %u is corrupted\n", r);
			return -ENODATA;
		}

		rec->name = str_ptr;
		str_ptr += strlen(rec->name) + 1;
	}

	return 0;
}

static int bootstage_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct reserved_mem *rmem;
	struct bootstage_drvdata *drvdata;
	int ret;

	rmem = of_reserved_mem_lookup(dev->of_node);
	if (!rmem) {
		dev_err(dev, "failed to lookup reserved memory\n");
		return -EINVAL;
	}

	if (!rmem->size || (rmem->size > ULONG_MAX) ||
	    (rmem->size < sizeof(struct bootstage_hdr))) {
		dev_err(dev, "invalid memory region size\n");
		return -EINVAL;
	}

	if (!PAGE_ALIGNED(rmem->base) || !PAGE_ALIGNED(rmem->size)) {
		dev_err(dev, "memory region must be page-aligned\n");
		return -EINVAL;
	}

	drvdata = devm_kmalloc(dev, sizeof(*drvdata), GFP_KERNEL);
	if (!drvdata)
		return -ENOMEM;

	platform_set_drvdata(pdev, drvdata);

	drvdata->hdr = devm_memremap(dev, rmem->base, rmem->size, MEMREMAP_WB);
	if (IS_ERR(drvdata->hdr)) {
		dev_err(dev, "failed to remap bootstage region\n");
		return PTR_ERR(drvdata->hdr);
	}

	drvdata->records =
		(struct bootstage_record *)((void *)drvdata->hdr + sizeof(struct bootstage_hdr));

	ret = bootstage_parse(dev, drvdata, rmem->size);
	if (ret)
		return ret;

	ret = sysfs_create_group(&pdev->dev.kobj, &bootstage_attr_group);
	if (ret) {
		dev_err(dev, "failed to create sysfs group\n");
		return ret;
	}

	bootstage_debugfs_init(dev, drvdata);

	return 0;
}

static void bootstage_remove(struct platform_device *pdev)
{
	struct bootstage_drvdata *drvdata = platform_get_drvdata(pdev);

	bootstage_debugfs_exit(&pdev->dev, drvdata);
	sysfs_remove_group(&pdev->dev.kobj, &bootstage_attr_group);
}

static const struct of_device_id bootstage_of_match[] = {
	{ .compatible = "bootstage" },
	{},
};

static struct platform_driver bootstage_driver = {
	.probe = bootstage_probe,
	.remove = bootstage_remove,
	.driver = {
		.name = "bootstage",
		.of_match_table = bootstage_of_match,
	},
};

static int __init bootstage_init(void)
{
	bootstage_debugfs_dir = debugfs_create_dir(bootstage_driver.driver.name, NULL);
	return platform_driver_register(&bootstage_driver);
}
arch_initcall(bootstage_init);

static void __exit bootstage_exit(void)
{
	debugfs_remove_recursive(bootstage_debugfs_dir);
	platform_driver_unregister(&bootstage_driver);
}
module_exit(bootstage_exit)

MODULE_DESCRIPTION("Driver for Bootstage stash.");
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Francesco Valla <francesco@valla.it>");
