/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
 */

#ifndef __SOC_TEGRA_CFG_H__
#define __SOC_TEGRA_CFG_H__

#include <linux/types.h>

/**
 * Config settings are a list of DT properties holding each field's recommended
 * value. Field info is held in tegra_cfg_field and tegra_cfg_desc.
 * Data of all fields in a single register are parsed and stored in
 * tegra_cfg_reg. Struct tegra_cfg_list contains list of configurations
 * and each config tegra_cfg contains register list.
 * Client drivers provide field and register data through tegra_cfg_desc.
 */

/**
 * Register field and DT property mapping.
 * @name: device property name of the field.
 * @offset: offset of register from base.
 * @mask: mask of field within register.
 */
struct tegra_cfg_field_desc {
	const char *name;
	u32 offset;
	u32 mask;
};

#define TEGRA_CFG_FIELD(fname, roffset, fmask)	\
{						\
	.name = fname,				\
	.offset = roffset,			\
	.mask = fmask,				\
}

/**
 * Configuration setting from controller where it passes the total number of
 * registers having config, and their register field names.
 */
struct tegra_cfg_desc {
	unsigned int num_regs;
	unsigned int num_fields;
	const struct tegra_cfg_field_desc *fields;
};

/**
 * Configuration register info generated by combining all field config settings
 * in device tree of a register.
 * @offset: offset of register from base.
 * @mask: generated mask from aggregate of all field settings read from dt.
 * @value: generated value by combining all field properties read from dt.
 */
struct tegra_cfg_reg {
	u32 offset;
	u32 mask;
	u32 value;
};

/**
 * Per config info of all registers.
 */
struct tegra_cfg {
	const char *name;
	unsigned int num_regs;
	struct tegra_cfg_reg *regs;
};

/**
 * Config settings list.
 */
struct tegra_cfg_list {
	unsigned int num_cfg;
	struct tegra_cfg *cfg;
};

struct tegra_cfg *
tegra_cfg_get_by_name(struct device *dev,
		      const struct tegra_cfg_list *list,
		      const char *cfg_name);

struct tegra_cfg_list *tegra_cfg_get(struct device *dev,
				     const struct device_node *np,
				     const struct tegra_cfg_desc *cfg_dev);
#endif /* __SOC_TEGRA_CFG_H__ */
