# SPDX-License-Identifier: GPL-2.0-only

arm-cla-y := \
	cla-init.o \
	cla-ctx.o \
	cla-mtc.o \
	cla-ops.o \
	cla-regs.o \
	cla-sched.o \
	cla-topology.o \
	cla-user.o

obj-$(CONFIG_ARM_CLA) += arm-cla.o
