/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * CRC constants generated by:
 *
 *	./scripts/gen-crc-consts.py x86_pclmul crc16_msb_0x8bb7,crc32_lsb_0xedb88320,crc64_msb_0x42f0e1eba9ea3693,crc64_lsb_0x9a6c9329ac4bc9b5
 *
 * Do not edit manually.
 */

/*
 * CRC folding constants generated for most-significant-bit-first CRC-16 using
 * G(x) = x^16 + x^15 + x^11 + x^9 + x^8 + x^7 + x^5 + x^4 + x^2 + x + 1
 */
static const struct {
	u8 bswap_mask[16];
	u64 fold_across_2048_bits_consts[2];
	u64 fold_across_1024_bits_consts[2];
	u64 fold_across_512_bits_consts[2];
	u64 fold_across_256_bits_consts[2];
	u64 fold_across_128_bits_consts[2];
	u8 shuf_table[48];
	u64 barrett_reduction_consts[2];
} crc16_msb_0x8bb7_consts ____cacheline_aligned __maybe_unused = {
	.bswap_mask = {15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
	.fold_across_2048_bits_consts = {
		0x22c6,	/* x^(2048+0) mod G(x) */
		0x9f16,	/* x^(2048+64) mod G(x) */
	},
	.fold_across_1024_bits_consts = {
		0x6123,	/* x^(1024+0) mod G(x) */
		0x2295,	/* x^(1024+64) mod G(x) */
	},
	.fold_across_512_bits_consts = {
		0x1069,	/* x^(512+0) mod G(x) */
		0xdd31,	/* x^(512+64) mod G(x) */
	},
	.fold_across_256_bits_consts = {
		0x857d,	/* x^(256+0) mod G(x) */
		0x7acc,	/* x^(256+64) mod G(x) */
	},
	.fold_across_128_bits_consts = {
		0x2d56000000000000,	/* x^80 mod G(x) * x^48 */
		0x1faa,	/* x^(128+64) mod G(x) */
	},
	.shuf_table = {
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
		 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	},
	.barrett_reduction_consts = {
		0xf65a57f81d33a48a,	/* floor(x^80 / G(x)) - x^64 */
		0x18bb7,	/* G(x) */
	},
};

/*
 * CRC folding constants generated for least-significant-bit-first CRC-32 using
 * G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
 *        x^5 + x^4 + x^2 + x + 1
 */
static const struct {
	u64 fold_across_2048_bits_consts[2];
	u64 fold_across_1024_bits_consts[2];
	u64 fold_across_512_bits_consts[2];
	u64 fold_across_256_bits_consts[2];
	u64 fold_across_128_bits_consts[2];
	u8 shuf_table[48];
	u64 barrett_reduction_consts[2];
} crc32_lsb_0xedb88320_consts ____cacheline_aligned __maybe_unused = {
	.fold_across_2048_bits_consts = {
		0xce3371cb,	/* x^(2048+64-33) mod G(x) */
		0xe95c1271,	/* x^(2048+0-33) mod G(x) */
	},
	.fold_across_1024_bits_consts = {
		0x33fff533,	/* x^(1024+64-33) mod G(x) */
		0x910eeec1,	/* x^(1024+0-33) mod G(x) */
	},
	.fold_across_512_bits_consts = {
		0x8f352d95,	/* x^(512+64-33) mod G(x) */
		0x1d9513d7,	/* x^(512+0-33) mod G(x) */
	},
	.fold_across_256_bits_consts = {
		0xf1da05aa,	/* x^(256+64-33) mod G(x) */
		0x81256527,	/* x^(256+0-33) mod G(x) */
	},
	.fold_across_128_bits_consts = {
		0xae689191,	/* x^(128+64-33) mod G(x) */
		0xccaa009e,	/* x^(128+0-33) mod G(x) */
	},
	.shuf_table = {
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
		 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	},
	.barrett_reduction_consts = {
		0xb4e5b025f7011641,	/* floor(x^95 / G(x)) */
		0x1db710641,	/* G(x) */
	},
};

/*
 * CRC folding constants generated for most-significant-bit-first CRC-64 using
 * G(x) = x^64 + x^62 + x^57 + x^55 + x^54 + x^53 + x^52 + x^47 + x^46 +
 *        x^45 + x^40 + x^39 + x^38 + x^37 + x^35 + x^33 + x^32 + x^31 +
 *        x^29 + x^27 + x^24 + x^23 + x^22 + x^21 + x^19 + x^17 + x^13 +
 *        x^12 + x^10 + x^9 + x^7 + x^4 + x + 1
 */
static const struct {
	u8 bswap_mask[16];
	u64 fold_across_2048_bits_consts[2];
	u64 fold_across_1024_bits_consts[2];
	u64 fold_across_512_bits_consts[2];
	u64 fold_across_256_bits_consts[2];
	u64 fold_across_128_bits_consts[2];
	u8 shuf_table[48];
	u64 barrett_reduction_consts[2];
} crc64_msb_0x42f0e1eba9ea3693_consts ____cacheline_aligned __maybe_unused = {
	.bswap_mask = {15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0},
	.fold_across_2048_bits_consts = {
		0x7f52691a60ddc70d,	/* x^(2048+0) mod G(x) */
		0x7036b0389f6a0c82,	/* x^(2048+64) mod G(x) */
	},
	.fold_across_1024_bits_consts = {
		0x05cf79dea9ac37d6,	/* x^(1024+0) mod G(x) */
		0x001067e571d7d5c2,	/* x^(1024+64) mod G(x) */
	},
	.fold_across_512_bits_consts = {
		0x5f6843ca540df020,	/* x^(512+0) mod G(x) */
		0xddf4b6981205b83f,	/* x^(512+64) mod G(x) */
	},
	.fold_across_256_bits_consts = {
		0x571bee0a227ef92b,	/* x^(256+0) mod G(x) */
		0x44bef2a201b5200c,	/* x^(256+64) mod G(x) */
	},
	.fold_across_128_bits_consts = {
		0x05f5c3c7eb52fab6,	/* x^128 mod G(x) * x^0 */
		0x4eb938a7d257740e,	/* x^(128+64) mod G(x) */
	},
	.shuf_table = {
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
		 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	},
	.barrett_reduction_consts = {
		0x578d29d06cc4f872,	/* floor(x^128 / G(x)) - x^64 */
		0x42f0e1eba9ea3693,	/* G(x) - x^64 */
	},
};

/*
 * CRC folding constants generated for least-significant-bit-first CRC-64 using
 * G(x) = x^64 + x^63 + x^61 + x^59 + x^58 + x^56 + x^55 + x^52 + x^49 +
 *        x^48 + x^47 + x^46 + x^44 + x^41 + x^37 + x^36 + x^34 + x^32 +
 *        x^31 + x^28 + x^26 + x^23 + x^22 + x^19 + x^16 + x^13 + x^12 +
 *        x^10 + x^9 + x^6 + x^4 + x^3 + 1
 */
static const struct {
	u64 fold_across_2048_bits_consts[2];
	u64 fold_across_1024_bits_consts[2];
	u64 fold_across_512_bits_consts[2];
	u64 fold_across_256_bits_consts[2];
	u64 fold_across_128_bits_consts[2];
	u8 shuf_table[48];
	u64 barrett_reduction_consts[2];
} crc64_lsb_0x9a6c9329ac4bc9b5_consts ____cacheline_aligned __maybe_unused = {
	.fold_across_2048_bits_consts = {
		0x37ccd3e14069cabc,	/* x^(2048+64-1) mod G(x) */
		0xa043808c0f782663,	/* x^(2048+0-1) mod G(x) */
	},
	.fold_across_1024_bits_consts = {
		0xa1ca681e733f9c40,	/* x^(1024+64-1) mod G(x) */
		0x5f852fb61e8d92dc,	/* x^(1024+0-1) mod G(x) */
	},
	.fold_across_512_bits_consts = {
		0x0c32cdb31e18a84a,	/* x^(512+64-1) mod G(x) */
		0x62242240ace5045a,	/* x^(512+0-1) mod G(x) */
	},
	.fold_across_256_bits_consts = {
		0xb0bc2e589204f500,	/* x^(256+64-1) mod G(x) */
		0xe1e0bb9d45d7a44c,	/* x^(256+0-1) mod G(x) */
	},
	.fold_across_128_bits_consts = {
		0xeadc41fd2ba3d420,	/* x^(128+64-1) mod G(x) */
		0x21e9761e252621ac,	/* x^(128+0-1) mod G(x) */
	},
	.shuf_table = {
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
		 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	},
	.barrett_reduction_consts = {
		0x27ecfa329aef9f77,	/* floor(x^127 / G(x)) */
		0x34d926535897936b,	/* G(x) - 1 */
	},
};
