/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * CRC constants generated by:
 *
 *	./scripts/gen-crc-consts.py x86_pclmul crc32_lsb_0xedb88320
 *
 * Do not edit manually.
 */

/*
 * CRC folding constants generated for least-significant-bit-first CRC-32 using
 * G(x) = x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 +
 *        x^5 + x^4 + x^2 + x + 1
 */
static const struct {
	u64 fold_across_2048_bits_consts[2];
	u64 fold_across_1024_bits_consts[2];
	u64 fold_across_512_bits_consts[2];
	u64 fold_across_256_bits_consts[2];
	u64 fold_across_128_bits_consts[2];
	u8 shuf_table[48];
	u64 barrett_reduction_consts[2];
} crc32_lsb_0xedb88320_consts ____cacheline_aligned __maybe_unused = {
	.fold_across_2048_bits_consts = {
		0xce3371cb,	/* x^(2048+64-33) mod G(x) */
		0xe95c1271,	/* x^(2048+0-33) mod G(x) */
	},
	.fold_across_1024_bits_consts = {
		0x33fff533,	/* x^(1024+64-33) mod G(x) */
		0x910eeec1,	/* x^(1024+0-33) mod G(x) */
	},
	.fold_across_512_bits_consts = {
		0x8f352d95,	/* x^(512+64-33) mod G(x) */
		0x1d9513d7,	/* x^(512+0-33) mod G(x) */
	},
	.fold_across_256_bits_consts = {
		0xf1da05aa,	/* x^(256+64-33) mod G(x) */
		0x81256527,	/* x^(256+0-33) mod G(x) */
	},
	.fold_across_128_bits_consts = {
		0xae689191,	/* x^(128+64-33) mod G(x) */
		0xccaa009e,	/* x^(128+0-33) mod G(x) */
	},
	.shuf_table = {
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
		 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
		-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	},
	.barrett_reduction_consts = {
		0xb4e5b025f7011641,	/* floor(x^95 / G(x)) */
		0x1db710641,	/* G(x) */
	},
};
