# SPDX-License-Identifier: GPL-2.0

TEST_PROGS := \
	rdma_cm_baseline.sh \
	rdma_cm_trace_sequence.sh \
	rdma_cm_counter_delta.sh \
	rdma_cm_fault_injection.sh

TEST_FILES := \
	rdma_common.sh \
	rdma_cm_review_loop.sh

include ../../../lib.mk
