/* SPDX-License-Identifier: GPL-2.0 */

#ifndef __LINUX_PCS_AIROHA_H
#define __LINUX_PCS_AIROHA_H

/* XFI_MAC */
#define AIROHA_PCS_XFI_MAC_XFI_GIB_CFG		0x0
#define   AIROHA_PCS_XFI_RX_FRAG_LEN		GENMASK(26, 22)
#define   AIROHA_PCS_XFI_TX_FRAG_LEN		GENMASK(21, 17)
#define   AIROHA_PCS_XFI_IPG_NUM		GENMASK(15, 10)
#define   AIROHA_PCS_XFI_TX_FC_EN		BIT(5)
#define   AIROHA_PCS_XFI_RX_FC_EN		BIT(4)
#define   AIROHA_PCS_XFI_RXMPI_STOP		BIT(3)
#define   AIROHA_PCS_XFI_RXMBI_STOP		BIT(2)
#define   AIROHA_PCS_XFI_TXMPI_STOP		BIT(1)
#define   AIROHA_PCS_XFI_TXMBI_STOP		BIT(0)
#define AIROHA_PCS_XFI_MAC_XFI_LOGIC_RST	0x10
#define   AIROHA_PCS_XFI_MAC_LOGIC_RST		BIT(0)
#define AIROHA_PCS_XFI_MAC_XFI_MACADDRH		0x60
#define   AIROHA_PCS_XFI_MAC_MACADDRH		GENMASK(15, 0)
#define AIROHA_PCS_XFI_MAC_XFI_MACADDRL		0x64
#define   AIROHA_PCS_XFI_MAC_MACADDRL		GENMASK(31, 0)
#define AIROHA_PCS_XFI_MAC_XFI_CNT_CLR		0x100
#define   AIROHA_PCS_XFI_GLB_CNT_CLR		BIT(0)

#endif /* __LINUX_PCS_AIROHA_H */
