// SPDX-License-Identifier: GPL-2.0-only
/*
 * Author: Anjali Kulkarni <anjali.k.kulkarni@oracle.com>
 *
 * Copyright (c) 2024 Oracle and/or its affiliates.
 */

#include <pthread.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>

/*
 * This code tests a thread exit notification when thread exits abnormally.
 * Normally, when a thread exits abnormally, the kernel is not aware of the
 * exit code. This is usually only conveyed from child to parent via the
 * pthread_exit() and pthread_join() calls. Sometimes, however, a parent
 * process cannot monitor all child processes via pthread_join(), particularly
 * when there is a huge amount of child processes. In this case, the parent
 * has created the child with PTHREAD_CREATE_DETACHED attribute.
 * To fix this problem, either when child wants to convey non-zero exit via
 * pthread_exit() or in a signal handler, the child can notify the kernel's
 * connector module it's exit status via a netlink call with new type
 * PROC_CN_MCAST_NOTIFY. (Implemented in the thread_filter.c file).
 * This will send the exit code from the child to the kernel, which the kernel
 * can later return to proc_filter program when the child actually exits.
 * To test this usecase:
 * Compile:
 *	make thread
 *	make proc_filter
 * To see non-zero exit notifications, run:
 *	./proc_filter -f
 * Start the threads code, creating 2 threads, in another window:
 *	./threads
 * The above will also send SIGSEGV to one of the threads created.
 * After you see the proc_filter display both tids, kill it:
 * [Ctrl-C] in the window where "./proc_filter -f" is being run.
 * The results will be printed in the "./threads" window.
 */

extern int notify_netlink_thread_exit(unsigned int exit_code);

static void sigsegvh(int sig)
{
	unsigned int exit_code = (unsigned int) sig;
	/*
	 * Send any non-zero value to get a notification. Here we are
	 * sending the signal number for SIGSEGV which is 11
	 */
	notify_netlink_thread_exit(exit_code);
}

void *threadc1(void *ptr)
{
	signal(SIGSEGV, sigsegvh);

	*(int *)ptr = gettid();

	printf("Child 1 thread id %d, handling SIGSEGV\n", gettid());
	sleep(10);
	pthread_exit(NULL);
}

void *threadc2(void *ptr)
{
	int exit_val = 1;

	*(int *)ptr = gettid();

	printf("Child 2 thread id %d, wants to exit with value %d\n",
			gettid(), exit_val);
	sleep(2);
	notify_netlink_thread_exit(exit_val);
	pthread_exit(NULL);
}

static void verify_exit_status(int tid1, int tid2)
{
	int found1 = 0, found2 = 0;
	int pid, tgid, exit_code;
	size_t size = 1024;
	FILE *file;
	char *data;

	data = malloc(size * sizeof(char));
	if (data == NULL) {
		perror("malloc for data failed");
		exit(1);
	}

	file = fopen("exit.log", "r");
	if (file == NULL) {
		perror("fopen of exit.log failed");
		free(data);
		exit(1);
	}

	while (getline(&data, &size, file) != -1) {
		sscanf(data, "pid %d tgid %d code %d",
				&pid, &tgid, &exit_code);

		if (tgid != getpid()) {
			continue;
		}

		if (pid == tid1) {
		       if (exit_code == 11) {
				printf("Successful notification of SIGSEGV, tid %d\n",
						pid);
			} else {
				printf("Failure SIGSEGV tid %d, exit code %d\n",
					       pid, exit_code);
			}
			found1 = 1;
		} else if (pid == tid2) {
			if (exit_code == 1) {
				printf("Successful notification of thread exit tid %d\n",
						pid);
			} else {
				printf("Failure thread exit tid %d, exit code %d\n",
					       pid, exit_code);
			}
			found2 = 1;
		}
	}

	if (!found1)
		printf("tid %d not present in exit.log file\n", tid1);

	if (!found2)
		printf("tid %d not present in exit.log file\n", tid2);

	fclose(file);
	free(data);
}

static inline void init_threads(pthread_attr_t *attr)
{
	int ret;

	ret = pthread_attr_init(attr);
	if (ret != 0) {
		perror("pthread_attr_init failed");
		exit(ret);
	}

	ret = pthread_attr_setdetachstate(attr, PTHREAD_CREATE_DETACHED);
	if (ret != 0) {
		perror("pthread_attr_setdetachstate failed");
		exit(ret);
	}
}

static inline void destroy_thread_attr(pthread_attr_t *attr)
{
	int ret;

	ret = pthread_attr_destroy(attr);
	if (ret != 0) {
		perror("pthread_attr_destroy failed");
		exit(ret);
	}
}

int main(int argc, char **argv)
{
	pthread_t thread1, thread2;
	pthread_attr_t attr1, attr2;
	int tid1, tid2, ret;

	init_threads(&attr1);
	ret = pthread_create(&thread1, &attr1, *threadc1, &tid1);
	if (ret != 0) {
		perror("pthread_create failed");
		exit(ret);
	}

	init_threads(&attr2);
	ret = pthread_create(&thread2, &attr2, *threadc2, &tid2);
	if (ret != 0) {
		perror("pthread_create failed");
		exit(ret);
	}

	sleep(1);

	/* Send SIGSEGV to tid1 */
	kill(tid1, SIGSEGV);

	/* Wait for children to exit or be killed and for exit.log to
	 * be generated by ./proc_filter
	 */
	sleep(10);

	verify_exit_status(tid1, tid2);

	destroy_thread_attr(&attr1);
	destroy_thread_attr(&attr2);

	exit(0);
}
