/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (C) 2024 Mobileye Vision Technologies Ltd.
 */

#ifndef _DT_BINDINGS_MOBILEYE_EYEQ_RESET_H
#define _DT_BINDINGS_MOBILEYE_EYEQ_RESET_H

#define EQ7HR_SOUTH_DOM0_PCI_PHY	0
#define EQ7HR_SOUTH_DOM0_PCI_CTL	1
#define EQ7HR_SOUTH_DOM0_S_NOC		2
#define EQ7HR_SOUTH_DOM0_GBE_PHY	3
#define EQ7HR_SOUTH_DOM0_GBE_CTL	4

#define EQ7HR_SOUTH_DOM1_XSPI		0
#define EQ7HR_SOUTH_DOM1_UFS		1
#define EQ7HR_SOUTH_DOM1_S_VDIO		2

#define EQ7HR_EAST_ISP			0
#define EQ7HR_EAST_VEU			1
#define EQ7HR_EAST_LBIST		2

#define EQ7HR_WEST_GPU			0
#define EQ7HR_WEST_CAU			1
#define EQ7HR_WEST_LBIST		2
#define EQ7HR_WEST_GPU_LBIST		3

#define EQ7HR_PERIPH_GPIO		0
#define EQ7HR_PERIPH_EXT		1
#define EQ7HR_PERIPH_UART		2
#define EQ7HR_PERIPH_SPI		3
#define EQ7HR_PERIPH_I2C0		4
#define EQ7HR_PERIPH_I2C1		5
#define EQ7HR_PERIPH_I2C2		6
#define EQ7HR_PERIPH_I2S		7

#define EQ7HR_DDR_APB			0
#define EQ7HR_DDR_DMI			1
#define EQ7HR_DDR_DFI			2
#define EQ7HR_DDR_PHY_SMS		3
#define EQ7HR_DDR_CTL_SMS		4

#define EQ7HR_ACC_DOM0_VMP0		0
#define EQ7HR_ACC_DOM0_VMP1		1
#define EQ7HR_ACC_DOM0_VMP2		2
#define EQ7HR_ACC_DOM0_VMP3		3
#define EQ7HR_ACC_DOM0_MPC0		4
#define EQ7HR_ACC_DOM0_MPC1		5
#define EQ7HR_ACC_DOM0_PMA0		6
#define EQ7HR_ACC_DOM0_PMA1		7

#define EQ7HR_ACC_DOM1_NCORE0		0
#define EQ7HR_ACC_DOM1_NCORE1		1
#define EQ7HR_ACC_DOM1_NCORE0_M		2
#define EQ7HR_ACC_DOM1_NCORE1_M		3
#define EQ7HR_ACC_DOM1_NCORE_NOC	4
#define EQ7HR_ACC_DOM1_VMP_NOC		5
#define EQ7HR_ACC_DOM1_MPC_NOC		6
#define EQ7HR_ACC_DOM1_PMA_NOC		7

#define EQ7HR_XNN_DOM0_XNN0		0
#define EQ7HR_XNN_DOM0_XNN1		1
#define EQ7HR_XNN_DOM0_XNN2		2

#define EQ7HR_XNN_DOM1_XNN0		0
#define EQ7HR_XNN_DOM1_XNN1		1
#define EQ7HR_XNN_DOM1_XNN2		2
#define EQ7HR_XNN_DOM1_XNN3		3
#define EQ7HR_XNN_DOM1_NCORE		4
#define EQ7HR_XNN_DOM1_I2_0		5
#define EQ7HR_XNN_DOM1_I2_1		6
#define EQ7HR_XNN_DOM1_SMS_0		7
#define EQ7HR_XNN_DOM1_SMS_1		8

#endif
