/* SPDX-License-Identifier: (GPL-2.0-only OR MIT) */
/*
 * Copyright (c) 2025 Rockchip Electronics Co., Ltd.
 * Author: Elaine Zhang <zhangqing@rock-chips.com>
 */

#ifndef _DT_BINDINGS_RESET_ROCKCHIP_RV1126B_H
#define _DT_BINDINGS_RESET_ROCKCHIP_RV1126B_H

/* ==========================list all of reset fields id=========================== */
/* TOPCRU-->SOFTRST_CON00 */

/* TOPCRU-->SOFTRST_CON15 */
#define SRST_PRESETN_CRU				0
#define SRST_PRESETN_CRU_BIU				1

/* BUSCRU-->SOFTRST_CON00 */
#define SRST_ARESETN_TOP_BIU				2
#define SRST_ARESETN_RKCE_BIU				3
#define SRST_ARESETN_BUS_BIU				4
#define SRST_HRESETN_BUS_BIU				5
#define SRST_PRESETN_BUS_BIU				6
#define SRST_PRESETN_CRU_BUS				7
#define SRST_PRESETN_SYS_GRF				8
#define SRST_HRESETN_BOOTROM				9
#define SRST_ARESETN_GIC400				10
#define SRST_ARESETN_SPINLOCK				11
#define SRST_PRESETN_WDT_NS				12
#define SRST_TRESETN_WDT_NS				13

/* BUSCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_WDT_HPMCU				14
#define SRST_TRESETN_WDT_HPMCU				15
#define SRST_HRESETN_CACHE				16
#define SRST_PRESETN_HPMCU_MAILBOX			17
#define SRST_PRESETN_HPMCU_INTMUX			18
#define SRST_RESETN_HPMCU_FULL_CLUSTER			19
#define SRST_RESETN_HPMCU_PWUP				20
#define SRST_RESETN_HPMCU_ONLY_CORE			21
#define SRST_TRESETN_HPMCU_JTAG				22
#define SRST_PRESETN_RKDMA				23
#define SRST_ARESETN_RKDMA				24

/* BUSCRU-->SOFTRST_CON02 */
#define SRST_PRESETN_DCF				25
#define SRST_ARESETN_DCF				26
#define SRST_HRESETN_RGA				27
#define SRST_ARESETN_RGA				28
#define SRST_RESETN_CORE_RGA				29
#define SRST_PRESETN_TIMER				30
#define SRST_RESETN_TIMER0				31
#define SRST_RESETN_TIMER1				32
#define SRST_RESETN_TIMER2				33
#define SRST_RESETN_TIMER3				34
#define SRST_RESETN_TIMER4				35
#define SRST_RESETN_TIMER5				36
#define SRST_ARESETN_RKCE				37
#define SRST_RESETN_PKA_RKCE				38
#define SRST_HRESETN_RKRNG_S				39
#define SRST_HRESETN_RKRNG_NS				40

/* BUSCRU-->SOFTRST_CON03 */
#define SRST_PRESETN_I2C0				41
#define SRST_RESETN_I2C0				42
#define SRST_PRESETN_I2C1				43
#define SRST_RESETN_I2C1				44
#define SRST_PRESETN_I2C3				45
#define SRST_RESETN_I2C3				46
#define SRST_PRESETN_I2C4				47
#define SRST_RESETN_I2C4				48
#define SRST_PRESETN_I2C5				49
#define SRST_RESETN_I2C5				50
#define SRST_PRESETN_SPI0				51
#define SRST_RESETN_SPI0				52
#define SRST_PRESETN_SPI1				53
#define SRST_RESETN_SPI1				54

/* BUSCRU-->SOFTRST_CON04 */
#define SRST_PRESETN_PWM0				55
#define SRST_RESETN_PWM0				56
#define SRST_PRESETN_PWM2				57
#define SRST_RESETN_PWM2				58
#define SRST_PRESETN_PWM3				59
#define SRST_RESETN_PWM3				60

/* BUSCRU-->SOFTRST_CON05 */
#define SRST_PRESETN_UART1				61
#define SRST_SRESETN_UART1				62
#define SRST_PRESETN_UART2				63
#define SRST_SRESETN_UART2				64
#define SRST_PRESETN_UART3				65
#define SRST_SRESETN_UART3				66
#define SRST_PRESETN_UART4				67
#define SRST_SRESETN_UART4				68
#define SRST_PRESETN_UART5				69
#define SRST_SRESETN_UART5				70
#define SRST_PRESETN_UART6				71
#define SRST_SRESETN_UART6				72
#define SRST_PRESETN_UART7				73
#define SRST_SRESETN_UART7				74

/* BUSCRU-->SOFTRST_CON06 */
#define SRST_PRESETN_TSADC				75
#define SRST_RESETN_TSADC				76
#define SRST_HRESETN_SAI0				77
#define SRST_MRESETN_SAI0				78
#define SRST_HRESETN_SAI1				79
#define SRST_MRESETN_SAI1				80
#define SRST_HRESETN_SAI2				81
#define SRST_MRESETN_SAI2				82
#define SRST_HRESETN_RKDSM				83
#define SRST_MRESETN_RKDSM				84
#define SRST_HRESETN_PDM				85
#define SRST_MRESETN_PDM				86
#define SRST_RESETN_PDM					87

/* BUSCRU-->SOFTRST_CON07 */
#define SRST_HRESETN_ASRC0				88
#define SRST_RESETN_ASRC0				89
#define SRST_HRESETN_ASRC1				90
#define SRST_RESETN_ASRC1				91
#define SRST_PRESETN_AUDIO_ADC_BUS			92
#define SRST_MRESETN_AUDIO_ADC_BUS			93
#define SRST_PRESETN_RKCE				94
#define SRST_HRESETN_NS_RKCE				95
#define SRST_PRESETN_OTPC_NS				96
#define SRST_RESETN_SBPI_OTPC_NS			97
#define SRST_RESETN_USER_OTPC_NS			98
#define SRST_RESETN_OTPC_ARB				99
#define SRST_PRESETN_OTP_MASK				100

/* PERICRU-->SOFTRST_CON00 */
#define SRST_ARESETN_PERI_BIU				101
#define SRST_PRESETN_PERI_BIU				102
#define SRST_PRESETN_RTC_BIU				103
#define SRST_PRESETN_CRU_PERI				104
#define SRST_PRESETN_PERI_GRF				105
#define SRST_PRESETN_GPIO1				106
#define SRST_DBRESETN_GPIO1				107
#define SRST_PRESETN_IOC_VCCIO1				108
#define SRST_ARESETN_USB3OTG				109
#define SRST_HRESETN_USB2HOST				110
#define SRST_HRESETN_ARB_USB2HOST			111
#define SRST_PRESETN_RTC_TEST				112

/* PERICRU-->SOFTRST_CON01 */
#define SRST_HRESETN_EMMC				113
#define SRST_HRESETN_FSPI0				114
#define SRST_HRESETN_XIP_FSPI0				115
#define SRST_SRESETN_2X_FSPI0				116
#define SRST_RESETN_UTMI_USB2HOST			117
#define SRST_RESETN_REF_PIPEPHY				118
#define SRST_PRESETN_PIPEPHY				119
#define SRST_PRESETN_PIPEPHY_GRF			120
#define SRST_PRESETN_USB2PHY				121
#define SRST_RESETN_POR_USB2PHY				122
#define SRST_RESETN_OTG_USB2PHY				123
#define SRST_RESETN_HOST_USB2PHY			124

/* CORECRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_CORE			125
#define SRST_NCOREPORESET0				126
#define SRST_NCORESET0					127
#define SRST_NCOREPORESET1				128
#define SRST_NCORESET1					129
#define SRST_NCOREPORESET2				130
#define SRST_NCORESET2					131
#define SRST_NCOREPORESET3				132
#define SRST_NCORESET3					133
#define SRST_NDBGRESET					134
#define SRST_NL2RESET					135

/* CORECRU-->SOFTRST_CON01 */
#define SRST_ARESETN_CORE_BIU				136
#define SRST_PRESETN_CORE_BIU				137
#define SRST_HRESETN_CORE_BIU				138
#define SRST_PRESETN_DBG				139
#define SRST_POTRESETN_DBG				140
#define SRST_NTRESETN_DBG				141
#define SRST_PRESETN_CORE_PVTPLL			142
#define SRST_PRESETN_CRU_CORE				143
#define SRST_PRESETN_CORE_GRF				144
#define SRST_PRESETN_DFT2APB				145

/* PMUCRU-->SOFTRST_CON00 */
#define SRST_HRESETN_PMU_BIU				146
#define SRST_PRESETN_PMU_GPIO0				147
#define SRST_DBRESETN_PMU_GPIO0				148
#define SRST_PRESETN_PMU_HP_TIMER			149
#define SRST_RESETN_PMU_HP_TIMER			150
#define SRST_RESETN_PMU_32K_HP_TIMER			151

/* PMUCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_PWM1				152
#define SRST_RESETN_PWM1				153
#define SRST_PRESETN_I2C2				154
#define SRST_RESETN_I2C2				155
#define SRST_PRESETN_UART0				156
#define SRST_SRESETN_UART0				157

/* PMUCRU-->SOFTRST_CON02 */
#define SRST_PRESETN_RCOSC_CTRL				158
#define SRST_RESETN_REF_RCOSC_CTRL			159
#define SRST_PRESETN_IOC_PMUIO0				160
#define SRST_PRESETN_CRU_PMU				161
#define SRST_PRESETN_PMU_GRF				162
#define SRST_RESETN_PREROLL				163
#define SRST_RESETN_PREROLL_32K				164
#define SRST_HRESETN_PMU_SRAM				165

/* PMUCRU-->SOFTRST_CON03 */
#define SRST_PRESETN_WDT_LPMCU				166
#define SRST_TRESETN_WDT_LPMCU				167
#define SRST_RESETN_LPMCU_FULL_CLUSTER			168
#define SRST_RESETN_LPMCU_PWUP				169
#define SRST_RESETN_LPMCU_ONLY_CORE			170
#define SRST_TRESETN_LPMCU_JTAG				171
#define SRST_PRESETN_LPMCU_MAILBOX			172

/* PMU1CRU-->SOFTRST_CON00 */
#define SRST_PRESETN_SPI2AHB				173
#define SRST_HRESETN_SPI2AHB				174
#define SRST_HRESETN_FSPI1				175
#define SRST_HRESETN_XIP_FSPI1				176
#define SRST_SRESETN_1X_FSPI1				177
#define SRST_PRESETN_IOC_PMUIO1				178
#define SRST_PRESETN_CRU_PMU1				179
#define SRST_PRESETN_AUDIO_ADC_PMU			180
#define SRST_MRESETN_AUDIO_ADC_PMU			181
#define SRST_HRESETN_PMU1_BIU				182

/* PMU1CRU-->SOFTRST_CON01 */
#define SRST_PRESETN_LPDMA				183
#define SRST_ARESETN_LPDMA				184
#define SRST_HRESETN_LPSAI				185
#define SRST_MRESETN_LPSAI				186
#define SRST_PRESETN_AOA_TDD				187
#define SRST_PRESETN_AOA_FE				188
#define SRST_PRESETN_AOA_AAD				189
#define SRST_PRESETN_AOA_APB				190
#define SRST_PRESETN_AOA_SRAM				191

/* DDRCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_DDR_BIU				192
#define SRST_PRESETN_DDRC				193
#define SRST_PRESETN_DDRMON				194
#define SRST_RESETN_TIMER_DDRMON			195
#define SRST_PRESETN_DFICTRL				196
#define SRST_PRESETN_DDR_GRF				197
#define SRST_PRESETN_CRU_DDR				198
#define SRST_PRESETN_DDRPHY				199
#define SRST_PRESETN_DMA2DDR				200

/* SUBDDRCRU-->SOFTRST_CON00 */
#define SRST_ARESETN_SYSMEM_BIU				201
#define SRST_ARESETN_SYSMEM				202
#define SRST_ARESETN_DDR_BIU				203
#define SRST_ARESETN_DDRSCH0_CPU			204
#define SRST_ARESETN_DDRSCH1_NPU			205
#define SRST_ARESETN_DDRSCH2_POE			206
#define SRST_ARESETN_DDRSCH3_VI				207
#define SRST_RESETN_CORE_DDRC				208
#define SRST_RESETN_DDRMON				209
#define SRST_RESETN_DFICTRL				210
#define SRST_RESETN_RS					211
#define SRST_ARESETN_DMA2DDR				212
#define SRST_RESETN_DDRPHY				213

/* VICRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_ISP			214
#define SRST_ARESETN_GMAC_BIU				215
#define SRST_ARESETN_VI_BIU				216
#define SRST_HRESETN_VI_BIU				217
#define SRST_PRESETN_VI_BIU				218
#define SRST_PRESETN_CRU_VI				219
#define SRST_PRESETN_VI_GRF				220
#define SRST_PRESETN_VI_PVTPLL				221
#define SRST_PRESETN_DSMC				222
#define SRST_ARESETN_DSMC				223
#define SRST_HRESETN_CAN0				224
#define SRST_RESETN_CAN0				225
#define SRST_HRESETN_CAN1				226
#define SRST_RESETN_CAN1				227

/* VICRU-->SOFTRST_CON01 */
#define SRST_PRESETN_GPIO2				228
#define SRST_DBRESETN_GPIO2				229
#define SRST_PRESETN_GPIO4				230
#define SRST_DBRESETN_GPIO4				231
#define SRST_PRESETN_GPIO5				232
#define SRST_DBRESETN_GPIO5				233
#define SRST_PRESETN_GPIO6				234
#define SRST_DBRESETN_GPIO6				235
#define SRST_PRESETN_GPIO7				236
#define SRST_DBRESETN_GPIO7				237
#define SRST_PRESETN_IOC_VCCIO2				238
#define SRST_PRESETN_IOC_VCCIO4				239
#define SRST_PRESETN_IOC_VCCIO5				240
#define SRST_PRESETN_IOC_VCCIO6				241
#define SRST_PRESETN_IOC_VCCIO7				242

/* VICRU-->SOFTRST_CON02 */
#define SRST_RESETN_CORE_ISP				243
#define SRST_HRESETN_VICAP				244
#define SRST_ARESETN_VICAP				245
#define SRST_DRESETN_VICAP				246
#define SRST_ISP0RESETN_VICAP				247
#define SRST_RESETN_CORE_VPSS				248
#define SRST_RESETN_CORE_VPSL				249
#define SRST_PRESETN_CSI2HOST0				250
#define SRST_PRESETN_CSI2HOST1				251
#define SRST_PRESETN_CSI2HOST2				252
#define SRST_PRESETN_CSI2HOST3				253
#define SRST_HRESETN_SDMMC0				254
#define SRST_ARESETN_GMAC				255
#define SRST_PRESETN_CSIPHY0				256
#define SRST_PRESETN_CSIPHY1				257

/* VICRU-->SOFTRST_CON03 */
#define SRST_PRESETN_MACPHY				258
#define SRST_RESETN_MACPHY				259
#define SRST_PRESETN_SARADC1				260
#define SRST_RESETN_SARADC1				261
#define SRST_PRESETN_SARADC2				262
#define SRST_RESETN_SARADC2				263

/* VEPUCRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_VEPU			264
#define SRST_ARESETN_VEPU_BIU				265
#define SRST_HRESETN_VEPU_BIU				266
#define SRST_PRESETN_VEPU_BIU				267
#define SRST_PRESETN_CRU_VEPU				268
#define SRST_PRESETN_VEPU_GRF				269
#define SRST_PRESETN_GPIO3				270
#define SRST_DBRESETN_GPIO3				271
#define SRST_PRESETN_IOC_VCCIO3				272
#define SRST_PRESETN_SARADC0				273
#define SRST_RESETN_SARADC0				274
#define SRST_HRESETN_SDMMC1				275

/* VEPUCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_VEPU_PVTPLL			276
#define SRST_HRESETN_VEPU				277
#define SRST_ARESETN_VEPU				278
#define SRST_RESETN_CORE_VEPU				279

/* NPUCRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_NPU			280
#define SRST_ARESETN_NPU_BIU				281
#define SRST_HRESETN_NPU_BIU				282
#define SRST_PRESETN_NPU_BIU				283
#define SRST_PRESETN_CRU_NPU				284
#define SRST_PRESETN_NPU_GRF				285
#define SRST_PRESETN_NPU_PVTPLL				286
#define SRST_HRESETN_RKNN				287
#define SRST_ARESETN_RKNN				288

/* VDOCRU-->SOFTRST_CON00 */
#define SRST_ARESETN_RKVDEC_BIU				289
#define SRST_ARESETN_VDO_BIU				290
#define SRST_HRESETN_VDO_BIU				291
#define SRST_PRESETN_VDO_BIU				292
#define SRST_PRESETN_CRU_VDO				293
#define SRST_PRESETN_VDO_GRF				294
#define SRST_ARESETN_RKVDEC				295
#define SRST_HRESETN_RKVDEC				296
#define SRST_RESETN_HEVC_CA_RKVDEC			297
#define SRST_ARESETN_VOP				298
#define SRST_HRESETN_VOP				299
#define SRST_DRESETN_VOP				300
#define SRST_ARESETN_OOC				301
#define SRST_HRESETN_OOC				302
#define SRST_DRESETN_OOC				303

/* VDOCRU-->SOFTRST_CON01 */
#define SRST_HRESETN_RKJPEG				304
#define SRST_ARESETN_RKJPEG				305
#define SRST_ARESETN_RKMMU_DECOM			306
#define SRST_HRESETN_RKMMU_DECOM			307
#define SRST_DRESETN_DECOM				308
#define SRST_ARESETN_DECOM				309
#define SRST_PRESETN_DECOM				310
#define SRST_PRESETN_MIPI_DSI				311
#define SRST_PRESETN_DSIPHY				312

/* VCPCRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_VCP			313
#define SRST_ARESETN_VCP_BIU				314
#define SRST_HRESETN_VCP_BIU				315
#define SRST_PRESETN_VCP_BIU				316
#define SRST_PRESETN_CRU_VCP				317
#define SRST_PRESETN_VCP_GRF				318
#define SRST_PRESETN_VCP_PVTPLL				319
#define SRST_ARESETN_AISP_BIU				320
#define SRST_HRESETN_AISP_BIU				321
#define SRST_RESETN_CORE_AISP				322

/* VCPCRU-->SOFTRST_CON01 */
#define SRST_HRESETN_FEC				323
#define SRST_ARESETN_FEC				324
#define SRST_RESETN_CORE_FEC				325
#define SRST_HRESETN_AVSP				326
#define SRST_ARESETN_AVSP				327

#endif
