/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) Cadence Design Systems, Inc.
 *
 * Author: Swapnil Jakhade <sjakhade@cadence.com>
 */

#ifndef CDNS_MHDP_DSC_H_
#define CDNS_MHDP_DSC_H_

#include <linux/bitops.h>
#include <linux/io.h>
#include <linux/minmax.h>
#include <drm/display/drm_dsc_helper.h>
#include <drm/drm_bridge.h>
#include <drm/drm_connector.h>
#include <drm/drm_crtc_helper.h>
#include <drm/drm_print.h>

#define DSC_SUPPORTED_VERSION_MIN			1

#define DSC_OUTPUT_BUFFER_MAX_ADDRESS			3667U
#define DP_DSC_PPS_SIZE					128

#define CDNS_DP_COM_MAIN_CONF				0
#define CDNS_DP_COM_MAIN_CONF_SPLIT_PANEL		BIT(0)
#define CDNS_DP_COM_MAIN_CONF_MUX_MODE			BIT(1)
#define CDNS_DP_COM_MAIN_CONF_MUX_SEL_OUT		BIT(2)
#define CDNS_DP_COM_MAIN_CONF_DE_RASTER_EN		BIT(3)
#define CDNS_DP_COM_MAIN_CONF_INPUT_MODE		BIT(4)
#define CDNS_DP_COM_MAIN_CONF_MUX_EOC_EN		BIT(5)
#define CDNS_DP_COM_MAIN_CONF_AUTO_DB_UPDATE		BIT(6)

#define CDNS_DP_ENC_MAIN_CONF(d)			(0x120 + ((d) * 0x100))
#define CDNS_DP_ENC_MAIN_CONF_INPUT_BPC			GENMASK(1, 0)
#define CDNS_DP_ENC_MAIN_CONF_CONVERT_RGB		BIT(2)
#define CDNS_DP_ENC_MAIN_CONF_ENABLE_422		BIT(3)
#define CDNS_DP_ENC_MAIN_CONF_LINEBUF_DEPTH		GENMASK(7, 4)
#define CDNS_DP_ENC_MAIN_CONF_LINEBUF_DEPTH_SHIFT	4
#define CDNS_DP_ENC_MAIN_CONF_BITS_PER_PIXEL		GENMASK(17, 8)
#define CDNS_DP_ENC_MAIN_CONF_BITS_PER_PIXEL_SHIFT	8
#define CDNS_DP_ENC_MAIN_CONF_BLOCK_PRED_EN		BIT(18)
#define CDNS_DP_ENC_MAIN_CONF_VIDEO_MODE		BIT(19)
#define CDNS_DP_ENC_MAIN_CONF_ICH_RST_EOL		BIT(20)
#define CDNS_DP_ENC_MAIN_CONF_INITIAL_LINES		GENMASK(31, 24)
#define CDNS_DP_ENC_MAIN_CONF_INITIAL_LINES_SHIFT	24

#define CDNS_DP_ENC_PICTURE_SIZE(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x4)
#define CDNS_DP_ENC_PICTURE_SIZE_HEIGHT			GENMASK(31, 16)
#define CDNS_DP_ENC_PICTURE_SIZE_HEIGHT_SHIFT		16
#define CDNS_DP_ENC_PICTURE_SIZE_WIDTH			GENMASK(15, 0)

#define CDNS_DP_ENC_SLICE_SIZE(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x8)
#define CDNS_DP_ENC_SLICE_SIZE_HEIGHT			GENMASK(31, 16)
#define CDNS_DP_ENC_SLICE_SIZE_HEIGHT_SHIFT		16
#define CDNS_DP_ENC_SLICE_SIZE_WIDTH			GENMASK(15, 0)

#define CDNS_DP_ENC_MISC_SIZE(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0xc)
#define CDNS_DP_ENC_MISC_SIZE_CHUNK_SIZE		GENMASK(31, 16)
#define CDNS_DP_ENC_MISC_SIZE_CHUNK_SIZE_SHIFT		16
#define CDNS_DP_ENC_MISC_SIZE_OB_MAX_ADDR		GENMASK(15, 2)
#define CDNS_DP_ENC_MISC_SIZE_OB_MAX_ADDR_SHIFT		2
#define CDNS_DP_ENC_MISC_SIZE_LAST_GRP_SIZE		GENMASK(1, 0)

#define CDNS_DP_ENC_HRD_DELAYS(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x10)
#define CDNS_DP_ENC_HRD_DELAYS_INIT_DEC_DELAY		GENMASK(31, 16)
#define CDNS_DP_ENC_HRD_DELAYS_INIT_DEC_DELAY_SHIFT	16
#define CDNS_DP_ENC_HRD_DELAYS_INIT_XMIT_DELAY		GENMASK(9, 0)

#define CDNS_DP_ENC_RC_SCALE(d)				(CDNS_DP_ENC_MAIN_CONF(d) + 0x14)
#define CDNS_DP_ENC_RC_SCALE_INIT_SCALE_VALUE		GENMASK(5, 0)

#define CDNS_DP_ENC_RC_SCALE_INC_DEC(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x18)
#define CDNS_DP_ENC_RC_SCALE_DEC_INTERVAL		GENMASK(27, 16)
#define CDNS_DP_ENC_RC_SCALE_DEC_INTERVAL_SHIFT		16
#define CDNS_DP_ENC_RC_SCALE_INC_INTERVAL		GENMASK(15, 0)

#define CDNS_DP_ENC_RC_OFFSETS_1(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x1c)
#define CDNS_DP_ENC_RC_OFFSETS_1_FL_BPG_OFFSET		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_OFFSETS_2(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x20)
#define CDNS_DP_ENC_RC_OFFSETS_2_SL_BPG_OFFSET		GENMASK(31, 16)
#define CDNS_DP_ENC_RC_OFFSETS_2_SL_BPG_OFFSET_SHIFT	16
#define CDNS_DP_ENC_RC_OFFSETS_2_NFL_BPG_OFFSET		GENMASK(15, 0)

#define CDNS_DP_ENC_RC_OFFSETS_3(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x24)
#define CDNS_DP_ENC_RC_OFFSETS_3_FINAL_OFFSET		GENMASK(31, 16)
#define CDNS_DP_ENC_RC_OFFSETS_3_FINAL_OFFSET_SHIFT	16
#define CDNS_DP_ENC_RC_OFFSETS_3_INIT_OFFSET		GENMASK(15, 0)

#define CDNS_DP_ENC_FLATNESS_DETECTION(d)		(CDNS_DP_ENC_MAIN_CONF(d) + 0x28)
#define CDNS_DP_ENC_FLATNESS_DETECTION_THRESH		GENMASK(17, 10)
#define CDNS_DP_ENC_FLATNESS_DETECTION_THRESH_SHIFT	10
#define CDNS_DP_ENC_FLATNESS_DETECTION_MAX_QP		GENMASK(9, 5)
#define CDNS_DP_ENC_FLATNESS_DETECTION_MAX_QP_SHIFT	5
#define CDNS_DP_ENC_FLATNESS_DETECTION_MIN_QP		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MODEL_SIZE(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x2c)
#define CDNS_DP_ENC_RC_MODEL_SIZE_RC_MODEL_SIZE		GENMASK(15, 0)

#define CDNS_DP_ENC_RC_CONFIG(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x30)
#define CDNS_DP_ENC_RC_CONFIG_TGT_OFFSET_LO		GENMASK(27, 24)
#define CDNS_DP_ENC_RC_CONFIG_TGT_OFFSET_LO_SHIFT	24
#define CDNS_DP_ENC_RC_CONFIG_TGT_OFFSET_HI		GENMASK(23, 20)
#define CDNS_DP_ENC_RC_CONFIG_TGT_OFFSET_HI_SHIFT	20
#define CDNS_DP_ENC_RC_CONFIG_QUANT_INC_LIM_1		GENMASK(17, 13)
#define CDNS_DP_ENC_RC_CONFIG_QUANT_INC_LIM_1_SHIFT	13
#define CDNS_DP_ENC_RC_CONFIG_QUANT_INC_LIM_0		GENMASK(12, 8)
#define CDNS_DP_ENC_RC_CONFIG_QUANT_INC_LIM_0_SHIFT	8
#define CDNS_DP_ENC_RC_CONFIG_EDGE_FACTOR		GENMASK(3, 0)

#define CDNS_DP_ENC_RC_BUF_THRESH_0(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x34)
#define CDNS_DP_ENC_RC_BUF_THRESH_0_THRESH_3		GENMASK(31, 24)
#define CDNS_DP_ENC_RC_BUF_THRESH_0_THRESH_2		GENMASK(23, 16)
#define CDNS_DP_ENC_RC_BUF_THRESH_0_THRESH_1		GENMASK(15, 8)
#define CDNS_DP_ENC_RC_BUF_THRESH_0_THRESH_0		GENMASK(7, 0)

#define CDNS_DP_ENC_RC_BUF_THRESH_1(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x38)
#define CDNS_DP_ENC_RC_BUF_THRESH_1_THRESH_7		GENMASK(31, 24)
#define CDNS_DP_ENC_RC_BUF_THRESH_1_THRESH_6		GENMASK(23, 16)
#define CDNS_DP_ENC_RC_BUF_THRESH_1_THRESH_5		GENMASK(15, 8)
#define CDNS_DP_ENC_RC_BUF_THRESH_1_THRESH_4		GENMASK(7, 0)

#define CDNS_DP_ENC_RC_BUF_THRESH_2(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x3c)
#define CDNS_DP_ENC_RC_BUF_THRESH_2_THRESH_11		GENMASK(31, 24)
#define CDNS_DP_ENC_RC_BUF_THRESH_2_THRESH_10		GENMASK(23, 16)
#define CDNS_DP_ENC_RC_BUF_THRESH_2_THRESH_9		GENMASK(15, 8)
#define CDNS_DP_ENC_RC_BUF_THRESH_2_THRESH_8		GENMASK(7, 0)

#define CDNS_DP_ENC_RC_BUF_THRESH_3(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x40)
#define CDNS_DP_ENC_RC_BUF_THRESH_3_THRESH_13		GENMASK(15, 8)
#define CDNS_DP_ENC_RC_BUF_THRESH_3_THRESH_12		GENMASK(7, 0)

#define CDNS_DP_ENC_RC_BUF_THRESH_THRESH_3_SHIFT	24
#define CDNS_DP_ENC_RC_BUF_THRESH_THRESH_2_SHIFT	16
#define CDNS_DP_ENC_RC_BUF_THRESH_THRESH_1_SHIFT	8

#define CDNS_DP_ENC_RC_MIN_QP_0(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x44)
#define CDNS_DP_ENC_RC_MIN_QP_0_RANGE_4			GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MIN_QP_0_RANGE_3			GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MIN_QP_0_RANGE_2			GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MIN_QP_0_RANGE_1			GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MIN_QP_0_RANGE_0			GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MIN_QP_1(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x48)
#define CDNS_DP_ENC_RC_MIN_QP_1_RANGE_9			GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MIN_QP_1_RANGE_8			GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MIN_QP_1_RANGE_7			GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MIN_QP_1_RANGE_6			GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MIN_QP_1_RANGE_5			GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MIN_QP_2(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x4c)
#define CDNS_DP_ENC_RC_MIN_QP_2_RANGE_14		GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MIN_QP_2_RANGE_13		GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MIN_QP_2_RANGE_12		GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MIN_QP_2_RANGE_11		GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MIN_QP_2_RANGE_10		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MAX_QP_0(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x50)
#define CDNS_DP_ENC_RC_MAX_QP_0_RANGE_4			GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MAX_QP_0_RANGE_3			GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MAX_QP_0_RANGE_2			GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MAX_QP_0_RANGE_1			GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MAX_QP_0_RANGE_0			GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MAX_QP_1(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x54)
#define CDNS_DP_ENC_RC_MAX_QP_1_RANGE_9			GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MAX_QP_1_RANGE_8			GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MAX_QP_1_RANGE_7			GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MAX_QP_1_RANGE_6			GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MAX_QP_1_RANGE_5			GENMASK(4, 0)

#define CDNS_DP_ENC_RC_MAX_QP_2(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0x58)
#define CDNS_DP_ENC_RC_MAX_QP_2_RANGE_14		GENMASK(24, 20)
#define CDNS_DP_ENC_RC_MAX_QP_2_RANGE_13		GENMASK(19, 15)
#define CDNS_DP_ENC_RC_MAX_QP_2_RANGE_12		GENMASK(14, 10)
#define CDNS_DP_ENC_RC_MAX_QP_2_RANGE_11		GENMASK(9, 5)
#define CDNS_DP_ENC_RC_MAX_QP_2_RANGE_10		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_QP_RANGE_4_SHIFT			20
#define CDNS_DP_ENC_RC_QP_RANGE_3_SHIFT			15
#define CDNS_DP_ENC_RC_QP_RANGE_2_SHIFT			10
#define CDNS_DP_ENC_RC_QP_RANGE_1_SHIFT			5

#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0(d)		(CDNS_DP_ENC_MAIN_CONF(d) + 0x5c)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_4		GENMASK(24, 20)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_3		GENMASK(19, 15)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_2		GENMASK(14, 10)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_1		GENMASK(9, 5)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_0		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_1(d)		(CDNS_DP_ENC_MAIN_CONF(d) + 0x60)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_9		GENMASK(24, 20)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_8		GENMASK(19, 15)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_7		GENMASK(14, 10)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_6		GENMASK(9, 5)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_5		GENMASK(4, 0)

#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_2(d)		(CDNS_DP_ENC_MAIN_CONF(d) + 0x64)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_14		GENMASK(24, 20)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_13		GENMASK(19, 15)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_12		GENMASK(14, 10)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_11		GENMASK(9, 5)
#define CDNS_DP_ENC_RC_RANGE_BPG_OFFSETS_0_10		GENMASK(4, 0)

#define CDNS_DP_ENC_DPI_CTRL_OUT_DELAY(d)		(CDNS_DP_ENC_MAIN_CONF(d) + 0x68)
#define CDNS_DP_ENC_DPI_CTRL_OUT_DELAY_CYCLES		GENMASK(15, 0)

#define CDNS_DP_ENC_GENERAL_STATUS(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0xa0)
#define CDNS_DP_ENC_GENERAL_STATUS_OUT_BUFF_FULL_1	BIT(6)
#define CDNS_DP_ENC_GENERAL_STATUS_OUT_BUFF_FULL_0	BIT(5)
#define CDNS_DP_ENC_GENERAL_STATUS_OUT_BUFF_EMPTY_1	BIT(4)
#define CDNS_DP_ENC_GENERAL_STATUS_OUT_BUFF_EMPTY_0	BIT(3)
#define CDNS_DP_ENC_GENERAL_STATUS_FRAME_DONE		BIT(2)
#define CDNS_DP_ENC_GENERAL_STATUS_FRAME_STARTED	BIT(1)
#define CDNS_DP_ENC_GENERAL_STATUS_CE			BIT(0)

#define CDNS_DP_ENC_HSLICE_STATUS(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0xa4)
#define CDNS_DP_ENC_HSLICE_STATUS_ACTUAL_SLICE		GENMASK(31, 16)
#define CDNS_DP_ENC_HSLICE_STATUS_ACTUAL_LINE		GENMASK(15, 0)

#define CDNS_DP_ENC_OUT_STATUS(d)			(CDNS_DP_ENC_MAIN_CONF(d) + 0xa8)
#define CDNS_DP_ENC_OUT_STATUS_ACTUAL_SLICE		GENMASK(31, 16)
#define CDNS_DP_ENC_OUT_STATUS_ACTUAL_LINE		GENMASK(15, 0)

#define CDNS_DP_ENC_INT_STAT(d)				(CDNS_DP_ENC_MAIN_CONF(d) + 0xac)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_FULL_1		BIT(10)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_FULL_0		BIT(9)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_EMPTY_1		BIT(8)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_EMPTY_0		BIT(7)
#define CDNS_DP_ENC_INT_STAT_FRAME_DONE			BIT(6)
#define CDNS_DP_ENC_INT_STAT_FRAME_STARTED		BIT(5)
#define CDNS_DP_ENC_INT_STAT_CE				BIT(4)
#define CDNS_DP_ENC_INT_STAT_RC_BUFF_OVER_1		BIT(3)
#define CDNS_DP_ENC_INT_STAT_RC_BUFF_OVER_0		BIT(2)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_UND_1		BIT(1)
#define CDNS_DP_ENC_INT_STAT_OUT_BUFF_UND_0		BIT(0)

#define CDNS_DP_ENC_INT_CLR(d)				(CDNS_DP_ENC_MAIN_CONF(d) + 0xb0)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_FULL_1		BIT(10)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_FULL_0		BIT(9)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_EMPTY_1		BIT(8)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_EMPTY_0		BIT(7)
#define CDNS_DP_ENC_INT_CLR_FRAME_DONE			BIT(6)
#define CDNS_DP_ENC_INT_CLR_FRAME_STARTED		BIT(5)
#define CDNS_DP_ENC_INT_CLR_CE				BIT(4)
#define CDNS_DP_ENC_INT_CLR_RC_BUFF_OVER_1		BIT(3)
#define CDNS_DP_ENC_INT_CLR_RC_BUFF_OVER_0		BIT(2)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_UND_1		BIT(1)
#define CDNS_DP_ENC_INT_CLR_OUT_BUFF_UND_0		BIT(0)

#define CDNS_DP_ENC_INT_MASK(d)				(CDNS_DP_ENC_MAIN_CONF(d) + 0xb4)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_FULL_1		BIT(10)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_FULL_0		BIT(9)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_EMPTY_1		BIT(8)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_EMPTY_0		BIT(7)
#define CDNS_DP_ENC_INT_MASK_FRAME_DONE			BIT(6)
#define CDNS_DP_ENC_INT_MASK_FRAME_STARTED		BIT(5)
#define CDNS_DP_ENC_INT_MASK_CE				BIT(4)
#define CDNS_DP_ENC_INT_MASK_RC_BUFF_OVER_1		BIT(3)
#define CDNS_DP_ENC_INT_MASK_RC_BUFF_OVER_0		BIT(2)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_UND_1		BIT(1)
#define CDNS_DP_ENC_INT_MASK_OUT_BUFF_UND_0		BIT(0)

#define CDNS_DP_ENC_INT_TEST(d)				(CDNS_DP_ENC_MAIN_CONF(d) + 0xb8)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_FULL_1		BIT(10)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_FULL_0		BIT(9)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_EMPTY_1		BIT(8)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_EMPTY_0		BIT(7)
#define CDNS_DP_ENC_INT_TEST_FRAME_DONE			BIT(6)
#define CDNS_DP_ENC_INT_TEST_FRAME_STARTED		BIT(5)
#define CDNS_DP_ENC_INT_TEST_CE				BIT(4)
#define CDNS_DP_ENC_INT_TEST_RC_BUFF_OVER_1		BIT(3)
#define CDNS_DP_ENC_INT_TEST_RC_BUFF_OVER_0		BIT(2)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_UND_1		BIT(1)
#define CDNS_DP_ENC_INT_TEST_OUT_BUFF_UND_0		BIT(0)

void cdns_mhdp_dsc_write_config(struct cdns_mhdp_device *mhdp);
void cdns_mhdp_dsc_write_enc_config(struct cdns_mhdp_device *mhdp, int stream_id,
				    const struct drm_display_mode *mode);
int cdns_mhdp_dsc_sink_support(struct cdns_mhdp_device *mhdp);
int cdns_mhdp_compute_dsc_params(struct cdns_mhdp_device *mhdp);
int cdns_mhdp_dsc_send_pps_sdp(struct cdns_mhdp_device *mhdp, int stream_id);

#endif /* MHDP_DSC_H_ */
