/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Rockchip VIP Driver
 *
 * Copyright (C) 2018 Rockchip Electronics Co., Ltd.
 * Copyright (C) 2023 Mehdi Djait <mehdi.djait@bootlin.com>
 */

#ifndef _RK_VIP_REGS_H
#define _RK_VIP_REGS_H

/* VIP Reg Offset */
#define VIP_CTRL				0x00
#define VIP_INTEN				0x04
#define VIP_INTSTAT				0x08
#define VIP_FOR					0x0c
#define VIP_LINE_NUM_ADDR			0x10
#define VIP_FRM0_ADDR_Y				0x14
#define VIP_FRM0_ADDR_UV			0x18
#define VIP_FRM1_ADDR_Y				0x1c
#define VIP_FRM1_ADDR_UV			0x20
#define VIP_VIR_LINE_WIDTH			0x24
#define VIP_SET_SIZE				0x28
#define VIP_SCM_ADDR_Y				0x2c
#define VIP_SCM_ADDR_U				0x30
#define VIP_SCM_ADDR_V				0x34
#define VIP_WB_UP_FILTER			0x38
#define VIP_WB_LOW_FILTER			0x3c
#define VIP_WBC_CNT				0x40
#define VIP_CROP				0x44
#define VIP_SCL_CTRL				0x48
#define VIP_SCL_DST				0x4c
#define VIP_SCL_FCT				0x50
#define VIP_SCL_VALID_NUM			0x54
#define VIP_LINE_LOOP_CTR			0x58
#define VIP_FRAME_STATUS			0x60
#define VIP_CUR_DST				0x64
#define VIP_LAST_LINE				0x68
#define VIP_LAST_PIX				0x6c

/* RK1808 VIP CSI Registers Offset */
#define VIP_CSI_ID0_CTRL0			0x80
#define VIP_CSI_ID0_CTRL1			0x84
#define VIP_CSI_ID1_CTRL0			0x88
#define VIP_CSI_ID1_CTRL1			0x8c
#define VIP_CSI_ID2_CTRL0			0x90
#define VIP_CSI_ID2_CTRL1			0x94
#define VIP_CSI_ID3_CTRL0			0x98
#define VIP_CSI_ID3_CTRL1			0x9c
#define VIP_CSI_WATER_LINE			0xa0
#define VIP_CSI_FRM0_ADDR_Y_ID0			0xa4
#define VIP_CSI_FRM1_ADDR_Y_ID0			0xa8
#define VIP_CSI_FRM0_ADDR_UV_ID0		0xac
#define VIP_CSI_FRM1_ADDR_UV_ID0		0xb0
#define VIP_CSI_FRM0_VLW_Y_ID0			0xb4
#define VIP_CSI_FRM1_VLW_Y_ID0			0xb8
#define VIP_CSI_FRM0_VLW_UV_ID0			0xbc
#define VIP_CSI_FRM1_VLW_UV_ID0			0xc0
#define VIP_CSI_FRM0_ADDR_Y_ID1			0xc4
#define VIP_CSI_FRM1_ADDR_Y_ID1			0xc8
#define VIP_CSI_FRM0_ADDR_UV_ID1		0xcc
#define VIP_CSI_FRM1_ADDR_UV_ID1		0xd0
#define VIP_CSI_FRM0_VLW_Y_ID1			0xd4
#define VIP_CSI_FRM1_VLW_Y_ID1			0xd8
#define VIP_CSI_FRM0_VLW_UV_ID1			0xdc
#define VIP_CSI_FRM1_VLW_UV_ID1			0xe0
#define VIP_CSI_FRM0_ADDR_Y_ID2			0xe4
#define VIP_CSI_FRM1_ADDR_Y_ID2			0xe8
#define VIP_CSI_FRM0_ADDR_UV_ID2		0xec
#define VIP_CSI_FRM1_ADDR_UV_ID2		0xf0
#define VIP_CSI_FRM0_VLW_Y_ID2			0xf4
#define VIP_CSI_FRM1_VLW_Y_ID2			0xf8
#define VIP_CSI_FRM0_VLW_UV_ID2			0xfc
#define VIP_CSI_FRM1_VLW_UV_ID2			0x100
#define VIP_CSI_FRM0_ADDR_Y_ID3			0x104
#define VIP_CSI_FRM1_ADDR_Y_ID3			0x108
#define VIP_CSI_FRM0_ADDR_UV_ID3		0x10c
#define VIP_CSI_FRM1_ADDR_UV_ID3		0x110
#define VIP_CSI_FRM0_VLW_Y_ID3			0x114
#define VIP_CSI_FRM1_VLW_Y_ID3			0x118
#define VIP_CSI_FRM0_VLW_UV_ID3			0x11c
#define VIP_CSI_FRM1_VLW_UV_ID3			0x120
#define VIP_CSI_INTEN				0x124
#define VIP_CSI_INTSTAT				0x128
#define VIP_CSI_LINE_INT_NUM_ID0_1		0x12c
#define VIP_CSI_LINE_INT_NUM_ID2_3		0x130
#define VIP_CSI_LINE_CNT_ID0_1			0x134
#define VIP_CSI_LINE_CNT_ID2_3			0x138
#define VIP_CSI_ID0_CROP_START			0x13c
#define VIP_CSI_ID1_CROP_START			0x140
#define VIP_CSI_ID2_CROP_START			0x144
#define VIP_CSI_ID3_CROP_START			0x148

/* The key register bit description */

/* VIP_CTRL Reg */
#define VIP_CTRL_ENABLE_CAPTURE			BIT(0)
#define VIP_CTRL_MODE_PINGPONG			BIT(1)
#define VIP_CTRL_MODE_LINELOOP			BIT(2)
#define VIP_CTRL_AXI_BURST_16			(0xF << 12)

/* VIP_INTEN */
#define VIP_INTEN_FRAME_END_EN			BIT(0)
#define VIP_INTEN_LINE_ERR_EN			BIT(2)
#define VIP_INTEN_BUS_ERR_EN			BIT(6)
#define VIP_INTEN_SCL_ERR_EN			BIT(7)
#define VIP_INTEN_PST_INF_FRAME_END_EN		BIT(9)

/* VIP INTSTAT */
#define VIP_INTSTAT_CLS				0x3FF
#define VIP_INTSTAT_FRAME_END			BIT(0)
#define VIP_INTSTAT_LINE_END			BIT(1)
#define VIP_INTSTAT_LINE_ERR			BIT(2)
#define VIP_INTSTAT_PIX_ERR			BIT(3)
#define VIP_INTSTAT_DFIFO_OF			BIT(5)
#define VIP_INTSTAT_BUS_ERR			BIT(6)
#define VIP_INTSTAT_PRE_INF_FRAME_END		BIT(8)
#define VIP_INTSTAT_PST_INF_FRAME_END		BIT(9)
#define VIP_INTSTAT_FRAME_END_CLR		BIT(0)
#define VIP_INTSTAT_LINE_END_CLR		BIT(1)
#define VIP_INTSTAT_LINE_ERR_CLR		BIT(2)
#define VIP_INTSTAT_PST_INF_FRAME_END_CLR	BIT(9)
#define VIP_INTSTAT_ERR				0xFC

/* VIP_FRAME STATUS */
#define VIP_FRAME_STAT_CLS			0x00
/* write 0 to clear frame 0 */
#define VIP_FRAME_FRM0_STAT_CLS			0x20

/* VIP_FORMAT */
#define VIP_FORMAT_VSY_HIGH_ACTIVE		BIT(0)
#define VIP_FORMAT_HSY_LOW_ACTIVE		BIT(1)

#define VIP_FORMAT_INPUT_MODE_YUV		(0x00 << 2)
#define VIP_FORMAT_INPUT_MODE_PAL		(0x02 << 2)
#define VIP_FORMAT_INPUT_MODE_NTSC		(0x03 << 2)
#define VIP_FORMAT_INPUT_MODE_BT1120		(0x07 << 2)
#define VIP_FORMAT_INPUT_MODE_RAW		(0x04 << 2)
#define VIP_FORMAT_INPUT_MODE_JPEG		(0x05 << 2)
#define VIP_FORMAT_INPUT_MODE_MIPI		(0x06 << 2)

#define VIP_FORMAT_YUV_INPUT_ORDER_UYVY		(0x00 << 5)
#define VIP_FORMAT_YUV_INPUT_ORDER_YVYU		BIT(5)
#define VIP_FORMAT_YUV_INPUT_ORDER_VYUY		(0x10 << 5)
#define VIP_FORMAT_YUV_INPUT_ORDER_YUYV		(0x03 << 5)
#define VIP_FORMAT_YUV_INPUT_422		(0x00 << 7)
#define VIP_FORMAT_YUV_INPUT_420		BIT(7)

#define VIP_FORMAT_INPUT_420_ORDER_ODD		BIT(8)

#define VIP_FORMAT_CCIR_INPUT_ORDER_EVEN	BIT(9)

#define VIP_FORMAT_RAW_DATA_WIDTH_8		(0x00 << 11)
#define VIP_FORMAT_RAW_DATA_WIDTH_10		BIT(11)
#define VIP_FORMAT_RAW_DATA_WIDTH_12		(0x02 << 11)

#define VIP_FORMAT_YUV_OUTPUT_422		(0x00 << 16)
#define VIP_FORMAT_YUV_OUTPUT_420		BIT(16)

#define VIP_FORMAT_OUTPUT_420_ORDER_EVEN	(0x00 << 17)
#define VIP_FORMAT_OUTPUT_420_ORDER_ODD		BIT(17)

#define VIP_FORMAT_RAWD_DATA_LITTLE_ENDIAN	(0x00 << 18)
#define VIP_FORMAT_RAWD_DATA_BIG_ENDIAN		BIT(18)

#define VIP_FORMAT_UV_STORAGE_ORDER_UVUV	(0x00 << 19)
#define VIP_FORMAT_UV_STORAGE_ORDER_VUVU	BIT(19)

#define VIP_FORMAT_BT1120_CLOCK_SINGLE_EDGES	(0x00 << 24)
#define VIP_FORMAT_BT1120_CLOCK_DOUBLE_EDGES	BIT(24)
#define VIP_FORMAT_BT1120_TRANSMIT_INTERFACE	(0x00 << 25)
#define VIP_FORMAT_BT1120_TRANSMIT_PROGRESS	BIT(25)
#define VIP_FORMAT_BT1120_YC_SWAP		BIT(26)

/* VIP_SCL_CTRL */
#define VIP_SCL_CTRL_ENABLE_SCL_DOWN		BIT(0)
#define VIP_SCL_CTRL_ENABLE_SCL_UP		BIT(1)
#define VIP_SCL_CTRL_ENABLE_YUV_16BIT_BYPASS	BIT(4)
#define VIP_SCL_CTRL_ENABLE_RAW_16BIT_BYPASS	BIT(5)
#define VIP_SCL_CTRL_ENABLE_32BIT_BYPASS	BIT(6)
#define VIP_SCL_CTRL_DISABLE_32BIT_BYPASS	(0x00 << 6)

/* VIP_INTSTAT */
#define VIP_INTSTAT_F0_READY			BIT(0)
#define VIP_INTSTAT_F1_READY			BIT(1)

/* VIP_CROP */
#define VIP_CROP_Y_SHIFT			16
#define VIP_CROP_X_SHIFT			0

/* VIP_CSI_ID_CTRL0 */
#define VIP_CSI_ENABLE_CAPTURE			BIT(0)
#define VIP_CSI_WRDDR_TYPE_RAW8			(0x0 << 1)
#define VIP_CSI_WRDDR_TYPE_RAW10		BIT(1)
#define VIP_CSI_WRDDR_TYPE_RAW12		(0x2 << 1)
#define VIP_CSI_WRDDR_TYPE_RGB888		(0x3 << 1)
#define VIP_CSI_WRDDR_TYPE_YUV422		(0x4 << 1)
#define VIP_CSI_ENABLE_COMMAND_MODE		BIT(4)
#define VIP_CSI_ENABLE_CROP			BIT(5)

/* VIP_CSI_INTEN */
#define VIP_CSI_FRAME0_START_INTEN(id)		(0x1 << ((id) * 2))
#define VIP_CSI_FRAME1_START_INTEN(id)		(0x1 << ((id) * 2 + 1))
#define VIP_CSI_FRAME0_END_INTEN(id)		(0x1 << ((id) * 2 + 8))
#define VIP_CSI_FRAME1_END_INTEN(id)		(0x1 << ((id) * 2 + 9))
#define VIP_CSI_DMA_Y_FIFO_OVERFLOW_INTEN	BIT(16)
#define VIP_CSI_DMA_UV_FIFO_OVERFLOW_INTEN	BIT(17)
#define VIP_CSI_CONFIG_FIFO_OVERFLOW_INTEN	BIT(18)
#define VIP_CSI_BANDWIDTH_LACK_INTEN		BIT(19)
#define VIP_CSI_RX_FIFO_OVERFLOW_INTEN		BIT(20)
#define VIP_CSI_ALL_FRAME_START_INTEN		(0xff << 0)
#define VIP_CSI_ALL_FRAME_END_INTEN		(0xff << 8)
#define VIP_CSI_ALL_ERROR_INTEN			(0x1f << 16)

/* VIP_CSI_INTSTAT */
#define VIP_CSI_FRAME0_START_ID0		BIT(0)
#define VIP_CSI_FRAME1_START_ID0		BIT(1)
#define VIP_CSI_FRAME0_START_ID1		BIT(2)
#define VIP_CSI_FRAME1_START_ID1		BIT(3)
#define VIP_CSI_FRAME0_START_ID2		BIT(4)
#define VIP_CSI_FRAME1_START_ID2		BIT(5)
#define VIP_CSI_FRAME0_START_ID3		BIT(6)
#define VIP_CSI_FRAME1_START_ID3		BIT(7)
#define VIP_CSI_FRAME0_END_ID0			BIT(8)
#define VIP_CSI_FRAME1_END_ID0			BIT(9)
#define VIP_CSI_FRAME0_END_ID1			BIT(10)
#define VIP_CSI_FRAME1_END_ID1			BIT(11)
#define VIP_CSI_FRAME0_END_ID2			BIT(12)
#define VIP_CSI_FRAME1_END_ID2			BIT(13)
#define VIP_CSI_FRAME0_END_ID3			BIT(14)
#define VIP_CSI_FRAME1_END_ID3			BIT(15)
#define VIP_CSI_DMA_Y_FIFO_OVERFLOW		BIT(16)
#define VIP_CSI_DMA_UV_FIFO_OVERFLOW		BIT(17)
#define VIP_CSI_CONFIG_FIFO_OVERFLOW		BIT(18)
#define VIP_CSI_BANDWIDTH_LACK			BIT(19)
#define VIP_CSI_RX_FIFO_OVERFLOW		BIT(20)

#define VIP_CSI_FIFO_OVERFLOW	(VIP_CSI_DMA_Y_FIFO_OVERFLOW |	\
				 VIP_CSI_DMA_UV_FIFO_OVERFLOW |	\
				 VIP_CSI_CONFIG_FIFO_OVERFLOW |	\
				 VIP_CSI_RX_FIFO_OVERFLOW)

/* CSI Host Registers Define */
#define VIP_CSIHOST_N_LANES			0x04
#define VIP_CSIHOST_PHY_RSTZ			0x0c
#define VIP_CSIHOST_RESETN			0x10
#define VIP_CSIHOST_ERR1			0x20
#define VIP_CSIHOST_ERR2			0x24
#define VIP_CSIHOST_MSK1			0x28
#define VIP_CSIHOST_MSK2			0x2c
#define VIP_CSIHOST_CONTROL			0x40

#define VIP_SW_CPHY_EN(x)			((x) << 0)
#define VIP_SW_DSI_EN(x)			((x) << 4)
#define VIP_SW_DATATYPE_FS(x)			((x) << 8)
#define VIP_SW_DATATYPE_FE(x)			((x) << 14)
#define VIP_SW_DATATYPE_LS(x)			((x) << 20)
#define VIP_SW_DATATYPE_LE(x)			((x) << 26)

#endif
