# SPDX-License-Identifier: GPL-2.0

snd-quantum-y := quantum_main.o quantum_dma.o quantum_midi.o \
                 quantum_mixer.o quantum_pcm.o quantum_tci.o

obj-$(CONFIG_SND_QUANTUM) += snd-quantum.o
