# StarFive Platform Support
obj-$(CONFIG_SND_SOC_JH7110_PWMDAC) += jh7110_pwmdac.o
obj-$(CONFIG_SND_SOC_JH7110_TDM) += jh7110_tdm.o

obj-$(CONFIG_SND_SOC_JH8100_CADENCE_I2S) += jh8100-i2s.o
jh8100-i2s-y := cdns-jh8100-i2s.o
jh8100-i2s-$(CONFIG_SND_SOC_JH8100_CADENCE_I2S_PCM) += cdns-jh8100-i2s-pcm.o
