# SPDX-License-Identifier: GPL-2.0

zynqmp-allegro-objs := zynqmp-allegro-core.o zynqmp-allegro-mail.o
zynqmp-allegro-objs += nal-rbsp.o nal-h264.o nal-hevc.o

obj-$(CONFIG_VIDEO_ZYNQMP_ALLEGRO_DVT) += zynqmp-allegro.o
