# SPDX-License-Identifier: GPL-2.0+
# RPL platform Support
snd-rpl-pci-acp6x-y	:= rpl-pci-acp6x.o
snd-rpl-acp6x-pdm-dma-y	:= rpl-acp6x-pdm-dma.o
snd-soc-rpl-acp6x-mach-y	:= rpl-acp6x-mach.o

obj-$(CONFIG_SND_SOC_AMD_RPL_ACP6x) += snd-rpl-pci-acp6x.o
obj-$(CONFIG_SND_SOC_AMD_RPL_ACP6x) += snd-rpl-acp6x-pdm-dma.o
obj-$(CONFIG_SND_SOC_AMD_RPL_MACH)   += snd-soc-rpl-acp6x-mach.o
