/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2025-2028 Red Hat, Inc. Gabriele Monaco <gmonaco@redhat.com>
 *
 * Hybrid automata (HA) monitor functions, to be used together
 * with automata models in C generated by the dot2k tool.
 *
 * This type of monitors extends the Deterministic automata (DA) class by
 * adding a set of environment variables (e.g. clocks) that can be used to
 * constraint the valid transitions.
 *
 * The dot2k tool is available at tools/verification/dot2k/
 *
 * For further information, see:
 *   Documentation/trace/rv/ha_monitor_synthesis.rst
 */

#ifndef _RV_HA_MONITOR_H
#define _RV_HA_MONITOR_H

#include <rv/automata.h>
#include <rv/da_common.h>

#if RV_MON_TYPE == RV_MON_GLOBAL || RV_MON_TYPE == RV_MON_PER_CPU
static bool ha_monitor_handle_constraint(enum states curr_state, enum events event, enum states next_state);
#elif RV_MON_TYPE == RV_MON_PER_TASK || RV_MON_TYPE == RV_MON_PER_OBJ
static bool ha_monitor_handle_constraint(monitor_target target, enum states curr_state, enum events event, enum states next_state);
#endif
static inline void ha_monitor_init_env(struct da_monitor *da_mon);
static inline void ha_monitor_reset_env(struct da_monitor *da_mon);
static inline bool ha_cancel_timer(struct ha_monitor *ha_mon);
#define da_monitor_event_hook ha_monitor_handle_constraint
#define da_monitor_init_hook ha_monitor_init_env
#define da_monitor_reset_hook ha_monitor_reset_env

#include <rv/da_monitor.h>
#include <linux/seq_buf.h>

/* This simplifies things since da_mon and ha_mon coexist in the same union */
_Static_assert(offsetof(struct ha_monitor, da_mon) == 0,
	       "da_mon must be the first element in an ha_mon!");
#define to_ha_monitor(da) ((struct ha_monitor *)da)

#define ENV_MAX CONCATENATE(env_max_, MONITOR_NAME)
#define ENV_MAX_STORED CONCATENATE(env_max_stored_, MONITOR_NAME)
#define envs CONCATENATE(envs_, MONITOR_NAME)

/* Environment storage before being reset */
#define ENV_INVALID_VALUE U64_MAX
/* Error with no event occurs only on timeouts */
#define EVENT_NONE EVENT_MAX
#define EVENT_NONE_LBL "none"

#ifdef CONFIG_RV_REACTORS

/*
 * Trigger the reaction after a failed environment constraint (e.g. related to a
 * clock).
 */
static void ha_cond_react(enum states curr_state, enum events event, char *env)
{
	if (!rv_reacting_on() || !RV_MONITOR_NAME.react)
		return;
	RV_MONITOR_NAME.react("rv: monitor %s does not allow event %s on state %s with env %s\n",
			__stringify(MONITOR_NAME),
			event == EVENT_NONE ? EVENT_NONE_LBL : model_get_event_name(event),
			model_get_state_name(curr_state),
			env);
}

#else /* CONFIG_RV_REACTOR */

static void ha_cond_react(enum states curr_state, enum events event, char *env)
{
	return;
}
#endif

/*
 * model_get_state_name - return the (string) name of the given state
 */
static char *model_get_env_name(enum envs env)
{
	if ((env < 0) || (env >= ENV_MAX))
		return "INVALID";

	return RV_AUTOMATON_NAME.env_names[env];
}
static enum hrtimer_restart ha_monitor_timer_callback(struct hrtimer *timer);

/* Should be supplied by the monitor */
static u64 ha_get_env(struct ha_monitor *ha_mon, enum envs env);
static bool ha_verify_constraint(struct ha_monitor *ha_mon,
				 enum states curr_state,
				 enum events event,
				 enum states next_state);

/*
 * ha_monitor_reset_all_stored - reset all environment variables in the monitor
 */
static inline void ha_monitor_reset_all_stored(struct ha_monitor *ha_mon)
{
	for (int i = 0; i < ENV_MAX_STORED; i++)
		smp_store_mb(ha_mon->env_store[i], ENV_INVALID_VALUE);
}

/*
 * ha_monitor_init_env - setup timer and reset all environment
 *
 * Called from a hook in the DA start functions, it supplies the da_mon
 * corresponding to the current ha_mon.
 * Not all hybrid automata require the timer, still set it for simplicity.
 */
static inline void ha_monitor_init_env(struct da_monitor *da_mon)
{
	struct ha_monitor *ha_mon = to_ha_monitor(da_mon);

	ha_monitor_reset_all_stored(ha_mon);
	if (unlikely(!ha_mon->timer.base))
		hrtimer_setup(&ha_mon->timer, ha_monitor_timer_callback,
			      CLOCK_MONOTONIC, HRTIMER_MODE_REL);
}

/*
 * ha_monitor_reset_env - stop timer and reset all environment
 *
 * Called from a hook in the DA reset functions, it supplies the da_mon
 * corresponding to the current ha_mon.
 * Not all hybrid automata require the timer, still clear it for simplicity.
 */
static inline void ha_monitor_reset_env(struct da_monitor *da_mon)
{
	struct ha_monitor *ha_mon = to_ha_monitor(da_mon);

	ha_monitor_reset_all_stored(ha_mon);
	/* Initialisation resets the monitor before initialising the timer */
	if (likely(ha_mon->timer.base))
		ha_cancel_timer(ha_mon);
}

/*
 * ha_monitor_env_invalid - return true if env has not been initialised
 */
static inline bool ha_monitor_env_invalid(struct ha_monitor *ha_mon, enum envs env)
{
	return READ_ONCE(ha_mon->env_store[env]) == ENV_INVALID_VALUE;
}

/*
 * ha_monitor_all_env_is_valid - return true if all env has been initialised
 */
static inline bool ha_monitor_all_env_is_valid(struct ha_monitor *ha_mon)
{
	for (int i = 0; i < ENV_MAX_STORED; i++) {
		if (ha_monitor_env_invalid(ha_mon, i))
			return false;
	}
	return true;
}

static inline void ha_get_env_string(struct seq_buf * s, struct ha_monitor *ha_mon)
{
	const char *format_str = "%s=%llu";

	for (int i = 0; i < ENV_MAX; i++) {
		seq_buf_printf(s, format_str, model_get_env_name(i),
			       ha_get_env(ha_mon, i));
		format_str = ",%s=%llu";
	}
}

#if RV_MON_TYPE == RV_MON_GLOBAL || RV_MON_TYPE == RV_MON_PER_CPU

/*
 * ha_get_monitor - return the global or per-cpu monitor address
 */
static inline struct ha_monitor *ha_get_monitor(void)
{
	return to_ha_monitor(da_get_monitor());
}

/*
 * ha_monitor_handle_constraint - handle the constraint on the current transition
 *
 * If the monitor implementation defines a constraint in the transition from
 * curr_state to event, react and trace appropriately as well as return false.
 * This function is called from the hook in the DA event handle function and
 * triggers a failure in the monitor.
 */
static bool ha_monitor_handle_constraint(enum states curr_state,
					 enum events event,
					 enum states next_state)
{
	struct ha_monitor *ha_mon = ha_get_monitor();
	DECLARE_SEQ_BUF(env_string, MAX_DA_NAME_LEN);
	bool env_was_valid;

	env_was_valid = ha_monitor_all_env_is_valid(ha_mon);

	if (ha_verify_constraint(ha_mon, curr_state, event, next_state))
		return true;

	/*
	 * If we started with an uninitialised environment, chances are the
	 * failure is a false positive. Do not fail the monitor just this time.
	 * Note that we need to run ha_verify_constraint first as it might
	 * initialise the environment.
	 */
	if (!env_was_valid)
		return true;

	ha_get_env_string(&env_string, ha_mon);
	ha_cond_react(curr_state, event, env_string.buffer);
	CONCATENATE(trace_error_env_, MONITOR_NAME)(
			   model_get_state_name(curr_state),
			   model_get_event_name(event),
			   env_string.buffer);
	return false;
}

static enum hrtimer_restart ha_monitor_timer_callback(struct hrtimer *timer)
{
	struct ha_monitor *ha_mon = container_of(timer, struct ha_monitor, timer);
	enum states curr_state = READ_ONCE(ha_mon->da_mon.curr_state);
	DECLARE_SEQ_BUF(env_string, MAX_DA_NAME_LEN);

	ha_get_env_string(&env_string, ha_mon);
	ha_cond_react(curr_state, EVENT_NONE, env_string.buffer);
	CONCATENATE(trace_error_env_, MONITOR_NAME)(
		    model_get_state_name(curr_state),
		    EVENT_NONE_LBL,
		    env_string.buffer);

	da_monitor_reset(&ha_mon->da_mon);

	return HRTIMER_NORESTART;
}

#elif RV_MON_TYPE == RV_MON_PER_TASK || RV_MON_TYPE == RV_MON_PER_OBJ

/*
 * ha_get_monitor - return the per-task monitor address
 */
static inline struct ha_monitor *ha_get_monitor(monitor_target target)
{
	return to_ha_monitor(da_get_monitor(target));
}

/*
 * ha_get_target - return the object associated to the monitor
 */
static inline monitor_target ha_get_target(struct ha_monitor *ha_mon)
{
	/* tasks have a union, the offset of da_mon and ha_mon are the same */
	return da_get_target((struct da_monitor *)ha_mon);
}

/*
 * ha_monitor_handle_constraint - handle the constraint on the current transition
 *
 * If the monitor implementation defines a constraint in the transition from
 * curr_state to event, react and trace appropriately as well as return false.
 * This function is called from the hook in the DA event handle function and
 * triggers a failure in the monitor.
 */
static bool ha_monitor_handle_constraint(monitor_target target,
					 enum states curr_state,
					 enum events event,
					 enum states next_state)
{
	struct ha_monitor *ha_mon = ha_get_monitor(target);
	DECLARE_SEQ_BUF(env_string, 32);
	bool env_was_valid;

	env_was_valid = ha_monitor_all_env_is_valid(ha_mon);

	if (ha_verify_constraint(ha_mon, curr_state, event, next_state))
		return true;

	/*
	 * If we started with an uninitialised environment, chances are the
	 * failure is a false positive. Do not fail the monitor just this time.
	 * Note that we need to run ha_verify_constraint first as it might
	 * initialise the environment.
	 */
	if (!env_was_valid)
		return true;

	ha_get_env_string(&env_string, ha_mon);
	ha_cond_react(curr_state, event, env_string.buffer);
	CONCATENATE(trace_error_env_, MONITOR_NAME)(da_get_id(target),
			   model_get_state_name(curr_state),
			   model_get_event_name(event),
			   env_string.buffer);
	return false;
}

static enum hrtimer_restart ha_monitor_timer_callback(struct hrtimer *timer)
{
	struct ha_monitor *ha_mon = container_of(timer, struct ha_monitor, timer);
	enum states curr_state = READ_ONCE(ha_mon->da_mon.curr_state);
	DECLARE_SEQ_BUF(env_string, MAX_DA_NAME_LEN);
	monitor_target target = ha_get_target(ha_mon);

	ha_get_env_string(&env_string, ha_mon);
	ha_cond_react(curr_state, EVENT_NONE, env_string.buffer);
	CONCATENATE(trace_error_env_, MONITOR_NAME)(da_get_id(target),
		    model_get_state_name(curr_state),
		    EVENT_NONE_LBL,
		    env_string.buffer);

	da_monitor_reset(&ha_mon->da_mon);

	return HRTIMER_NORESTART;
}

#endif /* RV_MON_TYPE */

/*
 * Helper functions for env variables describing clocks with ns granularity
 */
static inline u64 ha_get_clk_ns(struct ha_monitor *ha_mon, enum envs env)
{
	return ktime_get_ns() - READ_ONCE(ha_mon->env_store[env]);
}
static inline void ha_reset_clk_ns(struct ha_monitor *ha_mon, enum envs env)
{
	smp_store_mb(ha_mon->env_store[env], ktime_get_ns());
}

/*
 * Helper functions for env variables describing clocks with jiffy granularity
 */
static inline u64 ha_get_clk_jiffy(struct ha_monitor *ha_mon, enum envs env)
{
	return jiffies - READ_ONCE(ha_mon->env_store[env]);
}
static inline void ha_reset_clk_jiffy(struct ha_monitor *ha_mon, enum envs env)
{
	smp_store_mb(ha_mon->env_store[env], jiffies);
}

/*
 * Helper functions to handle the monitor timer.
 * Not all monitors require a timer, in such case the timer will be set up but
 * never armed.
 * Timers start since the last reset of the supplied env or from now if env is
 * not an environment variable. If env was not initialised no timer starts.
 * Timers can expire on any CPU unless the monitor is per-cpu,
 * where we assume every event occurs on the local CPU.
 */
static inline void ha_start_timer_ns(struct ha_monitor *ha_mon, enum envs env,
				     u64 expire)
{
	int mode = HRTIMER_MODE_REL;
	u64 passed = 0;

	if (env >= 0 && env < ENV_MAX_STORED) {
		if (ha_monitor_env_invalid(ha_mon, env))
			return;
		passed = ha_get_env(ha_mon, env);
	}
	if (RV_MON_TYPE == RV_MON_PER_CPU)
		mode |= HRTIMER_MODE_PINNED;
	hrtimer_start(&ha_mon->timer, ns_to_ktime(expire - passed), mode);
}
static inline void ha_start_timer_jiffy(struct ha_monitor *ha_mon,
					enum envs env, u64 expire)
{
	u64 passed = 0;

	if (env >= 0 && env < ENV_MAX_STORED) {
		if (ha_monitor_env_invalid(ha_mon, env))
			return;
		passed = ha_get_env(ha_mon, env);
	}
	ha_start_timer_ns(ha_mon, ENV_MAX_STORED,
			jiffies_to_nsecs(expire - passed));
}
/*
 * ha_cancel_timer - Cancel the timer and return whether it expired
 *
 * Return true if the timer was cancelled after expiration but before the
 * callback could run.
 */
static inline bool ha_cancel_timer(struct ha_monitor *ha_mon)
{
	ktime_t remaining;

	if (!hrtimer_active(&ha_mon->timer))
		return false;
	remaining = hrtimer_get_remaining(&ha_mon->timer);
	if (hrtimer_try_to_cancel(&ha_mon->timer) == 1 && remaining < 0)
		return true;
	return false;
}

#endif
