# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025, Intel Corporation. All rights reserved.
#
# Makefile - Late Binding client driver for Intel MEI Bus Driver.

subdir-ccflags-y += -I$(srctree)/drivers/misc/mei/

obj-$(CONFIG_INTEL_MEI_LATE_BIND) += mei_late_bind.o
