/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/binder_genl.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_ANDROID_BINDER_GENL_H
#define _UAPI_LINUX_ANDROID_BINDER_GENL_H

#define BINDER_GENL_FAMILY_NAME		"binder_genl"
#define BINDER_GENL_FAMILY_VERSION	1

/*
 * Define what kind of binder transactions should be reported.
 */
enum binder_genl_flag {
	BINDER_GENL_FLAG_FAILED = 1,
	BINDER_GENL_FLAG_DELAYED = 2,
	BINDER_GENL_FLAG_SPAM = 4,
	BINDER_GENL_FLAG_OVERRIDE = 8,
};

enum {
	BINDER_GENL_A_CMD_CONTEXT = 1,
	BINDER_GENL_A_CMD_PID,
	BINDER_GENL_A_CMD_FLAGS,

	__BINDER_GENL_A_CMD_MAX,
	BINDER_GENL_A_CMD_MAX = (__BINDER_GENL_A_CMD_MAX - 1)
};

enum {
	BINDER_GENL_A_REPORT_CONTEXT = 1,
	BINDER_GENL_A_REPORT_ERR,
	BINDER_GENL_A_REPORT_FROM_PID,
	BINDER_GENL_A_REPORT_FROM_TID,
	BINDER_GENL_A_REPORT_TO_PID,
	BINDER_GENL_A_REPORT_TO_TID,
	BINDER_GENL_A_REPORT_REPLY,
	BINDER_GENL_A_REPORT_FLAGS,
	BINDER_GENL_A_REPORT_CODE,
	BINDER_GENL_A_REPORT_DATA_SIZE,

	__BINDER_GENL_A_REPORT_MAX,
	BINDER_GENL_A_REPORT_MAX = (__BINDER_GENL_A_REPORT_MAX - 1)
};

enum {
	BINDER_GENL_CMD_SET = 1,
	BINDER_GENL_CMD_REPORT,

	__BINDER_GENL_CMD_MAX,
	BINDER_GENL_CMD_MAX = (__BINDER_GENL_CMD_MAX - 1)
};

#endif /* _UAPI_LINUX_ANDROID_BINDER_GENL_H */
