# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
# Copyright(c) 2026 Realtek Semiconductor Corp. All rights reserved.

#
# Makefile for the Realtek R816E power management driver
#

obj-$(CONFIG_R816E) += r816e.o
