# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_RUST_MINIMAL)		+= rust_minimal.o
obj-$(CONFIG_SAMPLE_RUST_PRINT)			+= rust_print.o
obj-$(CONFIG_SAMPLE_RUST_USB_SIMPLE)		+= rust_usb_simple.o

rust-libs					:= ../../drivers/usb/core/usb

subdir-$(CONFIG_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
