/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef SELFTEST_KVM_UTIL_ARCH_H
#define SELFTEST_KVM_UTIL_ARCH_H

#include "kvm_util_types.h"

struct kvm_vm_arch {};

enum kvm_s390_stats {
	VM_STAT(inject_io),
	VM_STAT(inject_float_mchk),
	VM_STAT(inject_pfault_done),
	VM_STAT(inject_service_signal),
	VM_STAT(inject_virtio),
	VM_STAT(aen_forward),
	VM_STAT(gmap_shadow_reuse),
	VM_STAT(gmap_shadow_create),
	VM_STAT(gmap_shadow_r1_entry),
	VM_STAT(gmap_shadow_r2_entry),
	VM_STAT(gmap_shadow_r3_entry),
	VM_STAT(gmap_shadow_sg_entry),
	VM_STAT(gmap_shadow_pg_entry),

	VCPU_STAT(exit_userspace),
	VCPU_STAT(exit_null),
	VCPU_STAT(exit_external_request),
	VCPU_STAT(exit_io_request),
	VCPU_STAT(exit_external_interrupt),
	VCPU_STAT(exit_stop_request),
	VCPU_STAT(exit_validity),
	VCPU_STAT(exit_instruction),
	VCPU_STAT(exit_pei),
	VCPU_STAT(halt_no_poll_steal),
	VCPU_STAT(instruction_lctl),
	VCPU_STAT(instruction_lctlg),
	VCPU_STAT(instruction_stctl),
	VCPU_STAT(instruction_stctg),
	VCPU_STAT(exit_program_interruption),
	VCPU_STAT(exit_instr_and_program),
	VCPU_STAT(exit_operation_exception),
	VCPU_STAT(deliver_ckc),
	VCPU_STAT(deliver_cputm),
	VCPU_STAT(deliver_external_call),
	VCPU_STAT(deliver_emergency_signal),
	VCPU_STAT(deliver_service_signal),
	VCPU_STAT(deliver_virtio),
	VCPU_STAT(deliver_stop_signal),
	VCPU_STAT(deliver_prefix_signal),
	VCPU_STAT(deliver_restart_signal),
	VCPU_STAT(deliver_program),
	VCPU_STAT(deliver_io),
	VCPU_STAT(deliver_machine_check),
	VCPU_STAT(exit_wait_state),
	VCPU_STAT(inject_ckc),
	VCPU_STAT(inject_cputm),
	VCPU_STAT(inject_external_call),
	VCPU_STAT(inject_emergency_signal),
	VCPU_STAT(inject_mchk),
	VCPU_STAT(inject_pfault_init),
	VCPU_STAT(inject_program),
	VCPU_STAT(inject_restart),
	VCPU_STAT(inject_set_prefix),
	VCPU_STAT(inject_stop_signal),
	VCPU_STAT(instruction_epsw),
	VCPU_STAT(instruction_gs),
	VCPU_STAT(instruction_io_other),
	VCPU_STAT(instruction_lpsw),
	VCPU_STAT(instruction_lpswe),
	VCPU_STAT(instruction_lpswey),
	VCPU_STAT(instruction_pfmf),
	VCPU_STAT(instruction_ptff),
	VCPU_STAT(instruction_sck),
	VCPU_STAT(instruction_sckpf),
	VCPU_STAT(instruction_stidp),
	VCPU_STAT(instruction_spx),
	VCPU_STAT(instruction_stpx),
	VCPU_STAT(instruction_stap),
	VCPU_STAT(instruction_iske),
	VCPU_STAT(instruction_ri),
	VCPU_STAT(instruction_rrbe),
	VCPU_STAT(instruction_sske),
	VCPU_STAT(instruction_ipte_interlock),
	VCPU_STAT(instruction_stsi),
	VCPU_STAT(instruction_stfl),
	VCPU_STAT(instruction_tb),
	VCPU_STAT(instruction_tpi),
	VCPU_STAT(instruction_tprot),
	VCPU_STAT(instruction_tsch),
	VCPU_STAT(instruction_sie),
	VCPU_STAT(instruction_essa),
	VCPU_STAT(instruction_sthyi),
	VCPU_STAT(instruction_sigp_sense),
	VCPU_STAT(instruction_sigp_sense_running),
	VCPU_STAT(instruction_sigp_external_call),
	VCPU_STAT(instruction_sigp_emergency),
	VCPU_STAT(instruction_sigp_cond_emergency),
	VCPU_STAT(instruction_sigp_start),
	VCPU_STAT(instruction_sigp_stop),
	VCPU_STAT(instruction_sigp_stop_store_status),
	VCPU_STAT(instruction_sigp_store_status),
	VCPU_STAT(instruction_sigp_store_adtl_status),
	VCPU_STAT(instruction_sigp_arch),
	VCPU_STAT(instruction_sigp_prefix),
	VCPU_STAT(instruction_sigp_restart),
	VCPU_STAT(instruction_sigp_init_cpu_reset),
	VCPU_STAT(instruction_sigp_cpu_reset),
	VCPU_STAT(instruction_sigp_unknown),
	VCPU_STAT(instruction_diagnose_10),
	VCPU_STAT(instruction_diagnose_44),
	VCPU_STAT(instruction_diagnose_9c),
	VCPU_STAT(diag_9c_ignored),
	VCPU_STAT(diag_9c_forward),
	VCPU_STAT(instruction_diagnose_258),
	VCPU_STAT(instruction_diagnose_308),
	VCPU_STAT(instruction_diagnose_500),
	VCPU_STAT(instruction_diagnose_other),
	VCPU_STAT(pfault_sync),
};

#endif  // SELFTEST_KVM_UTIL_ARCH_H
