/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 AIROHA Inc
 * Author: Christian Marangi <ansuelsmth@gmail.com>
 */

#ifndef _PHY_AN7583_PCIE_H
#define _PHY_AN7583_PCIE_H

/* G3 ANA */
#define REG_PXP_CMN_EN				0x0
#define   G3_ANA_PXP_CMN_TRIM			GENMASK(28, 24)
#define   G3_ANA_PXP_CMN_EN			BIT(0)

#define REG_PXP_JCPLL_IB_EXT_EN			0x4
#define   G3_ANA_PXP_JCPLL_CHP_IOFST		GENMASK(29, 24)
#define   G3_ANA_PXP_JCPLL_CHP_IBIAS		GENMASK(21, 16)
#define   G3_ANA_PXP_JCPLL_LPF_SHCK_EN		BIT(8)

#define REG_PXP_JCPLL_LPF_BR			0x8
#define   G3_ANA_PXP_JCPLL_LPF_BWR		GENMASK(28, 24)
#define   G3_ANA_PXP_JCPLL_LPF_BP		GENMASK(20, 16)
#define   G3_ANA_PXP_JCPLL_LPF_BC		GENMASK(12, 8)
#define   G3_ANA_PXP_JCPLL_LPF_BR		GENMASK(4, 0)

#define REG_PXP_JCPLL_LPF_BWC			0xc
#define   G3_ANA_PXP_JCPLL_KBAND_DIV		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_KBAND_CODE		GENMASK(23, 16)
#define   G3_ANA_PXP_JCPLL_LPF_BWC		GENMASK(4, 0)

#define REG_PXP_JCPLL_KBAND_KFC			0x10
#define   G3_ANA_PXP_JCPLL_POSTDIV_EN		BIT(24)
#define   G3_ANA_PXP_JCPLL_KBAND_KS		GENMASK(17, 16)
#define   G3_ANA_PXP_JCPLL_KBAND_KF		GENMASK(9, 8)
#define   G3_ANA_PXP_JCPLL_KBAND_KFC		GENMASK(1, 0)

#define REG_PXP_JCPLL_MMD_PREDIV_MODE		0x14
#define   G3_ANA_PXP_JCPLL_POSTDIV_D5		BIT(24)
#define   G3_ANA_PXP_JCPLL_POSTDIV_D2		BIT(16)
#define   G3_ANA_PXP_JCPLL_MMD_PREDIV_MODE	GENMASK(1, 0)

#define REG_PXP_JCPLL_MONCK_EN			0x18
#define   G3_ANA_PXP_JCPLL_REFIN_DIV		GENMASK(25, 24)

#define REG_PXP_JCPLL_RST_DLY			0x1c
#define   G3_ANA_PXP_JCPLL_SDM_DI_LS		GENMASK(25, 24)
#define   G3_ANA_PXP_JCPLL_SDM_DI_EN		BIT(16)
#define   G3_ANA_PXP_JCPLL_PLL_RSTB		BIT(8)
#define   G3_ANA_PXP_JCPLL_RST_DLY		GENMASK(2, 0)

#define REG_PXP_JCPLL_SDM_IFM			0x20
#define   G3_ANA_PXP_JCPLL_SDM_IFM		BIT(0)

#define REG_PXP_JCPLL_SDM_HREN			0x24
#define   G3_ANA_PXP_JCPLL_TCL_AMP_VREF		GENMASK(28, 24)
#define   G3_ANA_PXP_JCPLL_TCL_AMP_GAIN		GENMASK(18, 16)
#define   G3_ANA_PXP_JCPLL_TCL_AMP_EN		BIT(8)
#define   G3_ANA_PXP_JCPLL_SDM_HREN		BIT(0)

#define REG_PXP_JCPLL_TCL_CMP_EN		0x28
#define   G3_ANA_PXP_JCPLL_TCL_LPF_BW		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_TCL_LPF_EN		BIT(16)

#define REG_PXP_JCPLL_VCODIV			0x2c
#define   G3_ANA_PXP_JCPLL_VCO_SCAPWR		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_VCO_HALFLSB_EN	BIT(16)
#define   G3_ANA_PXP_JCPLL_VCO_CFIX		GENMASK(9, 8)

#define REG_PXP_JCPLL_VCO_TCLVAR		0x30
#define   G3_ANA_PXP_JCPLL_SSC_PHASE_INI	BIT(17)
#define   G3_ANA_PXP_JCPLL_SSC_EN		BIT(16)
#define   G3_ANA_PXP_JCPLL_VCO_TCLVAR		GENMASK(2, 0)

#define REG_PXP_JCPLL_SSC_TRI_EN		0x34
#define   G3_ANA_PXP_JCPLL_SSC_DELTA1		GENMASK(23, 8)
#define   G3_ANA_PXP_JCPLL_SSC_TRI_EN		BIT(0)

#define REG_PXP_JCPLL_SSC_DELTA			0x38
#define   G3_ANA_PXP_JCPLL_SSC_PERIOD		GENMASK(31, 16)
#define   G3_ANA_PXP_JCPLL_SSC_DELTA		GENMASK(15, 0)

#define REG_PXP_JCPLL_SPARE_H			0x48
#define   G3_ANA_PXP_JCPLL_TCL_KBAND_VREF	GENMASK(20, 16)
#define   G3_ANA_PXP_JCPLL_SPARE_L		GENMASK(15, 8)

#define REG_PXP_JCPLL_FREQ_MEAS_EN		0x4c
#define   G3_ANA_PXP_TXPLL_LPF_SHCK_EN		BIT(25)
#define   G3_ANA_PXP_JCPLL_VCO_KBAND_MEAS_EN	BIT(8)

#define REG_PXP_TXPLL_CHP_IBIAS			0x50
#define   G3_ANA_PXP_TXPLL_LPF_BC		GENMASK(28, 24)
#define   G3_ANA_PXP_TXPLL_LPF_BR		GENMASK(20, 16)
#define   G3_ANA_PXP_TXPLL_CHP_IOFST		GENMASK(13, 8)
#define   G3_ANA_PXP_TXPLL_CHP_IBIAS		GENMASK(5, 0)

#define REG_PXP_TXPLL_LPF_BP			0x54
#define   G3_ANA_PXP_TXPLL_LPF_BWC		GENMASK(20, 16)
#define   G3_ANA_PXP_TXPLL_LPF_BWR		GENMASK(12, 8)
#define   G3_ANA_PXP_TXPLL_LPF_BP		GENMASK(4, 0)

#define REG_PXP_TXPLL_KBAND_CODE		0x58
#define   G3_ANA_PXP_TXPLL_KBAND_KF		GENMASK(25, 24)
#define   G3_ANA_PXP_TXPLL_KBAND_KFC		GENMASK(17, 16)
#define   G3_ANA_PXP_TXPLL_KBAND_DIV		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_KBAND_CODE		GENMASK(7, 0)

#define REG_PXP_TXPLL_KBAND_KS			0x5c
#define   G3_ANA_PXP_TXPLL_MMD_PREDIV_MODE	GENMASK(17, 16)
#define   G3_ANA_PXP_TXPLL_POSTDIV_EN		BIT(8)
#define   G3_ANA_PXP_TXPLL_KBAND_KS		GENMASK(1, 0)

#define REG_PXP_TXPLL_PHY_CK1_EN		0x60
#define   G3_ANA_PXP_TXPLL_PHY_CK1_EN		BIT(0)

#define REG_PXP_TXPLL_REFIN_INTERNAL		0x64
#define   G3_ANA_PXP_TXPLL_PLL_RSTB		BIT(24)
#define   G3_ANA_PXP_TXPLL_RST_DLY		GENMASK(18, 16)
#define   G3_ANA_PXP_TXPLL_REFIN_DIV		GENMASK(9, 8)
#define   G3_ANA_PXP_TXPLL_REFIN_INTERNAL	BIT(0)

#define REG_PXP_TXPLL_SDM_DI_EN			0x68
#define   G3_ANA_PXP_TXPLL_SDM_IFM		BIT(16)
#define   G3_ANA_PXP_TXPLL_SDM_DI_LS		GENMASK(9, 8)

#define REG_PXP_TXPLL_SDM_ORD			0x6c
#define   G3_ANA_PXP_TXPLL_TCL_AMP_EN		BIT(24)
#define   G3_ANA_PXP_TXPLL_SDM_ORD		GENMASK(1, 0)

#define REG_PXP_TXPLL_TCL_AMP_GAIN		0x70
#define   G3_ANA_PXP_TXPLL_TCL_AMP_VREF		GENMASK(12, 8)
#define   G3_ANA_PXP_TXPLL_TCL_AMP_GAIN		GENMASK(2, 0)

#define REG_PXP_TXPLL_TCL_LPF_EN		0x74
#define   G3_ANA_PXP_TXPLL_VCO_CFIX		GENMASK(25, 24)
#define   G3_ANA_PXP_TXPLL_TCL_LPF_BW		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_TCL_LPF_EN		BIT(0)

#define REG_PXP_TXPLL_VCO_HALFLSB_EN		0x78
#define   G3_ANA_PXP_TXPLL_VCO_SCAPWR		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_VCO_HALFLSB_EN	BIT(0)

#define REG_PXP_TXPLL_SSC_EN			0x7c
#define   G3_ANA_PXP_TXPLL_SSC_PHASE_INI	BIT(8)
#define   G3_ANA_PXP_TXPLL_SSC_EN		BIT(0)

#define REG_PXP_TXPLL_SSC_DELTA1		0x80
#define   G3_ANA_PXP_TXPLL_SSC_DELTA		GENMASK(31, 16)
#define   G3_ANA_PXP_TXPLL_SSC_DELTA1		GENMASK(15, 0)

#define REG_PXP_TXPLL_SSC_PERIOD		0x84
#define   G3_ANA_PXP_TXPLL_SSC_PERIOD		GENMASK(15, 0)

#define REG_PXP_TXPLL_VTP_EN			0x88
#define   G3_ANA_PXP_TXPLL_VTP_EN		BIT(0)

#define REG_PXP_TXPLL_TCL_VTP_EN		0x90
#define   G3_ANA_PXP_TXPLL_SPARE_L		GENMASK(31, 24)

#define REG_PXP_TXPLL_TCL_KBAND_VREF		0x94
#define   G3_ANA_PXP_TXPLL_VCO_KBAND_MEAS_EN	BIT(24)
#define   G3_ANA_PXP_TXPLL_TCL_KBAND_VREF	GENMASK(4, 0)

#define REG_PCIE_CLKTX0_AMP			0x98
#define   G3_ANA_PXP_PCIE_CLKTX0_IMP_SEL	GENMASK(31, 27)
#define   G3_ANA_PXP_PCIE_CLKTX0_HZ		BIT(26)
#define   G3_ANA_PCIE_CLKTX0_SR			GENMASK(17, 16)
#define   G3_ANA_PCIE_CLKTX0_OFFSET		GENMASK(9, 8)
#define   G3_ANA_PCIE_CLKTX0_AMP		GENMASK(2, 0)

#define REG_PXP_PLL_MONCLK_SEL			0xa0
#define   G3_ANA_PXP_PLL_CMN_RESERVE0		GENMASK(15, 8)

#define REG_PXP_TX_CKLDO_EN			0xc4
#define   G3_ANA_PXP_TX_DMEDGEGEN_EN		BIT(24)
#define   G3_ANA_PXP_TX_CKLDO_EN		BIT(0)

#define REG_PXP_RX_REV_0			0xd4
#define   G3_ANA_PXP_RX_REV_1_10_8		GENMASK(26, 24)
#define   G3_ANA_PXP_RX_REV_1_6_4		GENMASK(22, 20)
#define   G3_ANA_PXP_RX_REV_1_3_2		GENMASK(19, 18)

#define REG_PXP_RX_PHYCK_DIV			0xd8
#define   G3_ANA_PXP_RX_TDC_CK_SEL		BIT(24)
#define   G3_ANA_PXP_RX_PHYCK_RSTB		BIT(16)
#define   G3_ANA_PXP_RX_PHYCK_SEL		GENMASK(9, 8)

#define REG_PXP_CDR_PD_PICAL_CKD8_INV		0xdc
#define   G3_ANA_PXP_CDR_PD_EDGE_DIS		BIT(8)

#define REG_PXP_CDR_LPF_RATIO			0xe8
#define   G3_ANA_PXP_CDR_LPF_TOP_LIM		GENMASK(26, 8)

#define REG_PXP_CDR_PR_BETA_DAC			0xf8
#define   G3_ANA_PXP_CDR_PR_KBAND_DIV		GENMASK(26, 24)
#define   G3_ANA_PXP_CDR_PR_BETA_SEL		GENMASK(19, 16)

#define REG_PXP_CDR_PR_VREG_IBAND_VAL		0xfc
#define   G3_ANA_PXP_CDR_PR_VREG_CKBUF_VAL_2_0	GENMASK(10, 8)
#define   G3_ANA_PXP_CDR_PR_VREG_IBAND_VAL_2_0	GENMASK(2, 0)

#define REG_PXP_CDR_PR_CKREF_DIV		0x100
#define   G3_ANA_PXP_CDR_PR_CKREF_DIV_1_0	GENMASK(1, 0)

#define REG_PXP_CDR_PR_TDC_REF_SEL		0x108
#define   G3_ANA_PXP_CDR_PR_CKREF_DIV1_1_0	GENMASK(25, 24)
#define   G3_ANA_PXP_CDR_PR_LDO_FORCE_ON	BIT(16)

#define REG_PXP_CDR_PR_MONPR_EN			0x10c
#define   G3_ANA_PXP_CDR_PR_XFICK_EN		BIT(2)

#define REG_PXP_RX_DAC_RANGE			0x110
#define   G3_ANA_PXP_RX_SIGDET_LPF_CTRL		GENMASK(25, 24)

#define REG_PXP_CDR_PR_MONCK_EN			0x104
#define   G3_ANA_PXP_CDR_PR_MONCK_EN		BIT(0)
#define   G3_ANA_PXP_CDR_PR_RESERVE0		GENMASK(19, 16)

#define REG_PXP_RX_SIGDET_NOVTH			0x114
#define   G3_ANA_PXP_RX_FE_50OHMS_SEL		GENMASK(25, 24)
#define   G3_ANA_PXP_RX_SIGDET_VTH_SEL_4_0	GENMASK(20, 16)
#define   G3_ANA_PXP_RX_SIGDET_PEAK_1_0		GENMASK(9, 8)

#define REG_PXP_RX_FE_EQ_HZEN			0x118
#define   G3_ANA_PXP_RX_FE_VB_EQ3_EN		BIT(24)
#define   G3_ANA_PXP_RX_FE_VB_EQ2_EN		BIT(16)
#define   G3_ANA_PXP_RX_FE_VB_EQ1_EN		BIT(8)

#define REG_PXP_RX_FE_VCM_GEN_PWDB		0x11c
#define   G3_ANA_PXP_RX_FE_VCM_GEN_PWDB		BIT(0)

#define REG_PXP_RX_OSCAL_CTLE2IOS		0x128
#define   G3_ANA_PXP_RX_OSCAL_VGA1VOS		GENMASK(29, 24)
#define   G3_ANA_PXP_RX_OSCAL_VGA1IOS		GENMASK(21, 16)

#define REG_PXP_RX_OSCAL_VGA2IOS		0x12c
#define   G3_ANA_PXP_RX_OSCAL_VGA2IOS		GENMASK(5, 0)

/* G3 PMA */
#define REG_RX_CTRL_SEQUENCE_DISB_CTRL_1	0x10c
#define   G3_PMA_DISB_RX_SDCAL_EN		BIT(0)

#define REG_RX_CTRL_SEQUENCE_FORCE_CTRL_1	0x114
#define   G3_PMA_FORCE_RX_SDCAL_EN		BIT(0)

#define REG_SS_RX_CAL_2				0x164
#define   G3_PMA_CAL_OUT_OS			GENMASK(11, 8)

#define REG_SS_RX_SIGDET_0			0x168
#define   G3_PMA_SIGDET_WIN_NONVLD_TIMES	GENMASK(28, 24)

#define REG_SS_TX_RST_B				0x260
#define   G3_PMA_TXCALIB_RST_B			BIT(8)
#define   G3_PMA_TX_TOP_RST_B			BIT(0)

#define REG_RX_FORCE_MODE_0			0x294
#define   G3_PMA_FORCE_DA_XPON_RX_FE_GAIN_CTRL	GENMASK(1, 0)

#define REG_SS_DA_XPON_PWDB_0			0x34c
#define   G3_PMA_DA_XPON_CDR_PR_PWDB		BIT(8)

#define REG_SW_RST_SET				0x460
#define   G3_PMA_SW_XFI_RXPCS_RST_N		BIT(8)
#define   G3_PMA_SW_TX_FIFO_RST_N		BIT(6)
#define   G3_PMA_SW_REF_RST_N			BIT(5)
#define   G3_PMA_SW_ALLPCS_RST_N		BIT(4)
#define   G3_PMA_SW_PMA_RST_N			BIT(3)
#define   G3_PMA_SW_TX_RST_N			BIT(2)
#define   G3_PMA_SW_RX_RST_N			BIT(1)
#define   G3_PMA_SW_RX_FIFO_RST_N		BIT(0)

#define REG_FORCE_DA_PXP_TX_TERM_SEL		0x77c
#define   G3_PMA_FORCE_SEL_DA_PXP_TX_TERM_SEL	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_TX_TERM_SEL	GENMASK(2, 0)

#define REG_FORCE_DA_PXP_CDR_PR_FLL_COR		0x790
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_DAC_EYE	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_RX_DAC_EYE	GENMASK(22, 16)

#define REG_FORCE_DA_PXP_CDR_PR_IDAC		0x794
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_SDM_PCW	BIT(24)

#define REG_FORCE_DA_PXP_TXPLL_SDM_PCW		0x798
#define   G3_PMA_FORCE_DA_PXP_TXPLL_SDM_PCW	GENMASK(30, 0)

#define REG_FORCE_DA_PXP_RX_FE_VOS		0x79c
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_SDM_PCW	BIT(16)

#define REG_FORCE_DA_PXP_JCPLL_SDM_PCW		0x800
#define   G3_PMA_FORCE_DA_PXP_JCPLL_SDM_PCW	GENMASK(30, 0)

#define REG_FORCE_DA_PXP_CDR_PD_PWDB		0x81c
#define   G3_PMA_FORCE_SEL_DA_PXP_CDR_PD_PWDB	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_CDR_PD_PWDB	BIT(0)

#define REG_FORCE_DA_PXP_CDR_PR_PIEYE_PWDB	0x824
#define   G3_PMA_FORCE_SEL_DA_PXP_CDR_PR_PIEYE_PWDB BIT(8)
#define   G3_PMA_FORCE_DA_PXP_CDR_PR_PIEYE_PWDB	BIT(0)

#define REG_FORCE_DA_PXP_JCPLL_CKOUT_EN		0x828
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_EN	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_EN		BIT(16)
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_CKOUT_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_CKOUT_EN	BIT(0)

#define REG_FORCE_DA_PXP_RX_SCAN_RST_B		0x84c
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_SIGDET_PWDB BIT(24)
#define   G3_PMA_FORCE_DA_PXP_RX_SIGDET_PWDB	BIT(16)

#define REG_FORCE_DA_PXP_TXPLL_CKOUT_EN		0x854
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_EN	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_TXPLL_EN		BIT(16)
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_CKOUT_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_TXPLL_CKOUT_EN	BIT(0)

#define REG_SCAN_MODE				0x884
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_KBAND_LOAD_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_KBAND_LOAD_EN BIT(0)

#define REG_FORCE_DA_PXP_RX_FE_GAIN_CTRL	0x88c
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_FE_GAIN_CTRL BIT(8)
#define   G3_PMA_FORCE_DA_PXP_RX_FE_GAIN_CTRL	GENMASK(1, 0)

#define REG_FORCE_DA_PXP_RX_FE_PWDB		0x894
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_FE_PWDB	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_RX_FE_PWDB	BIT(0)

#define REG_ADD_DIG_RESERVE_12			0x8b8
#define   G3_PMA_DIG_RESERVE_12_8_8		BIT(8)

#define REG_ADD_DIG_RESERVE_27			0x908
#define   G3_PMA_DIG_RESERVE_27_16_16		BIT(16)

#define REG_ADD_DIG_RESERVE_30			0x914
#define   G3_PMA_DIG_RESERVE_30			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_31			0x918
#define   G3_PMA_DIG_RESERVE_31_20_16		GENMASK(20, 16)
#define   G3_PMA_DIG_RESERVE_31_12_8		GENMASK(12, 8)
#define   G3_PMA_DIG_RESERVE_31_4_0		GENMASK(4, 0)

#define REG_ADD_DIG_RESERVE_32			0x91c
#define   G3_PMA_DIG_RESERVE_32_31_16		GENMASK(31, 16)

#define REG_ADD_DIG_RESERVE_33			0x920
#define   G3_PMA_DIG_RESERVE_33_31_16		GENMASK(31, 16)
#define   G3_PMA_DIG_RESERVE_33_15_0		GENMASK(15, 0)

#define REG_ADD_DIG_RESERVE_34			0x924
#define   G3_PMA_DIG_RESERVE_34			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_35			0x928
#define   G3_PMA_DIG_RESERVE_35			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_40			0x93c
#define   G3_PMA_DIG_RESERVE_40			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_43			0x948
#define   G3_PMA_DIG_RESERVE_43_18_16		GENMASK(18, 16)
#define   G3_PMA_DIG_RESERVE_43_14_12		GENMASK(14, 12)
#define   G3_PMA_DIG_RESERVE_43_10_8		GENMASK(10, 8)

/* DTIME */
#define REG_PCIE_PEXTP_DIG_GLB44		0x0
#define PCIE_XTP_RXDET_LATCH_STB_T_SEL		GENMASK(31, 29)
#define PCIE_XTP_TXPD_RXDET_DONE_CDT		BIT(28)
#define PCIE_XTP_TXPD_TX_DATA_EN_DLY		GENMASK(27, 24)
#define PCIE_XTP_RXDET_FINISH_STB_T_SEL		GENMASK(23, 16)
#define PCIE_XTP_RXDET_EN_STB_T_SEL		GENMASK(15, 8)
#define PCIE_XTP_RXDET_VCM_OFF_STB_T_SEL	GENMASK(7, 0)

/* RX AEQ */
#define REG_PCIE_PEXTP_DIG_LN_RX30		0x0
#define PCIE_XTP_LN_RX_PDOWN_E0_AEQEN_WAIT	GENMASK(31, 16)
#define PCIE_XTP_LN_RX_PDOWN_T2RLB_DIG_EN	BIT(8)
#define PCIE_XTP_LN_RX_PDOWN_L1P2_EXIT_WAIT	GENMASK(7, 0)

#endif /* _PHY_AN7583_PCIE_H */
