/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 AIROHA Inc
 * Author: Christian Marangi <ansuelsmth@gmail.com>
 */

#ifndef _PHY_AIROHA_PCIE_H
#define _PHY_AIROHA_PCIE_H

/* QPhy ANA */
#define REG_QP_RXAFE_RESERVE			0x4
#define   QP_ANA_QP_CDR_PD_10B_EN		BIT(11)
#define   QP_ANA_QP_CDR_PD_EDGE_DIS		BIT(10)

#define REG_QP_CDR_LPF_MJV_LIM		        0xc
#define   QP_ANA_QP_CDR_LPF_RATIO		GENMASK(5, 4)

#define REG_QP_CDR_PR_CKREF_DIV1		0x18
#define   QP_ANA_QP_CDR_PR_KBAND_DIV		GENMASK(26, 24)
#define   QP_ANA_QP_CDR_PR_DAC_BAND		GENMASK(12, 8)

#define REG_QP_CDR_PR_KBAND_DIV_PCIE		0x1c
#define   QP_ANA_QP_CDR_PR_XFICK_EN		BIT(30)
#define   QP_ANA_QP_CDR_PR_KBAND_PCIE_MODE	BIT(6)
#define   QP_ANA_QP_CDR_PR_KBAND_DIV_PCIE	GENMASK(5, 0)

#define REG_QP_CDR_FORCE_IBANDLPF_R_OFF		0x20
#define   QP_ANA_QP_CDR_PHYCK_RSTB		BIT(13)

#define REG_QP_TX_MODE_16B_EN			0x28
#define   QP_ANA_QP_TX_RESERVE_8		BIT(24)

#define REG_QP_RXLBTX_EN			0x2c
#define   QP_ANA_QP_TX_DMEDGEGEN_EN		BIT(27)
#define   QP_ANA_QP_TX_RXDET_METHOD		BIT(25)

#define REG_QP_BGR_EN				0x30
#define   QP_ANA_QP_BIAS_V2V_CAL		GENMASK(26, 21)
#define   QP_ANA_QP_BG_DIV			GENMASK(3, 2)

#define REG_PCIE_CLKDRV_IMPSEL			0x34
#define   QP_ANA_PCIE_CLKDRV_AMP		GENMASK(27, 25)
#define   QP_ANA_PCIE_CLKDRV_FORCEIN		GENMASK(24, 23)
#define   QP_ANA_PCIE_CLKDRV_HZ			BIT(14)
#define   QP_ANA_PCIE_CLKDRV_RP			GENMASK(13, 9)
#define   QP_ANA_PCIE_CLKDRV_IMPSEL		GENMASK(4, 0)

#define REG_QP_TDC_FT_CK_EN			0x38
#define   QP_ANA_QP_PLL_DEBUG_SEL		BIT(19)

#define REG_QP_PLL_IPLL_DIG_PWR_SEL		0x3c
#define   QP_ANA_QP_PLL_PREDIV			GENMASK(26, 25)
#define   QP_ANA_QP_PLL_MON_LDO_SEL		GENMASK(18, 16)
#define   QP_ANA_QP_PLL_OSCAL_ENB		BIT(19)
#define   QP_ANA_QP_PLL_MONVC_EN		BIT(14)
#define   QP_ANA_QP_PLL_LDOLPF_VSEL		GENMASK(6, 5)

#define REG_QP_PLL_SDM_ORD			0x40
#define   QP_ANA_QP_PLL_SSC_PHASE_INI		BIT(3)
#define   QP_ANA_QP_PLL_SSC_TRI_EN		BIT(4)

/* QPhy PMA */
#define REG_QP_TX_DA_CTRL_0			0x0
#define   QP_PMA_RXDET_RD_WAIT_TIMER		GENMASK(15, 12)
#define   QP_PMA_RXDET_EN_WINDOW		GENMASK(9, 4)

#define REG_QP_TX_DA_CTRL_3			0xc
#define   QP_PMA_TX_DATA_RATE_SEL		GENMASK(30, 28)

#define REG_PON_RXFEDIG_CTRL_0			0x100
#define   QP_PMA_QP_EQ_RX500M_CK_SEL		BIT(12)

#define REG_SS_LCPLL_PWCTL_SETTING_2		0x208
#define   QP_PMA_NCPO_ANA_MSB			GENMASK(17, 16)

#define REG_SS_LCPLL_TDC_FLT_2			0x230
#define   QP_PMA_LCPLL_NCPO_VALUE		GENMASK(30, 0)

#define REG_SS_LCPLL_TDC_PCW_1			0x248
#define   QP_PMA_LCPLL_PON_HRDDS_PCW_NCPO_GPON	GENMASK(30, 0)

#define REG_INTF_CTRL_6				0x318
#define   QP_PMA_DA_QP_TX_DATA_EN_SEL		BIT(13)
#define   QP_PMA_DA_QP_TX_DATA_EN_FORCE		BIT(12)

#define REG_INTF_CTRL_7				0x31c
#define   QP_PMA_DA_QP_PLL_EN_SEL		BIT(5)
#define   QP_PMA_DA_QP_PLL_EN_FORCE		BIT(4)

#define REG_INTF_CTRL_8				0x320
#define   QP_PMA_DA_QP_XTAL_EXT_EN_SEL		BIT(13)
#define   QP_PMA_DA_QP_XTAL_EXT_EN_FORCE	GENMASK(12, 11)

#define REG_INTF_STS_9				0x364
#define   QP_PMA_ADDR_INTF_STS_PLL_VCOCAL	GENMASK(23, 16)

#define REG_PLL_CTRL_0				0x400
#define   QP_PMA_PHYA_AUTO_INIT			BIT(0)

#define REG_PLL_CTRL_1				0x404
#define   QP_PMA_QP_PLL_SSC_EN			BIT(30)

#define REG_PLL_CTRL_2				0x408
#define   QP_PMA_DA_QP_PLL_SDM_IFM_INTF		BIT(30)
#define   QP_PMA_DA_QP_PLL_RICO_SEL_INTF	BIT(29)
#define   QP_PMA_DA_QP_PLL_PHY_CK_EN_INTF	BIT(27)
#define   QP_PMA_DA_QP_PLL_PCK_SEL_INTF		BIT(22)
#define   QP_PMA_DA_QP_PLL_KBAND_PREDIV_INTF	GENMASK(21, 20)
#define   QP_PMA_DA_QP_PLL_IR_INTF		GENMASK(19, 16)
#define   QP_PMA_DA_QP_PLL_ICOIQ_EN_INTF	BIT(14)
#define   QP_PMA_DA_QP_PLL_FBKSEL_INTF		GENMASK(13, 12)
#define   QP_PMA_DA_QP_PLL_BPB_INTF		GENMASK(7, 6)
#define   QP_PMA_DA_QP_PLL_BPA_INTF		GENMASK(4, 2)
#define   QP_PMA_DA_QP_PLL_BC_INTF		GENMASK(1, 0)

#define REG_PLL_CTRL_3				0x40c
#define   QP_PMA_DA_QP_PLL_SSC_PERIOD_INTF	GENMASK(31, 16)
#define   QP_PMA_DA_QP_PLL_SSC_DELTA_INTF	GENMASK(15, 0)

#define REG_PLL_CTRL_4				0x410
#define   QP_PMA_DA_QP_PLL_SDM_HREN_INTF	GENMASK(4, 3)
#define   QP_PMA_DA_QP_PLL_ICOLP_EN_INTF	BIT(2)

#define REG_PLL_CK_CTRL_0			0x414
#define   QP_PMA_DA_PCIE_CLKTX_EN_INTF		BIT(5)
#define   QP_PMA_DA_PCIE_CLKRX_EN_INTF		BIT(4)

#define REG_PLL_CK_CTRL_1			0x418
#define   QP_PMA_PLL_FORCE_UNSTABLE		BIT(19)
#define   QP_PMA_PLL_FORCE_STABLE		BIT(18)

#define REG_PLL_CK_CTRL_2			0x41c
#define   QP_PMA_PCIE_MODE_PLL_AUTO_OFF_EN	BIT(2)
#define   QP_PMA_PCIE_MODE_PLL_AUTO_ON_EN	BIT(1)
#define   QP_PMA_PCIE_MODE_PLL_AUTO_EN		BIT(0)

#define REG_RX_DLY_0				0x614
#define   QP_PMA_QP_RX_PI_CAL_EN_H_DLY		GENMASK(7, 0)

#define REG_RX_CTRL_2				0x630
#define   QP_PMA_QP_RX_EQ_EN_H_DLY		GENMASK(28, 16)

#define REG_RX_CTRL_5				0x63c
#define   QP_PMA_FREDET_CHK_CYCLE		GENMASK(29, 10)

#define REG_RX_CTRL_6				0x640
#define   QP_PMA_FREDET_GOLDEN_CYCLE		GENMASK(19, 0)

#define REG_RX_CTRL_7				0x644
#define   QP_PMA_FREDET_TOLERATE_CYCLE		GENMASK(19, 0)

#define REG_RX_CTRL_10				0x650
#define   QP_PMA_QP_CRSDET_RSTB			BIT(1)

#define REG_RX_CTRL_11				0x654
#define   QP_PMA_QP_FORCE_SIGDET_5G		BIT(19)

#define REG_RX_CTRL_36				0x6b8
#define   QP_PMA_QP_PCIE_USB_SYSTEM		BIT(26)
#define   QP_PMA_QP_LCK2DATA_DLY_TIME_9_0	GENMASK(25, 16)

#define REG_RX_CTRL_45				0x6dc
#define   QP_PMA_QP_EQ_EN_DLY			GENMASK(12, 0)

#define REG_RX_CTRL_46				0x6e0
#define   QP_PMA_QP_PCIE_USB_BYPASS_EQ_P1_TO_P0_EN BIT(27)
#define   QP_PMA_REBACK_P0_LCK2REF_EN		BIT(26)

#define REG_RX_CTRL_50				0x6f0
#define   QP_PMA_QP_EQ_EN_DLY_SHORT		GENMASK(25, 13)
#define   QP_PMA_QP_RX_EQ_EN_H_DLY_SHORT	GENMASK(12, 0)

/* QPhy DIG */
#define REG_QP_CK_RST_CTRL_3			0x30c
#define   QP_DIG_NS_CK_DIV_SEL			BIT(25)
#define   QP_DIG_US_CK_DIV_SEL			BIT(24)

#define REG_QP_CK_RST_CTRL_7			0x340
#define   QP_DIG_MULTI_PHY_USB2P5_EN		BIT(26)
#define   QP_DIG_MULTI_PHY_USB5_EN		BIT(25)
#define   QP_DIG_MULTI_PHY_USB_MODE_EN		BIT(24)

/* G3 ANA */
#define REG_PXP_CMN_EN				0x0
#define   G3_ANA_PXP_CMN_TRIM			GENMASK(28, 24)
#define   G3_ANA_PXP_CMN_EN			BIT(0)

#define REG_PXP_JCPLL_IB_EXT_EN			0x4
#define   G3_ANA_PXP_JCPLL_CHP_IOFST		GENMASK(29, 24)
#define   G3_ANA_PXP_JCPLL_CHP_IBIAS		GENMASK(21, 16)
#define   G3_ANA_PXP_JCPLL_LPF_SHCK_EN		BIT(8)

#define REG_PXP_JCPLL_LPF_BR			0x8
#define   G3_ANA_PXP_JCPLL_LPF_BWR		GENMASK(28, 24)
#define   G3_ANA_PXP_JCPLL_LPF_BP		GENMASK(20, 16)
#define   G3_ANA_PXP_JCPLL_LPF_BC		GENMASK(12, 8)
#define   G3_ANA_PXP_JCPLL_LPF_BR		GENMASK(4, 0)

#define REG_PXP_JCPLL_LPF_BWC			0xc
#define   G3_ANA_PXP_JCPLL_KBAND_DIV		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_KBAND_CODE		GENMASK(23, 16)
#define   G3_ANA_PXP_JCPLL_LPF_BWC		GENMASK(4, 0)

#define REG_PXP_JCPLL_KBAND_KFC			0x10
#define   G3_ANA_PXP_JCPLL_POSTDIV_EN		BIT(24)
#define   G3_ANA_PXP_JCPLL_KBAND_KS		GENMASK(17, 16)
#define   G3_ANA_PXP_JCPLL_KBAND_KF		GENMASK(9, 8)
#define   G3_ANA_PXP_JCPLL_KBAND_KFC		GENMASK(1, 0)

#define REG_PXP_JCPLL_MMD_PREDIV_MODE		0x14
#define   G3_ANA_PXP_JCPLL_POSTDIV_D5		BIT(24)
#define   G3_ANA_PXP_JCPLL_POSTDIV_D2		BIT(16)
#define   G3_ANA_PXP_JCPLL_MMD_PREDIV_MODE	GENMASK(1, 0)

#define REG_PXP_JCPLL_MONCK_EN			0x18
#define   G3_ANA_PXP_JCPLL_REFIN_DIV		GENMASK(25, 24)

#define REG_PXP_JCPLL_RST_DLY			0x1c
#define   G3_ANA_PXP_JCPLL_SDM_DI_LS		GENMASK(25, 24)
#define   G3_ANA_PXP_JCPLL_SDM_DI_EN		BIT(16)
#define   G3_ANA_PXP_JCPLL_PLL_RSTB		BIT(8)
#define   G3_ANA_PXP_JCPLL_RST_DLY		GENMASK(2, 0)

#define REG_PXP_JCPLL_SDM_IFM			0x20
#define   G3_ANA_PXP_JCPLL_SDM_IFM		BIT(0)

#define REG_PXP_JCPLL_SDM_HREN			0x24
#define   G3_ANA_PXP_JCPLL_TCL_AMP_VREF		GENMASK(28, 24)
#define   G3_ANA_PXP_JCPLL_TCL_AMP_GAIN		GENMASK(18, 16)
#define   G3_ANA_PXP_JCPLL_TCL_AMP_EN		BIT(8)
#define   G3_ANA_PXP_JCPLL_SDM_HREN		BIT(0)

#define REG_PXP_JCPLL_TCL_CMP_EN		0x28
#define   G3_ANA_PXP_JCPLL_TCL_LPF_BW		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_TCL_LPF_EN		BIT(16)

#define REG_PXP_JCPLL_VCODIV			0x2c
#define   G3_ANA_PXP_JCPLL_VCO_SCAPWR		GENMASK(26, 24)
#define   G3_ANA_PXP_JCPLL_VCO_HALFLSB_EN	BIT(16)
#define   G3_ANA_PXP_JCPLL_VCO_CFIX		GENMASK(9, 8)

#define REG_PXP_JCPLL_VCO_TCLVAR		0x30
#define   G3_ANA_PXP_JCPLL_SSC_PHASE_INI	BIT(17)
#define   G3_ANA_PXP_JCPLL_SSC_EN		BIT(16)
#define   G3_ANA_PXP_JCPLL_VCO_TCLVAR		GENMASK(2, 0)

#define REG_PXP_JCPLL_SSC_TRI_EN		0x34
#define   G3_ANA_PXP_JCPLL_SSC_DELTA1		GENMASK(23, 8)
#define   G3_ANA_PXP_JCPLL_SSC_TRI_EN		BIT(0)

#define REG_PXP_JCPLL_SSC_DELTA			0x38
#define   G3_ANA_PXP_JCPLL_SSC_PERIOD		GENMASK(31, 16)
#define   G3_ANA_PXP_JCPLL_SSC_DELTA		GENMASK(15, 0)

#define REG_PXP_JCPLL_SPARE_H			0x48
#define   G3_ANA_PXP_JCPLL_TCL_KBAND_VREF	GENMASK(20, 16)
#define   G3_ANA_PXP_JCPLL_SPARE_L		GENMASK(15, 8)

#define REG_PXP_JCPLL_FREQ_MEAS_EN		0x4c
#define   G3_ANA_PXP_TXPLL_LPF_SHCK_EN		BIT(25)
#define   G3_ANA_PXP_JCPLL_VCO_KBAND_MEAS_EN	BIT(8)

#define REG_PXP_TXPLL_CHP_IBIAS			0x50
#define   G3_ANA_PXP_TXPLL_LPF_BC		GENMASK(28, 24)
#define   G3_ANA_PXP_TXPLL_LPF_BR		GENMASK(20, 16)
#define   G3_ANA_PXP_TXPLL_CHP_IOFST		GENMASK(13, 8)
#define   G3_ANA_PXP_TXPLL_CHP_IBIAS		GENMASK(5, 0)

#define REG_PXP_TXPLL_LPF_BP			0x54
#define   G3_ANA_PXP_TXPLL_LPF_BWC		GENMASK(20, 16)
#define   G3_ANA_PXP_TXPLL_LPF_BWR		GENMASK(12, 8)
#define   G3_ANA_PXP_TXPLL_LPF_BP		GENMASK(4, 0)

#define REG_PXP_TXPLL_KBAND_CODE		0x58
#define   G3_ANA_PXP_TXPLL_KBAND_KF		GENMASK(25, 24)
#define   G3_ANA_PXP_TXPLL_KBAND_KFC		GENMASK(17, 16)
#define   G3_ANA_PXP_TXPLL_KBAND_DIV		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_KBAND_CODE		GENMASK(7, 0)

#define REG_PXP_TXPLL_KBAND_KS			0x5c
#define   G3_ANA_PXP_TXPLL_MMD_PREDIV_MODE	GENMASK(17, 16)
#define   G3_ANA_PXP_TXPLL_POSTDIV_EN		BIT(8)
#define   G3_ANA_PXP_TXPLL_KBAND_KS		GENMASK(1, 0)

#define REG_PXP_TXPLL_PHY_CK1_EN		0x60
#define   G3_ANA_PXP_TXPLL_PHY_CK1_EN		BIT(0)

#define REG_PXP_TXPLL_REFIN_INTERNAL		0x64
#define   G3_ANA_PXP_TXPLL_PLL_RSTB		BIT(24)
#define   G3_ANA_PXP_TXPLL_RST_DLY		GENMASK(18, 16)
#define   G3_ANA_PXP_TXPLL_REFIN_DIV		GENMASK(9, 8)
#define   G3_ANA_PXP_TXPLL_REFIN_INTERNAL	BIT(0)

#define REG_PXP_TXPLL_SDM_DI_EN			0x68
#define   G3_ANA_PXP_TXPLL_SDM_IFM		BIT(16)
#define   G3_ANA_PXP_TXPLL_SDM_DI_LS		GENMASK(9, 8)

#define REG_PXP_TXPLL_SDM_ORD			0x6c
#define   G3_ANA_PXP_TXPLL_TCL_AMP_EN		BIT(24)
#define   G3_ANA_PXP_TXPLL_SDM_ORD		GENMASK(1, 0)

#define REG_PXP_TXPLL_TCL_AMP_GAIN		0x70
#define   G3_ANA_PXP_TXPLL_TCL_AMP_VREF		GENMASK(12, 8)
#define   G3_ANA_PXP_TXPLL_TCL_AMP_GAIN		GENMASK(2, 0)

#define REG_PXP_TXPLL_TCL_LPF_EN		0x74
#define   G3_ANA_PXP_TXPLL_VCO_CFIX		GENMASK(25, 24)
#define   G3_ANA_PXP_TXPLL_TCL_LPF_BW		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_TCL_LPF_EN		BIT(0)

#define REG_PXP_TXPLL_VCO_HALFLSB_EN		0x78
#define   G3_ANA_PXP_TXPLL_VCO_SCAPWR		GENMASK(10, 8)
#define   G3_ANA_PXP_TXPLL_VCO_HALFLSB_EN	BIT(0)

#define REG_PXP_TXPLL_SSC_EN			0x7c
#define   G3_ANA_PXP_TXPLL_SSC_PHASE_INI	BIT(8)
#define   G3_ANA_PXP_TXPLL_SSC_EN		BIT(0)

#define REG_PXP_TXPLL_SSC_DELTA1		0x80
#define   G3_ANA_PXP_TXPLL_SSC_DELTA		GENMASK(31, 16)
#define   G3_ANA_PXP_TXPLL_SSC_DELTA1		GENMASK(15, 0)

#define REG_PXP_TXPLL_SSC_PERIOD		0x84
#define   G3_ANA_PXP_TXPLL_SSC_PERIOD		GENMASK(15, 0)

#define REG_PXP_TXPLL_VTP_EN			0x88
#define   G3_ANA_PXP_TXPLL_VTP_EN		BIT(0)

#define REG_PXP_TXPLL_TCL_VTP_EN		0x90
#define   G3_ANA_PXP_TXPLL_SPARE_L		GENMASK(31, 24)

#define REG_PXP_TXPLL_TCL_KBAND_VREF		0x94
#define   G3_ANA_PXP_TXPLL_VCO_KBAND_MEAS_EN	BIT(24)
#define   G3_ANA_PXP_TXPLL_TCL_KBAND_VREF	GENMASK(4, 0)

#define REG_PCIE_CLKTX0_AMP			0x98
#define   G3_ANA_PXP_PCIE_CLKTX0_IMP_SEL	GENMASK(31, 27)
#define   G3_ANA_PXP_PCIE_CLKTX0_HZ		BIT(26)
#define   G3_ANA_PCIE_CLKTX0_SR			GENMASK(17, 16)
#define   G3_ANA_PCIE_CLKTX0_OFFSET		GENMASK(9, 8)
#define   G3_ANA_PCIE_CLKTX0_AMP		GENMASK(2, 0)

#define REG_PXP_PLL_MONCLK_SEL			0xa0
#define   G3_ANA_PXP_PLL_CMN_RESERVE0		GENMASK(15, 8)

#define REG_PXP_TX_CKLDO_EN			0xc4
#define   G3_ANA_PXP_TX_DMEDGEGEN_EN		BIT(24)
#define   G3_ANA_PXP_TX_CKLDO_EN		BIT(0)

#define REG_PXP_RX_REV_0			0xd4
#define   G3_ANA_PXP_RX_REV_1_10_8		GENMASK(26, 24)
#define   G3_ANA_PXP_RX_REV_1_6_4		GENMASK(22, 20)
#define   G3_ANA_PXP_RX_REV_1_3_2		GENMASK(19, 18)

#define REG_PXP_RX_PHYCK_DIV			0xd8
#define   G3_ANA_PXP_RX_TDC_CK_SEL		BIT(24)
#define   G3_ANA_PXP_RX_PHYCK_RSTB		BIT(16)
#define   G3_ANA_PXP_RX_PHYCK_SEL		GENMASK(9, 8)

#define REG_PXP_CDR_PD_PICAL_CKD8_INV		0xdc
#define   G3_ANA_PXP_CDR_PD_EDGE_DIS		BIT(8)

#define REG_PXP_CDR_LPF_RATIO			0xe8
#define   G3_ANA_PXP_CDR_LPF_TOP_LIM		GENMASK(26, 8)

#define REG_PXP_CDR_PR_BETA_DAC			0xf8
#define   G3_ANA_PXP_CDR_PR_KBAND_DIV		GENMASK(26, 24)
#define   G3_ANA_PXP_CDR_PR_BETA_SEL		GENMASK(19, 16)

#define REG_PXP_CDR_PR_VREG_IBAND_VAL		0xfc
#define   G3_ANA_PXP_CDR_PR_VREG_CKBUF_VAL_2_0	GENMASK(10, 8)
#define   G3_ANA_PXP_CDR_PR_VREG_IBAND_VAL_2_0	GENMASK(2, 0)

#define REG_PXP_CDR_PR_CKREF_DIV		0x100
#define   G3_ANA_PXP_CDR_PR_CKREF_DIV_1_0	GENMASK(1, 0)

#define REG_PXP_CDR_PR_TDC_REF_SEL		0x108
#define   G3_ANA_PXP_CDR_PR_CKREF_DIV1_1_0	GENMASK(25, 24)
#define   G3_ANA_PXP_CDR_PR_LDO_FORCE_ON	BIT(16)

#define REG_PXP_CDR_PR_MONPR_EN			0x10c
#define   G3_ANA_PXP_CDR_PR_XFICK_EN		BIT(2)

#define REG_PXP_RX_DAC_RANGE			0x110
#define   G3_ANA_PXP_RX_SIGDET_LPF_CTRL		GENMASK(25, 24)

#define REG_PXP_CDR_PR_MONCK_EN			0x104
#define   G3_ANA_PXP_CDR_PR_MONCK_EN		BIT(0)
#define   G3_ANA_PXP_CDR_PR_RESERVE0		GENMASK(19, 16)

#define REG_PXP_RX_SIGDET_NOVTH			0x114
#define   G3_ANA_PXP_RX_FE_50OHMS_SEL		GENMASK(25, 24)
#define   G3_ANA_PXP_RX_SIGDET_VTH_SEL_4_0	GENMASK(20, 16)
#define   G3_ANA_PXP_RX_SIGDET_PEAK_1_0		GENMASK(9, 8)

#define REG_PXP_RX_FE_EQ_HZEN			0x118
#define   G3_ANA_PXP_RX_FE_VB_EQ3_EN		BIT(24)
#define   G3_ANA_PXP_RX_FE_VB_EQ2_EN		BIT(16)
#define   G3_ANA_PXP_RX_FE_VB_EQ1_EN		BIT(8)

#define REG_PXP_RX_FE_VCM_GEN_PWDB		0x11c
#define   G3_ANA_PXP_RX_FE_VCM_GEN_PWDB		BIT(0)

#define REG_PXP_RX_OSCAL_CTLE2IOS		0x128
#define   G3_ANA_PXP_RX_OSCAL_VGA1VOS		GENMASK(29, 24)
#define   G3_ANA_PXP_RX_OSCAL_VGA1IOS		GENMASK(21, 16)

#define REG_PXP_RX_OSCAL_VGA2IOS		0x12c
#define   G3_ANA_PXP_RX_OSCAL_VGA2IOS		GENMASK(5, 0)

/* G3 PMA */
#define REG_RX_CTRL_SEQUENCE_DISB_CTRL_1	0x10c
#define   G3_PMA_DISB_RX_SDCAL_EN		BIT(0)

#define REG_RX_CTRL_SEQUENCE_FORCE_CTRL_1	0x114
#define   G3_PMA_FORCE_RX_SDCAL_EN		BIT(0)

#define REG_SS_RX_CAL_2				0x164
#define   G3_PMA_CAL_OUT_OS			GENMASK(11, 8)

#define REG_SS_RX_SIGDET_0			0x168
#define   G3_PMA_SIGDET_WIN_NONVLD_TIMES	GENMASK(28, 24)

#define REG_SS_TX_RST_B				0x260
#define   G3_PMA_TXCALIB_RST_B			BIT(8)
#define   G3_PMA_TX_TOP_RST_B			BIT(0)

#define REG_RX_FORCE_MODE_0			0x294
#define   G3_PMA_FORCE_DA_XPON_RX_FE_GAIN_CTRL	GENMASK(1, 0)

#define REG_SS_DA_XPON_PWDB_0			0x34c
#define   G3_PMA_DA_XPON_CDR_PR_PWDB		BIT(8)

#define REG_SW_RST_SET				0x460
#define   G3_PMA_SW_XFI_RXPCS_RST_N		BIT(8)
#define   G3_PMA_SW_TX_FIFO_RST_N		BIT(6)
#define   G3_PMA_SW_REF_RST_N			BIT(5)
#define   G3_PMA_SW_ALLPCS_RST_N		BIT(4)
#define   G3_PMA_SW_PMA_RST_N			BIT(3)
#define   G3_PMA_SW_TX_RST_N			BIT(2)
#define   G3_PMA_SW_RX_RST_N			BIT(1)
#define   G3_PMA_SW_RX_FIFO_RST_N		BIT(0)

#define REG_FORCE_DA_PXP_TX_TERM_SEL		0x77c
#define   G3_PMA_FORCE_SEL_DA_PXP_TX_TERM_SEL	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_TX_TERM_SEL	GENMASK(2, 0)

#define REG_FORCE_DA_PXP_CDR_PR_FLL_COR		0x790
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_DAC_EYE	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_RX_DAC_EYE	GENMASK(22, 16)

#define REG_FORCE_DA_PXP_CDR_PR_IDAC		0x794
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_SDM_PCW	BIT(24)

#define REG_FORCE_DA_PXP_TXPLL_SDM_PCW		0x798
#define   G3_PMA_FORCE_DA_PXP_TXPLL_SDM_PCW	GENMASK(30, 0)

#define REG_FORCE_DA_PXP_RX_FE_VOS		0x79c
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_SDM_PCW	BIT(16)

#define REG_FORCE_DA_PXP_JCPLL_SDM_PCW		0x800
#define   G3_PMA_FORCE_DA_PXP_JCPLL_SDM_PCW	GENMASK(30, 0)

#define REG_FORCE_DA_PXP_CDR_PD_PWDB		0x81c
#define   G3_PMA_FORCE_SEL_DA_PXP_CDR_PD_PWDB	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_CDR_PD_PWDB	BIT(0)

#define REG_FORCE_DA_PXP_CDR_PR_PIEYE_PWDB	0x824
#define   G3_PMA_FORCE_SEL_DA_PXP_CDR_PR_PIEYE_PWDB BIT(8)
#define   G3_PMA_FORCE_DA_PXP_CDR_PR_PIEYE_PWDB	BIT(0)

#define REG_FORCE_DA_PXP_JCPLL_CKOUT_EN		0x828
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_EN	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_EN		BIT(16)
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_CKOUT_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_CKOUT_EN	BIT(0)

#define REG_FORCE_DA_PXP_RX_SCAN_RST_B		0x84c
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_SIGDET_PWDB BIT(24)
#define   G3_PMA_FORCE_DA_PXP_RX_SIGDET_PWDB	BIT(16)

#define REG_FORCE_DA_PXP_TXPLL_CKOUT_EN		0x854
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_EN	BIT(24)
#define   G3_PMA_FORCE_DA_PXP_TXPLL_EN		BIT(16)
#define   G3_PMA_FORCE_SEL_DA_PXP_TXPLL_CKOUT_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_TXPLL_CKOUT_EN	BIT(0)

#define REG_SCAN_MODE				0x884
#define   G3_PMA_FORCE_SEL_DA_PXP_JCPLL_KBAND_LOAD_EN BIT(8)
#define   G3_PMA_FORCE_DA_PXP_JCPLL_KBAND_LOAD_EN BIT(0)

#define REG_FORCE_DA_PXP_RX_FE_GAIN_CTRL	0x88c
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_FE_GAIN_CTRL BIT(8)
#define   G3_PMA_FORCE_DA_PXP_RX_FE_GAIN_CTRL	GENMASK(1, 0)

#define REG_FORCE_DA_PXP_RX_FE_PWDB		0x894
#define   G3_PMA_FORCE_SEL_DA_PXP_RX_FE_PWDB	BIT(8)
#define   G3_PMA_FORCE_DA_PXP_RX_FE_PWDB	BIT(0)

#define REG_ADD_DIG_RESERVE_12			0x8b8
#define   G3_PMA_DIG_RESERVE_12_8_8		BIT(8)

#define REG_ADD_DIG_RESERVE_27			0x908
#define   G3_PMA_DIG_RESERVE_27_16_16		BIT(16)

#define REG_ADD_DIG_RESERVE_30			0x914
#define   G3_PMA_DIG_RESERVE_30			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_31			0x918
#define   G3_PMA_DIG_RESERVE_31_20_16		GENMASK(20, 16)
#define   G3_PMA_DIG_RESERVE_31_12_8		GENMASK(12, 8)
#define   G3_PMA_DIG_RESERVE_31_4_0		GENMASK(4, 0)

#define REG_ADD_DIG_RESERVE_32			0x91c
#define   G3_PMA_DIG_RESERVE_32_31_16		GENMASK(31, 16)

#define REG_ADD_DIG_RESERVE_33			0x920
#define   G3_PMA_DIG_RESERVE_33_31_16		GENMASK(31, 16)
#define   G3_PMA_DIG_RESERVE_33_15_0		GENMASK(15, 0)

#define REG_ADD_DIG_RESERVE_34			0x924
#define   G3_PMA_DIG_RESERVE_34			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_35			0x928
#define   G3_PMA_DIG_RESERVE_35			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_40			0x93c
#define   G3_PMA_DIG_RESERVE_40			GENMASK(31, 0)

#define REG_ADD_DIG_RESERVE_43			0x948
#define   G3_PMA_DIG_RESERVE_43_18_16		GENMASK(18, 16)
#define   G3_PMA_DIG_RESERVE_43_14_12		GENMASK(14, 12)
#define   G3_PMA_DIG_RESERVE_43_10_8		GENMASK(10, 8)

/* DTIME */
#define REG_PCIE_PEXTP_DIG_GLB44		0x0
#define PCIE_XTP_RXDET_LATCH_STB_T_SEL		GENMASK(31, 29)
#define PCIE_XTP_TXPD_RXDET_DONE_CDT		BIT(28)
#define PCIE_XTP_TXPD_TX_DATA_EN_DLY		GENMASK(27, 24)
#define PCIE_XTP_RXDET_FINISH_STB_T_SEL		GENMASK(23, 16)
#define PCIE_XTP_RXDET_EN_STB_T_SEL		GENMASK(15, 8)
#define PCIE_XTP_RXDET_VCM_OFF_STB_T_SEL	GENMASK(7, 0)

/* RX AEQ */
#define REG_PCIE_PEXTP_DIG_LN_RX30		0x0
#define PCIE_XTP_LN_RX_PDOWN_E0_AEQEN_WAIT	GENMASK(31, 16)
#define PCIE_XTP_LN_RX_PDOWN_T2RLB_DIG_EN	BIT(8)
#define PCIE_XTP_LN_RX_PDOWN_L1P2_EXIT_WAIT	GENMASK(7, 0)

#endif /* _PHY_AIROHA_PCIE_H */
