/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/ulp_ddp.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_ULP_DDP_H
#define _UAPI_LINUX_ULP_DDP_H

#define ULP_DDP_FAMILY_NAME	"ulp_ddp"
#define ULP_DDP_FAMILY_VERSION	1

enum ulp_ddp_cap {
	ULP_DDP_CAP_NVME_TCP,
	ULP_DDP_CAP_NVME_TCP_DDGST_RX,
};

enum {
	ULP_DDP_A_STAT_IFINDEX = 1,
	ULP_DDP_A_STAT_PAD,
	ULP_DDP_A_STAT_RX_NVMEOTCP_SK_ADD,
	ULP_DDP_A_STAT_RX_NVMEOTCP_SK_ADD_FAIL,
	ULP_DDP_A_STAT_RX_NVMEOTCP_SK_DEL,
	ULP_DDP_A_STAT_RX_NVMEOTCP_SETUP,
	ULP_DDP_A_STAT_RX_NVMEOTCP_SETUP_FAIL,
	ULP_DDP_A_STAT_RX_NVMEOTCP_TEARDOWN,
	ULP_DDP_A_STAT_RX_NVMEOTCP_DROP,
	ULP_DDP_A_STAT_RX_NVMEOTCP_RESYNC,
	ULP_DDP_A_STAT_RX_NVMEOTCP_PACKETS,
	ULP_DDP_A_STAT_RX_NVMEOTCP_BYTES,

	__ULP_DDP_A_STAT_MAX,
	ULP_DDP_A_STAT_MAX = (__ULP_DDP_A_STAT_MAX - 1)
};

enum {
	ULP_DDP_A_DEV_IFINDEX = 1,
	ULP_DDP_A_DEV_HW,
	ULP_DDP_A_DEV_ACTIVE,
	ULP_DDP_A_DEV_WANTED,
	ULP_DDP_A_DEV_WANTED_MASK,
	ULP_DDP_A_DEV_PAD,

	__ULP_DDP_A_DEV_MAX,
	ULP_DDP_A_DEV_MAX = (__ULP_DDP_A_DEV_MAX - 1)
};

enum {
	ULP_DDP_CMD_GET = 1,
	ULP_DDP_CMD_STATS,
	ULP_DDP_CMD_SET,
	ULP_DDP_CMD_SET_NTF,

	__ULP_DDP_CMD_MAX,
	ULP_DDP_CMD_MAX = (__ULP_DDP_CMD_MAX - 1)
};

#define ULP_DDP_MCGRP_MGMT	"mgmt"

#endif /* _UAPI_LINUX_ULP_DDP_H */
