/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/ulp_ddp.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_ULP_DDP_H
#define _UAPI_LINUX_ULP_DDP_H

#define ULP_DDP_FAMILY_NAME	"ulp_ddp"
#define ULP_DDP_FAMILY_VERSION	1

enum ulp_ddp_cap {
	ULP_DDP_CAP_NVME_TCP,
	ULP_DDP_CAP_NVME_TCP_DDGST_RX,

	/* private: */
	__ULP_DDP_CAP_MAX,
	ULP_DDP_CAP_MAX = (__ULP_DDP_CAP_MAX - 1)
};

enum {
	ULP_DDP_A_STATS_IFINDEX = 1,
	ULP_DDP_A_STATS_RX_NVME_TCP_SK_ADD,
	ULP_DDP_A_STATS_RX_NVME_TCP_SK_ADD_FAIL,
	ULP_DDP_A_STATS_RX_NVME_TCP_SK_DEL,
	ULP_DDP_A_STATS_RX_NVME_TCP_SETUP,
	ULP_DDP_A_STATS_RX_NVME_TCP_SETUP_FAIL,
	ULP_DDP_A_STATS_RX_NVME_TCP_TEARDOWN,
	ULP_DDP_A_STATS_RX_NVME_TCP_DROP,
	ULP_DDP_A_STATS_RX_NVME_TCP_RESYNC,
	ULP_DDP_A_STATS_RX_NVME_TCP_PACKETS,
	ULP_DDP_A_STATS_RX_NVME_TCP_BYTES,

	__ULP_DDP_A_STATS_MAX,
	ULP_DDP_A_STATS_MAX = (__ULP_DDP_A_STATS_MAX - 1)
};

enum {
	ULP_DDP_A_CAPS_IFINDEX = 1,
	ULP_DDP_A_CAPS_HW,
	ULP_DDP_A_CAPS_ACTIVE,
	ULP_DDP_A_CAPS_WANTED,
	ULP_DDP_A_CAPS_WANTED_MASK,

	__ULP_DDP_A_CAPS_MAX,
	ULP_DDP_A_CAPS_MAX = (__ULP_DDP_A_CAPS_MAX - 1)
};

enum {
	ULP_DDP_CMD_CAPS_GET = 1,
	ULP_DDP_CMD_STATS_GET,
	ULP_DDP_CMD_CAPS_SET,
	ULP_DDP_CMD_CAPS_SET_NTF,

	__ULP_DDP_CMD_MAX,
	ULP_DDP_CMD_MAX = (__ULP_DDP_CMD_MAX - 1)
};

#define ULP_DDP_MCGRP_MGMT	"mgmt"

#endif /* _UAPI_LINUX_ULP_DDP_H */
