/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/ultraeth.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_ULTRAETH_NL_H
#define _UAPI_LINUX_ULTRAETH_NL_H

#define ULTRAETH_FAMILY_NAME	"ultraeth"
#define ULTRAETH_FAMILY_VERSION	1

enum {
	ULTRAETH_A_CONTEXT_ID = 1,

	__ULTRAETH_A_CONTEXT_MAX,
	ULTRAETH_A_CONTEXT_MAX = (__ULTRAETH_A_CONTEXT_MAX - 1)
};

enum {
	ULTRAETH_A_CONTEXTS_CONTEXT = 1,

	__ULTRAETH_A_CONTEXTS_MAX,
	ULTRAETH_A_CONTEXTS_MAX = (__ULTRAETH_A_CONTEXTS_MAX - 1)
};

enum {
	ULTRAETH_A_FEP_IN_ADDR_IP = 1,
	ULTRAETH_A_FEP_IN_ADDR_IP6,
	ULTRAETH_A_FEP_IN_ADDR_FAMILY,

	__ULTRAETH_A_FEP_IN_ADDR_MAX,
	ULTRAETH_A_FEP_IN_ADDR_MAX = (__ULTRAETH_A_FEP_IN_ADDR_MAX - 1)
};

enum {
	ULTRAETH_A_FEP_ADDRESS_IN_ADDRESS = 1,
	ULTRAETH_A_FEP_ADDRESS_FLAGS,
	ULTRAETH_A_FEP_ADDRESS_CAPS,
	ULTRAETH_A_FEP_ADDRESS_START_RESOURCE_INDEX,
	ULTRAETH_A_FEP_ADDRESS_NUM_RESOURCE_INDICES,
	ULTRAETH_A_FEP_ADDRESS_INITIATOR_ID,
	ULTRAETH_A_FEP_ADDRESS_PID_ON_FEP,
	ULTRAETH_A_FEP_ADDRESS_PADDING,
	ULTRAETH_A_FEP_ADDRESS_VERSION,

	__ULTRAETH_A_FEP_ADDRESS_MAX,
	ULTRAETH_A_FEP_ADDRESS_MAX = (__ULTRAETH_A_FEP_ADDRESS_MAX - 1)
};

enum {
	ULTRAETH_A_FEP_ENTRY_ADDRESS = 1,

	__ULTRAETH_A_FEP_ENTRY_MAX,
	ULTRAETH_A_FEP_ENTRY_MAX = (__ULTRAETH_A_FEP_ENTRY_MAX - 1)
};

enum {
	ULTRAETH_A_FLIST_FEP = 1,

	__ULTRAETH_A_FLIST_MAX,
	ULTRAETH_A_FLIST_MAX = (__ULTRAETH_A_FLIST_MAX - 1)
};

enum {
	ULTRAETH_A_JOB_REQ_CONTEXT_ID = 1,
	ULTRAETH_A_JOB_REQ_ID,
	ULTRAETH_A_JOB_REQ_ADDRESS,
	ULTRAETH_A_JOB_REQ_SERVICE_NAME,

	__ULTRAETH_A_JOB_REQ_MAX,
	ULTRAETH_A_JOB_REQ_MAX = (__ULTRAETH_A_JOB_REQ_MAX - 1)
};

enum {
	ULTRAETH_A_JOB_ID = 1,
	ULTRAETH_A_JOB_ADDRESS,
	ULTRAETH_A_JOB_SERVICE_NAME,
	ULTRAETH_A_JOB_FLIST,

	__ULTRAETH_A_JOB_MAX,
	ULTRAETH_A_JOB_MAX = (__ULTRAETH_A_JOB_MAX - 1)
};

enum {
	ULTRAETH_A_JLIST_JOB = 1,

	__ULTRAETH_A_JLIST_MAX,
	ULTRAETH_A_JLIST_MAX = (__ULTRAETH_A_JLIST_MAX - 1)
};

enum {
	ULTRAETH_A_JOBS_CONTEXT_ID = 1,
	ULTRAETH_A_JOBS_JLIST,

	__ULTRAETH_A_JOBS_MAX,
	ULTRAETH_A_JOBS_MAX = (__ULTRAETH_A_JOBS_MAX - 1)
};

enum {
	ULTRAETH_CMD_CONTEXT_GET = 1,
	ULTRAETH_CMD_CONTEXT_NEW,
	ULTRAETH_CMD_CONTEXT_DEL,
	ULTRAETH_CMD_JOB_GET,
	ULTRAETH_CMD_JOB_NEW,
	ULTRAETH_CMD_JOB_DEL,

	__ULTRAETH_CMD_MAX,
	ULTRAETH_CMD_MAX = (__ULTRAETH_CMD_MAX - 1)
};

#endif /* _UAPI_LINUX_ULTRAETH_NL_H */
