# SPDX-License-Identifier: GPL-2.0-only
# Makefile for firmware loading selftests
CFLAGS = -Wall \
         -O2

TEST_PROGS := fw_run_tests.sh ghes_nvidia_einj.sh
TEST_FILES := fw_fallback.sh fw_filesystem.sh fw_upload.sh fw_lib.sh einj_lib.sh ghes_nvidia_einj_profiles.sh
TEST_GEN_FILES := fw_namespace

include ../lib.mk
