/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 * Copyright (c) 2024, SaluteDevices. All Rights Reserved.
 *
 * Author: Jan Dakinevich <jan.dakinevich@salutedevices.com>
 */

#ifndef __A1_AUDIO_CLKC_BINDINGS_H
#define __A1_AUDIO_CLKC_BINDINGS_H

#define AUD_CLKID_DDR_ARB		1
#define AUD_CLKID_TDMIN_A		2
#define AUD_CLKID_TDMIN_B		3
#define AUD_CLKID_TDMIN_LB		4
#define AUD_CLKID_LOOPBACK		5
#define AUD_CLKID_TDMOUT_A		6
#define AUD_CLKID_TDMOUT_B		7
#define AUD_CLKID_FRDDR_A		8
#define AUD_CLKID_FRDDR_B		9
#define AUD_CLKID_TODDR_A		10
#define AUD_CLKID_TODDR_B		11
#define AUD_CLKID_SPDIFIN		12
#define AUD_CLKID_RESAMPLE		13
#define AUD_CLKID_EQDRC			14
#define AUD_CLKID_LOCKER		15
#define AUD_CLKID_MST_A_MCLK_SEL	16
#define AUD_CLKID_MST_A_MCLK_DIV	17
#define AUD_CLKID_MST_A_MCLK		18
#define AUD_CLKID_MST_B_MCLK_SEL	19
#define AUD_CLKID_MST_B_MCLK_DIV	20
#define AUD_CLKID_MST_B_MCLK		21
#define AUD_CLKID_MST_C_MCLK_SEL	22
#define AUD_CLKID_MST_C_MCLK_DIV	23
#define AUD_CLKID_MST_C_MCLK		24
#define AUD_CLKID_MST_D_MCLK_SEL	25
#define AUD_CLKID_MST_D_MCLK_DIV	26
#define AUD_CLKID_MST_D_MCLK		27
#define AUD_CLKID_SPDIFIN_CLK_SEL	28
#define AUD_CLKID_SPDIFIN_CLK_DIV	29
#define AUD_CLKID_SPDIFIN_CLK		30
#define AUD_CLKID_RESAMPLE_CLK_SEL	31
#define AUD_CLKID_RESAMPLE_CLK_DIV	32
#define AUD_CLKID_RESAMPLE_CLK		33
#define AUD_CLKID_LOCKER_IN_CLK_SEL	34
#define AUD_CLKID_LOCKER_IN_CLK_DIV	35
#define AUD_CLKID_LOCKER_IN_CLK		36
#define AUD_CLKID_LOCKER_OUT_CLK_SEL	37
#define AUD_CLKID_LOCKER_OUT_CLK_DIV	38
#define AUD_CLKID_LOCKER_OUT_CLK	39
#define AUD_CLKID_EQDRC_CLK_SEL		40
#define AUD_CLKID_EQDRC_CLK_DIV		41
#define AUD_CLKID_EQDRC_CLK		42
#define AUD_CLKID_MST_A_SCLK_PRE_EN	43
#define AUD_CLKID_MST_A_SCLK_DIV	44
#define AUD_CLKID_MST_A_SCLK_POST_EN	45
#define AUD_CLKID_MST_A_SCLK		46
#define AUD_CLKID_MST_B_SCLK_PRE_EN	47
#define AUD_CLKID_MST_B_SCLK_DIV	48
#define AUD_CLKID_MST_B_SCLK_POST_EN	49
#define AUD_CLKID_MST_B_SCLK		50
#define AUD_CLKID_MST_C_SCLK_PRE_EN	51
#define AUD_CLKID_MST_C_SCLK_DIV	52
#define AUD_CLKID_MST_C_SCLK_POST_EN	53
#define AUD_CLKID_MST_C_SCLK		54
#define AUD_CLKID_MST_D_SCLK_PRE_EN	55
#define AUD_CLKID_MST_D_SCLK_DIV	56
#define AUD_CLKID_MST_D_SCLK_POST_EN	57
#define AUD_CLKID_MST_D_SCLK		58
#define AUD_CLKID_MST_A_LRCLK_DIV	59
#define AUD_CLKID_MST_A_LRCLK		60
#define AUD_CLKID_MST_B_LRCLK_DIV	61
#define AUD_CLKID_MST_B_LRCLK		62
#define AUD_CLKID_MST_C_LRCLK_DIV	63
#define AUD_CLKID_MST_C_LRCLK		64
#define AUD_CLKID_MST_D_LRCLK_DIV	65
#define AUD_CLKID_MST_D_LRCLK		66
#define AUD_CLKID_TDMIN_A_SCLK_SEL	67
#define AUD_CLKID_TDMIN_A_SCLK_PRE_EN	68
#define AUD_CLKID_TDMIN_A_SCLK_POST_EN	69
#define AUD_CLKID_TDMIN_A_SCLK		70
#define AUD_CLKID_TDMIN_A_LRCLK		71
#define AUD_CLKID_TDMIN_B_SCLK_SEL	72
#define AUD_CLKID_TDMIN_B_SCLK_PRE_EN	73
#define AUD_CLKID_TDMIN_B_SCLK_POST_EN	74
#define AUD_CLKID_TDMIN_B_SCLK		75
#define AUD_CLKID_TDMIN_B_LRCLK		76
#define AUD_CLKID_TDMIN_LB_SCLK_SEL	77
#define AUD_CLKID_TDMIN_LB_SCLK_PRE_EN	78
#define AUD_CLKID_TDMIN_LB_SCLK_POST_EN	79
#define AUD_CLKID_TDMIN_LB_SCLK		80
#define AUD_CLKID_TDMIN_LB_LRCLK	81
#define AUD_CLKID_TDMOUT_A_SCLK_SEL	82
#define AUD_CLKID_TDMOUT_A_SCLK_PRE_EN	83
#define AUD_CLKID_TDMOUT_A_SCLK_POST_EN	84
#define AUD_CLKID_TDMOUT_A_SCLK		85
#define AUD_CLKID_TDMOUT_A_LRCLK	86
#define AUD_CLKID_TDMOUT_B_SCLK_SEL	87
#define AUD_CLKID_TDMOUT_B_SCLK_PRE_EN	88
#define AUD_CLKID_TDMOUT_B_SCLK_POST_EN	89
#define AUD_CLKID_TDMOUT_B_SCLK		90
#define AUD_CLKID_TDMOUT_B_LRCLK	91

#define AUD2_CLKID_DDR_ARB		100
#define AUD2_CLKID_PDM			101
#define AUD2_CLKID_TDMIN_VAD		102
#define AUD2_CLKID_TODDR_VAD		103
#define AUD2_CLKID_VAD			104
#define AUD2_CLKID_AUDIOTOP		105
#define AUD2_CLKID_VAD_MCLK_SEL		106
#define AUD2_CLKID_VAD_MCLK_DIV		107
#define AUD2_CLKID_VAD_MCLK		108
#define AUD2_CLKID_VAD_CLK_SEL		109
#define AUD2_CLKID_VAD_CLK_DIV		110
#define AUD2_CLKID_VAD_CLK		111
#define AUD2_CLKID_PDM_DCLK_SEL		112
#define AUD2_CLKID_PDM_DCLK_DIV		113
#define AUD2_CLKID_PDM_DCLK		114
#define AUD2_CLKID_PDM_SYSCLK_SEL	115
#define AUD2_CLKID_PDM_SYSCLK_DIV	116
#define AUD2_CLKID_PDM_SYSCLK		117

#endif /* __A1_AUDIO_CLKC_BINDINGS_H */
