/* SPDX-License-Identifier: (GPL-2.0-only OR MIT) */
/*
 * Copyright (c) 2024 Amlogic, Inc. All rights reserved.
 * Author: Chuan Liu <chuan.liu@amlogic.com>
 */

#ifndef _DT_BINDINGS_CLOCK_AMLOGIC_A5_PERIPHERALS_CLKC_H
#define _DT_BINDINGS_CLOCK_AMLOGIC_A5_PERIPHERALS_CLKC_H

#define CLKID_RTC_DUALDIV_CLKIN			0
#define CLKID_RTC_DUALDIV			1
#define CLKID_RTC_DUALDIV_SEL			2
#define CLKID_RTC_DUALDIV_CLKOUT		3
#define CLKID_RTC_CLK				4
#define CLKID_SYS_RESET_CTRL			5
#define CLKID_SYS_PWR_CTRL			6
#define CLKID_SYS_PAD_CTRL			7
#define CLKID_SYS_CTRL				8
#define CLKID_SYS_TS_PLL			9
#define CLKID_SYS_DEV_ARB			10
#define CLKID_SYS_MAILBOX			11
#define CLKID_SYS_JTAG_CTRL			12
#define CLKID_SYS_IR_CTRL			13
#define CLKID_SYS_MSR_CLK			14
#define CLKID_SYS_ROM				15
#define CLKID_SYS_CPU_ARB			16
#define CLKID_SYS_RSA				17
#define CLKID_SYS_SARADC			18
#define CLKID_SYS_STARTUP			19
#define CLKID_SYS_SECURE			20
#define CLKID_SYS_SPIFC				21
#define CLKID_SYS_DSPA				22
#define CLKID_SYS_NNA				23
#define CLKID_SYS_ETH_MAC			24
#define CLKID_SYS_RAMA				25
#define CLKID_SYS_RAMB				26
#define CLKID_SYS_AUDIO_TOP			27
#define CLKID_SYS_AUDIO_VAD			28
#define CLKID_SYS_USB				29
#define CLKID_SYS_SD_EMMC_A			30
#define CLKID_SYS_SD_EMMC_C			31
#define CLKID_SYS_PWM_AB			32
#define CLKID_SYS_PWM_CD			33
#define CLKID_SYS_PWM_EF			34
#define CLKID_SYS_PWM_GH			35
#define CLKID_SYS_SPICC_1			36
#define CLKID_SYS_SPICC_0			37
#define CLKID_SYS_UART_A			38
#define CLKID_SYS_UART_B			39
#define CLKID_SYS_UART_C			40
#define CLKID_SYS_UART_D			41
#define CLKID_SYS_UART_E			42
#define CLKID_SYS_I2C_M_A			43
#define CLKID_SYS_I2C_M_B			44
#define CLKID_SYS_I2C_M_C			45
#define CLKID_SYS_I2C_M_D			46
#define CLKID_SYS_RTC				47
#define CLKID_AXI_AUDIO_VAD			48
#define CLKID_AXI_AUDIO_TOP			49
#define CLKID_AXI_RAMB				50
#define CLKID_AXI_RAMA				51
#define CLKID_AXI_NNA				52
#define CLKID_AXI_DEV1_DMC			53
#define CLKID_AXI_DEV0_DMC			54
#define CLKID_AXI_DSP_DMC			55
#define CLKID_12_24M_IN				56
#define CLKID_12M_24M				57
#define CLKID_FCLK_25M_DIV			58
#define CLKID_FCLK_25M				59
#define CLKID_GEN_SEL				60
#define CLKID_GEN_DIV				61
#define CLKID_GEN				62
#define CLKID_SARADC_SEL			63
#define CLKID_SARADC_DIV			64
#define CLKID_SARADC				65
#define CLKID_PWM_A_SEL				66
#define CLKID_PWM_A_DIV				67
#define CLKID_PWM_A				68
#define CLKID_PWM_B_SEL				69
#define CLKID_PWM_B_DIV				70
#define CLKID_PWM_B				71
#define CLKID_PWM_C_SEL				72
#define CLKID_PWM_C_DIV				73
#define CLKID_PWM_C				74
#define CLKID_PWM_D_SEL				75
#define CLKID_PWM_D_DIV				76
#define CLKID_PWM_D				77
#define CLKID_PWM_E_SEL				78
#define CLKID_PWM_E_DIV				79
#define CLKID_PWM_E				80
#define CLKID_PWM_F_SEL				81
#define CLKID_PWM_F_DIV				82
#define CLKID_PWM_F				83
#define CLKID_PWM_G_SEL				84
#define CLKID_PWM_G_DIV				85
#define CLKID_PWM_G				86
#define CLKID_PWM_H_SEL				87
#define CLKID_PWM_H_DIV				88
#define CLKID_PWM_H				89
#define CLKID_SPICC_0_SEL			90
#define CLKID_SPICC_0_DIV			91
#define CLKID_SPICC_0				92
#define CLKID_SPICC_1_SEL			93
#define CLKID_SPICC_1_DIV			94
#define CLKID_SPICC_1				95
#define CLKID_SD_EMMC_A_SEL			96
#define CLKID_SD_EMMC_A_DIV			97
#define CLKID_SD_EMMC_A				98
#define CLKID_SD_EMMC_C_SEL			99
#define CLKID_SD_EMMC_C_DIV			100
#define CLKID_SD_EMMC_C				101
#define CLKID_TS_DIV				102
#define CLKID_TS				103
#define CLKID_ETH_125M_DIV			104
#define CLKID_ETH_125M				105
#define CLKID_ETH_RMII_DIV			106
#define CLKID_ETH_RMII				107
#define CLKID_DSPA_0_SEL			108
#define CLKID_DSPA_0_DIV			109
#define CLKID_DSPA_0				110
#define CLKID_DSPA_1_SEL			111
#define CLKID_DSPA_1_DIV			112
#define CLKID_DSPA_1				113
#define CLKID_DSPA				114
#define CLKID_NNA_CORE_SEL			115
#define CLKID_NNA_CORE_DIV			116
#define CLKID_NNA_CORE				117
#define CLKID_NNA_AXI_SEL			118
#define CLKID_NNA_AXI_DIV			119
#define CLKID_NNA_AXI				120

#endif  /* _DT_BINDINGS_CLOCK_AMLOGIC_A5_PERIPHERALS_CLKC_H */
