/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (C) 2024 Mobileye Vision Technologies Ltd.
 */

#ifndef _DT_BINDINGS_CLOCK_MOBILEYE_EYEQ_CLK_H
#define _DT_BINDINGS_CLOCK_MOBILEYE_EYEQ_CLK_H

#define EQ5C_PLL_CPU		0
#define EQ5C_PLL_VMP		1
#define EQ5C_PLL_PMA		2
#define EQ5C_PLL_VDI		3
#define EQ5C_PLL_DDR0		4
#define EQ5C_PLL_PCI		5
#define EQ5C_PLL_PER		6
#define EQ5C_PLL_PMAC		7
#define EQ5C_PLL_MPC		8
#define EQ5C_PLL_DDR1		9

#define EQ5C_DIV_OSPI		10

/* EQ5C_PLL_CPU children */
#define EQ5C_CPU_CORE0		11
#define EQ5C_CPU_CORE1		12
#define EQ5C_CPU_CORE2		13
#define EQ5C_CPU_CORE3		14

/* EQ5C_PLL_PER children */
#define EQ5C_PER_OCC		15
#define EQ5C_PER_UART		16
#define EQ5C_PER_SPI		17
#define EQ5C_PER_I2C		18
#define EQ5C_PER_GPIO		19
#define EQ5C_PER_EMMC		20
#define EQ5C_PER_OCC_PCI	21

#define EQ6LC_PLL_DDR		0
#define EQ6LC_PLL_CPU		1
#define EQ6LC_PLL_PER		2
#define EQ6LC_PLL_VDI		3

#define EQ6HC_CENTRAL_PLL_CPU	0
#define EQ6HC_CENTRAL_CPU_OCC	1

#define EQ6HC_WEST_PLL_PER	0
#define EQ6HC_WEST_PER_OCC	1
#define EQ6HC_WEST_PER_UART	2

#define EQ6HC_SOUTH_PLL_VDI		0
#define EQ6HC_SOUTH_PLL_PCIE		1
#define EQ6HC_SOUTH_PLL_PER		2
#define EQ6HC_SOUTH_PLL_ISP		3

#define EQ6HC_SOUTH_DIV_EMMC		4
#define EQ6HC_SOUTH_DIV_OSPI_REF	5
#define EQ6HC_SOUTH_DIV_OSPI_SYS	6
#define EQ6HC_SOUTH_DIV_TSU		7

#define EQ6HC_ACC_PLL_XNN		0
#define EQ6HC_ACC_PLL_VMP		1
#define EQ6HC_ACC_PLL_PMA		2
#define EQ6HC_ACC_PLL_MPC		3
#define EQ6HC_ACC_PLL_NOC		4

#define EQ7HC_SOUTH_PLL_XSPI	0
#define EQ7HC_SOUTH_PLL_VDIO	1
#define EQ7HC_SOUTH_PLL_PER	2
#define EQ7HC_SOUTH_PLL_100P0	3

#define EQ7HC_SOUTH_DIV_VDO_DSI_SYS	4
#define EQ7HC_SOUTH_DIV_PMA_CMN_REF	5
#define EQ7HC_SOUTH_DIV_REF_UFS		6
#define EQ7HC_SOUTH_DIV_REF_100P0	7
#define EQ7HC_SOUTH_DIV_XSPI_SYS	8
#define EQ7HC_SOUTH_DIV_XSPI_MBITS	9
#define EQ7HC_SOUTH_DIV_NOC_S		10
#define EQ7HC_SOUTH_DIV_PCIE_SYS	11
#define EQ7HC_SOUTH_DIV_PCIE_SYS_MBITS	12
#define EQ7HC_SOUTH_DIV_PCIE_GBE_PHY	13
#define EQ7HC_SOUTH_DIV_UFS_CORE	14
#define EQ7HC_SOUTH_DIV_UFS_SMS		15
#define EQ7HC_SOUTH_DIV_UFS_ROM_SMS	16
#define EQ7HC_SOUTH_DIV_ETH_SYS		17
#define EQ7HC_SOUTH_DIV_ETH_MBITS	18
#define EQ7HC_SOUTH_DIV_CFG_S		19
#define EQ7HC_SOUTH_DIV_TSU		20
#define EQ7HC_SOUTH_DIV_VDIO		21
#define EQ7HC_SOUTH_DIV_VDIO_CORE	22
#define EQ7HC_SOUTH_DIV_VDIO_CORE_MBIT	23
#define EQ7HC_SOUTH_DIV_VDO_CORE_MBITS	24
#define EQ7HC_SOUTH_DIV_VDO_P		25
#define EQ7HC_SOUTH_DIV_VDIO_CFG	26
#define EQ7HC_SOUTH_DIV_VDIO_TXCLKESC	27

#define EQ7HC_EAST_PLL_106P6	0
#define EQ7HC_EAST_PLL_NOC	1
#define EQ7HC_EAST_PLL_ISP	2
#define EQ7HC_EAST_PLL_VEU	3

#define EQ7HC_EAST_DIV_REF_DDR_PHY	4
#define EQ7HC_EAST_DIV_REF_106P6	5
#define EQ7HC_EAST_DIV_CORE		6
#define EQ7HC_EAST_DIV_CORE_MBITS	7
#define EQ7HC_EAST_DIV_ISRAM_MBITS	8
#define EQ7HC_EAST_DIV_CFG		9
#define EQ7HC_EAST_DIV_VEU_CORE		10
#define EQ7HC_EAST_DIV_VEU_MBITS	11
#define EQ7HC_EAST_DIV_VEU_OCP		12
#define EQ7HC_EAST_DIV_LBITS		13
#define EQ7HC_EAST_DIV_ISP0_CORE	14

#define EQ7HC_WEST_PLL_106P6	0
#define EQ7HC_WEST_PLL_NOC	1
#define EQ7HC_WEST_PLL_GPU	2
#define EQ7HC_WEST_PLL_SSI	3

#define EQ7HC_WEST_DIV_GPU		4
#define EQ7HC_WEST_DIV_GPU_MBITS	5
#define EQ7HC_WEST_DIV_LBITS		6
#define EQ7HC_WEST_DIV_MIPS_TIMER	7
#define EQ7HC_WEST_DIV_SSI_CORE		8
#define EQ7HC_WEST_DIV_SSI_CORE_MBITS	9
#define EQ7HC_WEST_DIV_SSI_ROM		10
#define EQ7HC_WEST_DIV_SSI_ROM_MBITS	11
#define EQ7HC_WEST_DIV_REF_DDR_PHY	12
#define EQ7HC_WEST_DIV_REF_106P6	13
#define EQ7HC_WEST_DIV_CORE		14
#define EQ7HC_WEST_DIV_CORE_MBIT	15
#define EQ7HC_WEST_DIV_CFG		16
#define EQ7HC_WEST_DIV_CAU		17
#define EQ7HC_WEST_DIV_CAU_MBITS	18

#define EQ7HC_PERIPH_EAST_PLL_PER	0

#define EQ7HC_PERIPH_EAST_DIV_PER	1

#define EQ7HC_PERIPH_WEST_PLL_PER	0
#define EQ7HC_PERIPH_WEST_PLL_I2S	1

#define EQ7HC_PERIPH_WEST_DIV_PER	2
#define EQ7HC_PERIPH_WEST_DIV_I2S	3

#define EQ7HC_DDR_PLL		0

#define EQ7HC_DDR_DIV_APB	1
#define EQ7HC_DDR_DIV_PLLREF	2
#define EQ7HC_DDR_DIV_DFI	3

#define EQ7HC_MIPS_PLL_CPU	0

#define EQ7HC_MIPS_DIV_CM	1

#define EQ7HC_ACC_PLL_VMP	0
#define EQ7HC_ACC_PLL_MPC	1
#define EQ7HC_ACC_PLL_PMA	2
#define EQ7HC_ACC_PLL_NOC	3

#define EQ7HC_ACC_DIV_PMA	4
#define EQ7HC_ACC_DIV_NCORE	5
#define EQ7HC_ACC_DIV_CFG	6

#define EQ7HC_XNN_PLL_XNN0	0
#define EQ7HC_XNN_PLL_XNN1	1
#define EQ7HC_XNN_PLL_XNN2	2
#define EQ7HC_XNN_PLL_CLSTR	3

#define EQ7HC_XNN_DIV_XNN0	4
#define EQ7HC_XNN_DIV_XNN1	5
#define EQ7HC_XNN_DIV_XNN2	6
#define EQ7HC_XNN_DIV_CLSTR	7
#define EQ7HC_XNN_DIV_I2	8
#define EQ7HC_XNN_DIV_I2_SMS	9
#define EQ7HC_XNN_DIV_CFG	10

#endif
