// SPDX-License-Identifier: GPL-2.0

// Copyright (C) 2024 Google LLC.

//! Miscdevice support.
//!
//! C headers: [`include/linux/miscdevice.h`](srctree/include/linux/miscdevice.h).
//!
//! Reference: <https://www.kernel.org/doc/html/latest/driver-api/misc_devices.html>

use crate::{
    alloc::KBox,
    bindings, container_of,
    device::Device,
    error::{to_result, Error, Result, VTABLE_DEFAULT_ERROR},
    ffi::{c_int, c_long, c_uint, c_ulong},
    fs::{File, Kiocb},
    iov::{IovIterDest, IovIterSource},
    mm::virt::VmaNew,
    prelude::*,
    seq_file::SeqFile,
    sync::aref::ARef,
    types::{ForeignOwnable, Opaque, ScopeGuard},
};
use core::{
    marker::{PhantomData, PhantomPinned},
    pin::Pin,
    ptr::drop_in_place,
    sync::atomic::{AtomicBool, Ordering},
};

/// Options for creating a misc device.
#[derive(Copy, Clone)]
pub struct MiscDeviceOptions {
    /// The name of the miscdevice.
    pub name: &'static CStr,
}

impl MiscDeviceOptions {
    /// Create a raw `struct miscdev` ready for registration.
    pub fn into_raw<T: MiscDeviceVTable + 'static>(self) -> bindings::miscdevice {
        let mut result: bindings::miscdevice = pin_init::zeroed();
        result.minor = bindings::MISC_DYNAMIC_MINOR as ffi::c_int;
        result.name = crate::str::as_char_ptr_in_const_context(self.name);
        result.fops = T::file_operations();
        result
    }
}

/// Generates the `MiscDeviceVTable` implementation for a concrete miscdevice type.
///
/// Place this macro after `impl MiscDevice for ...`.
///
/// The generated implementation always binds `file_operations.owner` to the current module's
/// `THIS_MODULE`, so safe drivers cannot accidentally publish owner-less or foreign-owned misc
/// device callbacks.
#[macro_export]
macro_rules! declare_misc_device_fops {
    ($type:ty) => {
        // SAFETY: This implements the standard Rust miscdevice vtable generated by
        // `build_file_operations()`, which wires up owner/module pinning and the private-data
        // protocol enforced by this abstraction.
        unsafe impl $crate::miscdevice::MiscDeviceVTable for $type {
            fn file_operations() -> &'static $crate::bindings::file_operations {
                struct AssertSync<T>(T);
                // SAFETY: This wrapper is only used for immutable `file_operations` tables stored
                // in a `static`.
                unsafe impl<T> Sync for AssertSync<T> {}

                static FOPS: AssertSync<$crate::bindings::file_operations> = AssertSync(
                    $crate::miscdevice::build_file_operations::<$type>(THIS_MODULE.as_ptr()),
                );

                &FOPS.0
            }
        }
    };
}

#[repr(C)]
struct RegistrationBacking<T: MiscDevice + 'static> {
    misc: Opaque<bindings::miscdevice>,
    data: T::RegistrationData,
    owner: *const MiscDeviceRegistration<T>,
    registered: AtomicBool,
}

struct OpenFile<T: MiscDevice + 'static> {
    data: *mut ffi::c_void,
    _t: PhantomData<T>,
}

impl<T: MiscDevice + 'static> OpenFile<T> {
    fn empty() -> Self {
        Self {
            data: core::ptr::null_mut(),
            _t: PhantomData,
        }
    }

    fn borrow(&self) -> <T::Ptr as ForeignOwnable>::Borrowed<'_> {
        // SAFETY: `self.data` comes from `T::Ptr::into_foreign()` and is only converted back in
        // `release`, after all borrows from this file operation callback have ended.
        unsafe { <T::Ptr as ForeignOwnable>::borrow(self.data) }
    }
}

/// A registration of a miscdevice.
///
/// # Invariants
///
/// - `backing.misc` contains a valid `struct miscdevice` created using
///   [`MiscDeviceOptions::into_raw`].
/// - When `backing.registered` is `true`, `backing.misc` is registered using
///   `misc_register()`.
/// - Before `misc_register()` publishes `backing.misc`, every field reachable through the safe
///   open context (`backing.data` and `backing.owner`) is fully initialized.
/// - `backing.owner` points back to this wrapper for the entire time the miscdevice is registered.
/// - Deregistration occurs at most once, either via [`MiscDeviceRegistration::deregister`] or
///   [`Drop`].
#[pin_data(PinnedDrop)]
pub struct MiscDeviceRegistration<T: MiscDevice + 'static> {
    backing: KBox<RegistrationBacking<T>>,
    #[pin]
    _pin: PhantomPinned,
    _t: PhantomData<T>,
}

// SAFETY: It is allowed to call `misc_deregister` on a different thread from where you called
// `misc_register`.
unsafe impl<T: MiscDevice> Send for MiscDeviceRegistration<T> {}
// SAFETY: All `&self` methods on this type are written to ensure that it is safe to call them in
// parallel.
unsafe impl<T: MiscDevice> Sync for MiscDeviceRegistration<T> {}

impl<T: MiscDevice + 'static> MiscDeviceRegistration<T> {
    /// Register a misc device.
    pub fn register(opts: MiscDeviceOptions) -> impl PinInit<Self, Error>
    where
        T: MiscDevice<RegistrationData = ()> + MiscDeviceVTable,
    {
        Self::register_with_data(opts, ())
    }

    /// Register a misc device together with driver-defined registration data.
    pub fn register_with_data(
        opts: MiscDeviceOptions,
        data: T::RegistrationData,
    ) -> impl PinInit<Self, Error>
    where
        T: MiscDeviceVTable,
    {
        let init = move |slot: *mut Self| {
            let backing = KBox::new(
                RegistrationBacking {
                    misc: Opaque::new(opts.into_raw::<T>()),
                    data,
                    owner: slot.cast_const(),
                    registered: AtomicBool::new(false),
                },
                GFP_KERNEL,
            )?;

            // SAFETY: `slot` is valid for writes for the duration of this initializer.
            unsafe {
                slot.write(Self {
                    backing,
                    _pin: PhantomPinned,
                    _t: PhantomData,
                })
            };

            // SAFETY: `slot` points to the fully-initialized registration wrapper we just wrote
            // above.
            let this = unsafe { &mut *slot };
            // SAFETY: `this.as_raw()` points at the fully initialized `struct miscdevice`
            // contained in the heap-backed registration backing.
            let ret = to_result(unsafe { bindings::misc_register(this.as_raw()) });
            if let Err(err) = ret {
                // SAFETY: The wrapper was fully initialized above, so dropping it here correctly
                // releases the heap-backed registration backing.
                unsafe { drop_in_place(slot) };
                return Err(err);
            }

            this.backing.registered.store(true, Ordering::Release);
            Ok(())
        };

        // SAFETY:
        // - On success, the closure writes a fully-initialized `Self` into `slot` before making
        //   the miscdevice visible via `misc_register()`. All state observable through the safe
        //   open context is initialized before publication.
        // - On failure after the write, it drops the initialized value before returning.
        unsafe { pin_init::pin_init_from_closure(init) }
    }

    /// Returns the registration wrapper for a raw `struct miscdevice` pointer.
    ///
    /// # Safety
    ///
    /// `misc` must point at the `misc` field of a live [`RegistrationBacking<T>`].
    unsafe fn from_raw_misc<'a>(misc: *mut bindings::miscdevice) -> &'a Self {
        // SAFETY: The caller guarantees that `misc` points at the `misc` field of a live
        // `RegistrationBacking<T>`, whose `owner` points back to the live registration wrapper.
        let backing =
            unsafe { &*container_of!(Opaque::cast_from(misc), RegistrationBacking<T>, misc) };
        // SAFETY: By the type invariant, `owner` points at the live wrapper that owns `backing`.
        unsafe { &*backing.owner }
    }

    /// Returns a raw pointer to the misc device.
    pub fn as_raw(&self) -> *mut bindings::miscdevice {
        self.backing.misc.get()
    }

    /// Returns the registration data that was supplied at registration time.
    pub fn data(&self) -> &T::RegistrationData {
        &self.backing.data
    }

    fn deregister_inner(backing: &RegistrationBacking<T>) {
        if backing.registered.swap(false, Ordering::AcqRel) {
            // SAFETY: `registered == true` guarantees that the miscdevice was successfully
            // registered and has not been deregistered yet.
            unsafe { bindings::misc_deregister(backing.misc.get()) };
        }
    }

    /// Deregister this misc device if it is still registered.
    ///
    /// After this returns, the misc core will no longer route new opens to [`MiscDevice::open`].
    /// Existing open files keep their own pinned `file_operations` table and private data and must
    /// be drained by the driver before it tears down device-side resources that those file handles
    /// still own.
    pub fn deregister(&self) {
        Self::deregister_inner(&self.backing);
    }
}

#[pinned_drop]
impl<T: MiscDevice + 'static> PinnedDrop for MiscDeviceRegistration<T> {
    fn drop(self: Pin<&mut Self>) {
        let this = self.project();
        Self::deregister_inner(this.backing);
    }
}

/// Publication-safe context passed to [`MiscDevice::open`].
pub struct MiscDeviceOpenContext<'a, T: MiscDevice + 'static> {
    registration: &'a MiscDeviceRegistration<T>,
    device: ARef<Device>,
}

impl<'a, T: MiscDevice + 'static> MiscDeviceOpenContext<'a, T> {
    /// Returns the registration data supplied at registration time.
    pub fn data(&self) -> &T::RegistrationData {
        self.registration.data()
    }

    /// Returns the class device backing this miscdevice open.
    pub fn device(&self) -> ARef<Device> {
        self.device.clone()
    }
}

/// Internal trait that supplies the concrete `file_operations` table used for a Rust miscdevice.
///
/// # Safety
///
/// Implementations must return a stable `file_operations` table produced by this abstraction so
/// that owner/module pinning and the private-data protocol remain intact. Drivers should use
/// [`declare_misc_device_fops!`] instead of implementing this trait manually.
#[doc(hidden)]
pub unsafe trait MiscDeviceVTable: MiscDevice + 'static {
    /// Returns the `file_operations` table for this miscdevice implementation.
    fn file_operations() -> &'static bindings::file_operations;
}

/// Trait implemented by the private data of an open misc device.
#[vtable]
pub trait MiscDevice: Sized {
    /// What kind of pointer should `Self` be wrapped in.
    type Ptr: ForeignOwnable + Send + Sync;

    /// Driver-defined data stored in the miscdevice registration.
    type RegistrationData: Send + Sync + 'static;

    /// Called when the misc device is opened.
    ///
    /// The returned pointer will be stored as the private data for the file.
    fn open(_file: &File, _ctx: &MiscDeviceOpenContext<'_, Self>) -> Result<Self::Ptr>;

    /// Called when the misc device is released.
    fn release(device: Self::Ptr, _file: &File) {
        drop(device);
    }

    /// Handle for mmap.
    ///
    /// This function is invoked when a user space process invokes the `mmap` system call on
    /// `file`. The function is a callback that is part of the VMA initializer. The kernel will do
    /// initial setup of the VMA before calling this function. The function can then interact with
    /// the VMA initialization by calling methods of `vma`. If the function does not return an
    /// error, the kernel will complete initialization of the VMA according to the properties of
    /// `vma`.
    fn mmap(
        _device: <Self::Ptr as ForeignOwnable>::Borrowed<'_>,
        _file: &File,
        _vma: &VmaNew,
    ) -> Result {
        build_error!(VTABLE_DEFAULT_ERROR)
    }

    /// Read from this miscdevice.
    fn read_iter(_kiocb: Kiocb<'_, Self::Ptr>, _iov: &mut IovIterDest<'_>) -> Result<usize> {
        build_error!(VTABLE_DEFAULT_ERROR)
    }

    /// Write to this miscdevice.
    fn write_iter(_kiocb: Kiocb<'_, Self::Ptr>, _iov: &mut IovIterSource<'_>) -> Result<usize> {
        build_error!(VTABLE_DEFAULT_ERROR)
    }

    /// Handler for ioctls.
    ///
    /// The `cmd` argument is usually manipulated using the utilities in [`kernel::ioctl`].
    ///
    /// [`kernel::ioctl`]: mod@crate::ioctl
    fn ioctl(
        _device: <Self::Ptr as ForeignOwnable>::Borrowed<'_>,
        _file: &File,
        _cmd: u32,
        _arg: usize,
    ) -> Result<isize> {
        build_error!(VTABLE_DEFAULT_ERROR)
    }

    /// Handler for ioctls.
    ///
    /// Used for 32-bit userspace on 64-bit platforms.
    ///
    /// This method is optional and only needs to be provided if the ioctl relies on structures
    /// that have different layout on 32-bit and 64-bit userspace. If no implementation is
    /// provided, then `compat_ptr_ioctl` will be used instead.
    #[cfg(CONFIG_COMPAT)]
    fn compat_ioctl(
        _device: <Self::Ptr as ForeignOwnable>::Borrowed<'_>,
        _file: &File,
        _cmd: u32,
        _arg: usize,
    ) -> Result<isize> {
        build_error!(VTABLE_DEFAULT_ERROR)
    }

    /// Show info for this fd.
    fn show_fdinfo(
        _device: <Self::Ptr as ForeignOwnable>::Borrowed<'_>,
        _m: &SeqFile,
        _file: &File,
    ) {
        build_error!(VTABLE_DEFAULT_ERROR)
    }
}

/// A vtable for the file operations of a Rust miscdevice.
struct MiscdeviceVTable<T: MiscDevice>(PhantomData<T>);

impl<T: MiscDevice + 'static> MiscdeviceVTable<T> {
    const fn build(owner: *mut bindings::module) -> bindings::file_operations {
        bindings::file_operations {
            owner,
            open: Some(Self::open),
            release: Some(Self::release),
            mmap: if T::HAS_MMAP { Some(Self::mmap) } else { None },
            read_iter: if T::HAS_READ_ITER {
                Some(Self::read_iter)
            } else {
                None
            },
            write_iter: if T::HAS_WRITE_ITER {
                Some(Self::write_iter)
            } else {
                None
            },
            unlocked_ioctl: if T::HAS_IOCTL {
                Some(Self::ioctl)
            } else {
                None
            },
            #[cfg(CONFIG_COMPAT)]
            compat_ioctl: if T::HAS_COMPAT_IOCTL {
                Some(Self::compat_ioctl)
            } else if T::HAS_IOCTL {
                bindings::compat_ptr_ioctl
            } else {
                None
            },
            show_fdinfo: if T::HAS_SHOW_FDINFO {
                Some(Self::show_fdinfo)
            } else {
                None
            },
            ..pin_init::zeroed()
        }
    }

    /// # Safety
    ///
    /// `file` and `inode` must be the file and inode for a file that is undergoing initialization.
    /// The file must be associated with a `MiscDeviceRegistration<T>`.
    unsafe extern "C" fn open(inode: *mut bindings::inode, raw_file: *mut bindings::file) -> c_int {
        // SAFETY: The pointers are valid and for a file being opened.
        let ret = unsafe { bindings::generic_file_open(inode, raw_file) };
        if ret != 0 {
            return ret;
        }

        // SAFETY: The open call of a file can access the private data.
        let misc_ptr = unsafe { (*raw_file).private_data };

        // SAFETY: This is a miscdevice, so `misc_open()` set the private data to a pointer to the
        // associated `struct miscdevice` before calling into this method. Furthermore,
        // `misc_open()` ensures that the miscdevice can't be unregistered and freed during this
        // call to `fops_open`.
        let misc = unsafe { MiscDeviceRegistration::<T>::from_raw_misc(misc_ptr.cast()) };

        // SAFETY:
        // * This underlying file is valid for (much longer than) the duration of `T::open`.
        // * There is no active fdget_pos region on the file on this thread.
        let file = unsafe { File::from_raw_file(raw_file) };

        // SAFETY: `misc_open()` serializes with `misc_deregister()` via `misc_mtx`, so the class
        // device remains live for the duration of this callback. Taking an extra reference here
        // lets the safe open context own the device independently from later teardown.
        let ctx = MiscDeviceOpenContext {
            registration: misc,
            device: unsafe { Device::get_device((*misc.as_raw()).this_device) },
        };

        let ptr = match T::open(file, &ctx) {
            Ok(ptr) => ptr,
            Err(err) => return err.to_errno(),
        };
        let ptr = ScopeGuard::new_with_data(ptr, |ptr| T::release(ptr, file));

        let mut open_file = match KBox::new(OpenFile::<T>::empty(), GFP_KERNEL) {
            Ok(open_file) => open_file,
            Err(_) => return ENOMEM.to_errno(),
        };
        open_file.data = ptr.dismiss().into_foreign();

        // This overwrites the private data with a small Rust-owned wrapper that keeps the module
        // pinned for the full file lifetime and owns the driver's foreign private data handle.
        //
        // SAFETY: The open call of a file can access the private data.
        unsafe { (*raw_file).private_data = open_file.into_foreign() };

        0
    }

    /// # Safety
    ///
    /// `file` and `inode` must be the file and inode for a file that is being released. The file
    /// must be associated with a `MiscDeviceRegistration<T>`.
    unsafe extern "C" fn release(_inode: *mut bindings::inode, file: *mut bindings::file) -> c_int {
        // SAFETY: The release call of a file owns the private data.
        let open_file =
            unsafe { <KBox<OpenFile<T>> as ForeignOwnable>::from_foreign((*file).private_data) };
        let data = open_file.data;

        // SAFETY:
        // * The file is valid for the duration of this call.
        // * There is no active fdget_pos region on the file on this thread.
        T::release(
            unsafe { <T::Ptr as ForeignOwnable>::from_foreign(data) },
            unsafe { File::from_raw_file(file) },
        );

        0
    }

    /// # Safety
    ///
    /// `kiocb` must be correspond to a valid file that is associated with a
    /// `MiscDeviceRegistration<T>`. `iter` must be a valid `struct iov_iter` for writing.
    unsafe extern "C" fn read_iter(
        kiocb: *mut bindings::kiocb,
        iter: *mut bindings::iov_iter,
    ) -> isize {
        // SAFETY: The caller provides a valid `struct kiocb` associated with a
        // `MiscDeviceRegistration<T>` file.
        let kiocb = unsafe { Kiocb::from_raw(kiocb) };
        // SAFETY: This is a valid `struct iov_iter` for writing.
        let iov = unsafe { IovIterDest::from_raw(iter) };

        match T::read_iter(kiocb, iov) {
            Ok(res) => res as isize,
            Err(err) => err.to_errno() as isize,
        }
    }

    /// # Safety
    ///
    /// `kiocb` must be correspond to a valid file that is associated with a
    /// `MiscDeviceRegistration<T>`. `iter` must be a valid `struct iov_iter` for writing.
    unsafe extern "C" fn write_iter(
        kiocb: *mut bindings::kiocb,
        iter: *mut bindings::iov_iter,
    ) -> isize {
        // SAFETY: The caller provides a valid `struct kiocb` associated with a
        // `MiscDeviceRegistration<T>` file.
        let kiocb = unsafe { Kiocb::from_raw(kiocb) };
        // SAFETY: This is a valid `struct iov_iter` for reading.
        let iov = unsafe { IovIterSource::from_raw(iter) };

        match T::write_iter(kiocb, iov) {
            Ok(res) => res as isize,
            Err(err) => err.to_errno() as isize,
        }
    }

    /// # Safety
    ///
    /// `file` must be a valid file that is associated with a `MiscDeviceRegistration<T>`.
    /// `vma` must be a vma that is currently being mmap'ed with this file.
    unsafe extern "C" fn mmap(
        file: *mut bindings::file,
        vma: *mut bindings::vm_area_struct,
    ) -> c_int {
        // SAFETY: The mmap call of a file can access the private data.
        let open_file =
            unsafe { <KBox<OpenFile<T>> as ForeignOwnable>::borrow((*file).private_data) };
        let device = open_file.borrow();
        // SAFETY: The caller provides a vma that is undergoing initial VMA setup.
        let area = unsafe { VmaNew::from_raw(vma) };
        // SAFETY:
        // * The file is valid for the duration of this call.
        // * There is no active fdget_pos region on the file on this thread.
        let file = unsafe { File::from_raw_file(file) };

        match T::mmap(device, file, area) {
            Ok(()) => 0,
            Err(err) => err.to_errno(),
        }
    }

    /// # Safety
    ///
    /// `file` must be a valid file that is associated with a `MiscDeviceRegistration<T>`.
    unsafe extern "C" fn ioctl(file: *mut bindings::file, cmd: c_uint, arg: c_ulong) -> c_long {
        // SAFETY: The ioctl call of a file can access the private data.
        let open_file =
            unsafe { <KBox<OpenFile<T>> as ForeignOwnable>::borrow((*file).private_data) };
        let device = open_file.borrow();

        // SAFETY:
        // * The file is valid for the duration of this call.
        // * There is no active fdget_pos region on the file on this thread.
        let file = unsafe { File::from_raw_file(file) };

        match T::ioctl(device, file, cmd, arg) {
            Ok(ret) => ret as c_long,
            Err(err) => err.to_errno() as c_long,
        }
    }

    /// # Safety
    ///
    /// `file` must be a valid file that is associated with a `MiscDeviceRegistration<T>`.
    #[cfg(CONFIG_COMPAT)]
    unsafe extern "C" fn compat_ioctl(
        file: *mut bindings::file,
        cmd: c_uint,
        arg: c_ulong,
    ) -> c_long {
        // SAFETY: The compat ioctl call of a file can access the private data.
        let open_file =
            unsafe { <KBox<OpenFile<T>> as ForeignOwnable>::borrow((*file).private_data) };
        let device = open_file.borrow();

        // SAFETY:
        // * The file is valid for the duration of this call.
        // * There is no active fdget_pos region on the file on this thread.
        let file = unsafe { File::from_raw_file(file) };

        match T::compat_ioctl(device, file, cmd, arg) {
            Ok(ret) => ret as c_long,
            Err(err) => err.to_errno() as c_long,
        }
    }

    /// # Safety
    ///
    /// - `file` must be a valid file that is associated with a `MiscDeviceRegistration<T>`.
    /// - `seq_file` must be a valid `struct seq_file` that we can write to.
    unsafe extern "C" fn show_fdinfo(seq_file: *mut bindings::seq_file, file: *mut bindings::file) {
        // SAFETY: The release call of a file owns the private data.
        let open_file =
            unsafe { <KBox<OpenFile<T>> as ForeignOwnable>::borrow((*file).private_data) };
        let device = open_file.borrow();
        // SAFETY:
        // * The file is valid for the duration of this call.
        // * There is no active fdget_pos region on the file on this thread.
        let file = unsafe { File::from_raw_file(file) };
        // SAFETY: The caller ensures that the pointer is valid and exclusive for the duration in
        // which this method is called.
        let m = unsafe { SeqFile::from_raw(seq_file) };

        T::show_fdinfo(device, m, file);
    }
}

#[doc(hidden)]
pub const fn build_file_operations<T: MiscDevice + 'static>(
    owner: *mut bindings::module,
) -> bindings::file_operations {
    MiscdeviceVTable::<T>::build(owner)
}
