/* SPDX-License-Identifier: GPL-2.0 */
/*
 * mt8196-audsys-clkid.h  --  MediaTek 8196 audsys clock id definition
 *
 * Copyright (c) 2025 MediaTek Inc.
 * Author: Darren Ye <darren.ye@mediatek.com>
 */

#ifndef _MT8196_AUDSYS_CLKID_H_
#define _MT8196_AUDSYS_CLKID_H_

enum{
	/* AFE */
	CLK_AFE_PCM1,
	CLK_AFE_PCM0,
	CLK_AFE_CM2,
	CLK_AFE_CM1,
	CLK_AFE_CM0,
	CLK_AFE_STF,
	CLK_AFE_HW_GAIN23,
	CLK_AFE_HW_GAIN01,
	CLK_AFE_FM_I2S,
	CLK_AFE_MTKAIFV4,
	CLK_AFE_UL2_ADC_HIRES_TML,
	CLK_AFE_UL2_ADC_HIRES,
	CLK_AFE_UL2_TML,
	CLK_AFE_UL2_ADC,
	CLK_AFE_UL1_ADC_HIRES_TML,
	CLK_AFE_UL1_ADC_HIRES,
	CLK_AFE_UL1_TML,
	CLK_AFE_UL1_ADC,
	CLK_AFE_UL0_ADC_HIRES_TML,
	CLK_AFE_UL0_ADC_HIRES,
	CLK_AFE_UL0_TML,
	CLK_AFE_UL0_ADC,
	CLK_AFE_ETDM_IN6,
	CLK_AFE_ETDM_IN5,
	CLK_AFE_ETDM_IN4,
	CLK_AFE_ETDM_IN3,
	CLK_AFE_ETDM_IN2,
	CLK_AFE_ETDM_IN1,
	CLK_AFE_ETDM_IN0,
	CLK_AFE_ETDM_OUT6,
	CLK_AFE_ETDM_OUT5,
	CLK_AFE_ETDM_OUT4,
	CLK_AFE_ETDM_OUT3,
	CLK_AFE_ETDM_OUT2,
	CLK_AFE_ETDM_OUT1,
	CLK_AFE_ETDM_OUT0,
	CLK_AFE_TDM_OUT,
	CLK_AFE_GENERAL15_ASRC,
	CLK_AFE_GENERAL14_ASRC,
	CLK_AFE_GENERAL13_ASRC,
	CLK_AFE_GENERAL12_ASRC,
	CLK_AFE_GENERAL11_ASRC,
	CLK_AFE_GENERAL10_ASRC,
	CLK_AFE_GENERAL9_ASRC,
	CLK_AFE_GENERAL8_ASRC,
	CLK_AFE_GENERAL7_ASRC,
	CLK_AFE_GENERAL6_ASRC,
	CLK_AFE_GENERAL5_ASRC,
	CLK_AFE_GENERAL4_ASRC,
	CLK_AFE_GENERAL3_ASRC,
	CLK_AFE_GENERAL2_ASRC,
	CLK_AFE_GENERAL1_ASRC,
	CLK_AFE_GENERAL0_ASRC,
	CLK_AFE_CONNSYS_I2S_ASRC,
	CLK_AFE_AUDIO_HOPPING,
	CLK_AFE_AUDIO_F26M,
	CLK_AFE_APLL1,
	CLK_AFE_APLL2,
	CLK_AFE_H208M,
	CLK_AFE_APLL_TUNER2,
	CLK_AFE_APLL_TUNER1,
	CLK_AFE_NR_CLK,
};

#endif
