/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2017, The Linux Foundation. All rights reserved.
 */

#ifndef QCOM_PHY_QMP_COMMON_H_
#define QCOM_PHY_QMP_COMMON_H_

#include <linux/clk-provider.h>
#include <linux/device.h>
#include <linux/of.h>

struct qmp_phy_init_tbl {
	unsigned int offset;
	unsigned int val;
	char *name;
	/*
	 * mask of lanes for which this register is written
	 * for cases when second lane needs different values
	 */
	u8 lane_mask;
};

#define QMP_PHY_INIT_CFG(o, v)		\
	{				\
		.offset = o,		\
		.val = v,		\
		.name = #o,		\
		.lane_mask = 0xff,	\
	}

#define QMP_PHY_INIT_CFG_LANE(o, v, l)	\
	{				\
		.offset = o,		\
		.val = v,		\
		.name = #o,		\
		.lane_mask = l,		\
	}

static inline void qmp_configure_lane(struct device *dev, void __iomem *base,
				      const struct qmp_phy_init_tbl tbl[],
				      int num, u8 lane_mask)
{
	int i;
	const struct qmp_phy_init_tbl *t = tbl;

	if (!t)
		return;

	for (i = 0; i < num; i++, t++) {
		if (!(t->lane_mask & lane_mask))
			continue;

		dev_dbg(dev, "Writing Reg: %s Offset: 0x%04x Val: 0x%02x\n",
			t->name, t->offset, t->val);
		writel(t->val, base + t->offset);
	}
}

static inline void qmp_configure(struct device *dev, void __iomem *base,
				 const struct qmp_phy_init_tbl tbl[], int num)
{
	qmp_configure_lane(dev, base, tbl, num, 0xff);
}

/*
 * Register a fixed rate pipe clock.
 *
 * The <s>_pipe_clksrc generated by PHY goes to the GCC that gate
 * controls it. The <s>_pipe_clk coming out of the GCC is requested
 * by the PHY driver for its operations.
 * We register the <s>_pipe_clksrc here. The gcc driver takes care
 * of assigning this <s>_pipe_clksrc as parent to <s>_pipe_clk.
 * Below picture shows this relationship.
 *
 *         +---------------+
 *         |   PHY block   |<<---------------------------------------+
 *         |               |                                         |
 *         |   +-------+   |                   +-----+               |
 *   I/P---^-->|  PLL  |---^--->pipe_clksrc--->| GCC |--->pipe_clk---+
 *    clk  |   +-------+   |                   +-----+
 *         +---------------+
 */
static inline struct clk_hw *devm_qmp_register_pipe_clock(struct device *dev,
							  struct device_node *np)
{
	const char *pname = NULL;
	char name[64];

	/* ignore if the property is not present */
	if (np)
		of_property_read_string(np, "clock-output-names", &pname);

	if (!pname) {
		snprintf(name, sizeof(name), "%s::pipe_clk", dev_name(dev));
		pname = name;
	}

	/* controllers using QMP phys use 125MHz pipe clock interface */
	return devm_clk_hw_register_fixed_rate(dev, pname, NULL, 0, 125000000);
}

static inline void qmp_clk_release_provider(void *res)
{
	of_clk_del_provider(res);
}

static inline int devm_qmp_register_pipe_clock_provider(struct device *dev,
							struct device_node *np)
{
	struct clk_hw *fixed;
	int ret;

	fixed = devm_qmp_register_pipe_clock(dev, np);
	if (IS_ERR(fixed))
		return PTR_ERR(fixed);

	ret = of_clk_add_hw_provider(np, of_clk_hw_simple_get, fixed);
	if (ret)
		return ret;

	/*
	 * Roll a devm action because the clock provider is the child node, but
	 * the child node is not actually a device.
	 */
	return devm_add_action_or_reset(dev, qmp_clk_release_provider, np);
}

#endif
