/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2026, The Linux Foundation. All rights reserved.
 */

#ifndef QCOM_PHY_QMP_QSERDES_TXRX_UFS_V8_H_
#define QCOM_PHY_QMP_QSERDES_TXRX_UFS_V8_H_

#define QSERDES_UFS_V8_TX_RES_CODE_LANE_OFFSET_TX		(0x34)
#define QSERDES_UFS_V8_TX_RES_CODE_LANE_OFFSET_RX		(0x38)
#define QSERDES_UFS_V8_TX_LANE_MODE_1				(0x80)
#define QSERDES_UFS_V8_RX_UCDR_FO_GAIN_RATE2			(0x1BC)
#define QSERDES_UFS_V8_RX_UCDR_FO_GAIN_RATE4			(0x1C4)
#define QSERDES_UFS_V8_RX_UCDR_SO_GAIN_RATE4			(0x1DC)
#define QSERDES_UFS_V8_RX_EQ_OFFSET_ADAPTOR_CNTRL1		(0x2C8)
#define QSERDES_UFS_V8_RX_UCDR_PI_CONTROLS			(0x1E4)
#define QSERDES_UFS_V8_RX_OFFSET_ADAPTOR_CNTRL3			(0x2D0)
#define QSERDES_UFS_V8_RX_UCDR_FASTLOCK_COUNT_HIGH_RATE4	(0x120)
#define QSERDES_UFS_V8_RX_UCDR_FASTLOCK_FO_GAIN_RATE4		(0xD4)
#define QSERDES_UFS_V8_RX_UCDR_FASTLOCK_SO_GAIN_RATE4		(0xEC)
#define QSERDES_UFS_V8_RX_VGA_CAL_MAN_VAL			(0x288)
#define QSERDES_UFS_V8_RX_EQU_ADAPTOR_CNTRL4			(0x2B0)
#define QSERDES_UFS_V8_RX_MODE_RATE_0_1_B4			(0x324)
#define QSERDES_UFS_V8_RX_MODE_RATE4_SA_B7			(0x3B4)
#define QSERDES_UFS_V8_RX_MODE_RATE4_SA_B9			(0x3BC)
#define QSERDES_UFS_V8_RX_MODE_RATE4_SB_B7			(0x3E0)
#define QSERDES_UFS_V8_RX_MODE_RATE4_SB_B9			(0x3E8)
#define QSERDES_UFS_V8_RX_MODE_RATE5_SA_B7			(0x40C)
#define QSERDES_UFS_V8_RX_MODE_RATE5_SA_B9			(0x414)
#define QSERDES_UFS_V8_RX_MODE_RATE5_SB_B7			(0x438)
#define QSERDES_UFS_V8_RX_MODE_RATE5_SB_B9			(0x440)
#define QSERDES_UFS_V8_RX_UCDR_SO_SATURATION			(0xF4)
#define QSERDES_UFS_V8_RX_TERM_BW_CTRL0				(0x1AC)
#define QSERDES_UFS_V8_RX_DLL0_FTUNE_CTRL			(0x498)
#define QSERDES_UFS_V8_RX_SIGDET_CAL_TRIM			(0x4d0)

#endif
