/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by xdrgen. Manual edits will be lost. */
/* XDR specification file: ../../Documentation/sunrpc/xdr/nfs4_2.x */
/* XDR specification modification time: Fri Jun 12 10:44:36 2026 */

#ifndef _LINUX_XDRGEN_NFS4_2_DEF_H
#define _LINUX_XDRGEN_NFS4_2_DEF_H

#include <linux/types.h>
#include <linux/sunrpc/xdrgen/_defs.h>

typedef bool fattr4_uncacheable_file_data;

enum { FATTR4_UNCACHEABLE_FILE_DATA = 87 };

#define NFS4_fattr4_uncacheable_file_data_sz \
	(XDR_bool)

#endif /* _LINUX_XDRGEN_NFS4_2_DEF_H */
