// SPDX-License-Identifier: GPL-2.0-only
/*
 * Landlock tests - Tested socket protocols definitions
 *
 * Copyright © 2025 Huawei Tech. Co., Ltd.
 */

/* Almost every protocol that can be used to create socket using create() method
 * of net_proto_family structure is tested (e.g. this method is used to
 * create socket with socket(2)).
 *
 * List of address families that are not tested:
 * - Protocol families requiring CAP_SYS_ADMIN or CAP_NET_RAW (eg. AF_PACKET,
 *   AF_CAIF).
 * - AF_SMC, AF_KMC, AF_XDP.
 * - AF_ASH, AF_SNA, AF_WANPIPE, AF_NETBEUI, AF_IPX, AF_DECNET, AF_ECONET
 *   and AF_IRDA are not implemented in kernel.
 * - AF_BRIDGE, AF_MPLS can't be used for creating sockets.
 * - AF_SECURITY - pseudo AF (Cf. socket.h).
 * - AF_IB is reserved by infiniband.
 */

/* Cf. unix_create */
PROTOCOL_VARIANT_ADD(UNIX, STREAM, 0);
PROTOCOL_VARIANT_ADD(UNIX, RAW, 0);
PROTOCOL_VARIANT_ADD(UNIX, DGRAM, 0);
PROTOCOL_VARIANT_ADD(UNIX, SEQPACKET, 0);

/* Cf. inet_create */
PROTOCOL_VARIANT_ADD(INET, STREAM, 0);
PROTOCOL_VARIANT_ADD(INET, STREAM, IPPROTO_TCP);
PROTOCOL_VARIANT_ADD(INET, DGRAM, 0);
PROTOCOL_VARIANT_ADD(INET, DGRAM, IPPROTO_UDP);
PROTOCOL_VARIANT_ADD_CAPS(INET, RAW, IPPROTO_TCP);
PROTOCOL_VARIANT_ADD(INET, SEQPACKET, IPPROTO_SCTP);
PROTOCOL_VARIANT_ADD(INET, STREAM, IPPROTO_MPTCP);

/* Cf. ax25_create */
PROTOCOL_VARIANT_ADD(AX25, DGRAM, 0);
PROTOCOL_VARIANT_ADD(AX25, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD_CAPS(AX25, RAW, 0);

/* Cf. atalk_create */
PROTOCOL_VARIANT_ADD_CAPS(APPLETALK, RAW, 0);
PROTOCOL_VARIANT_ADD(APPLETALK, DGRAM, 0);

/* Cf. nr_create */
PROTOCOL_VARIANT_ADD(NETROM, SEQPACKET, 0);

/* Cf. pvc_create */
PROTOCOL_VARIANT_ADD(ATMPVC, DGRAM, 0);
PROTOCOL_VARIANT_ADD(ATMPVC, RAW, 0);
PROTOCOL_VARIANT_ADD(ATMPVC, RDM, 0);
PROTOCOL_VARIANT_ADD(ATMPVC, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD(ATMPVC, DCCP, 0);
PROTOCOL_VARIANT_ADD(ATMPVC, PACKET, 0);

/* Cf. x25_create */
PROTOCOL_VARIANT_ADD(X25, SEQPACKET, 0);

/* Cf. inet6_create */
PROTOCOL_VARIANT_ADD(INET6, STREAM, 0);
PROTOCOL_VARIANT_ADD(INET6, STREAM, IPPROTO_TCP);
PROTOCOL_VARIANT_ADD(INET6, DGRAM, 0);
PROTOCOL_VARIANT_ADD(INET6, DGRAM, IPPROTO_UDP);
PROTOCOL_VARIANT_ADD_CAPS(INET6, RAW, IPPROTO_TCP);
PROTOCOL_VARIANT_ADD(INET6, SEQPACKET, IPPROTO_SCTP);
PROTOCOL_VARIANT_ADD(INET6, STREAM, IPPROTO_MPTCP);

/* Cf. rose_create */
PROTOCOL_VARIANT_ADD(ROSE, SEQPACKET, 0);

/* Cf. pfkey_create */
PROTOCOL_VARIANT_ADD_CAPS(KEY, RAW, PF_KEY_V2);

/* Cf. netlink_create */
PROTOCOL_VARIANT_ADD(NETLINK, RAW, 0);
PROTOCOL_VARIANT_ADD(NETLINK, DGRAM, 0);

/* Cf. packet_create */
PROTOCOL_VARIANT_ADD_CAPS(PACKET, DGRAM, 0);
PROTOCOL_VARIANT_ADD_CAPS(PACKET, RAW, 0);
PROTOCOL_VARIANT_ADD_CAPS(PACKET, PACKET, 0);

/* Cf. svc_create */
PROTOCOL_VARIANT_ADD(ATMSVC, DGRAM, 0);
PROTOCOL_VARIANT_ADD(ATMSVC, RAW, 0);
PROTOCOL_VARIANT_ADD(ATMSVC, RDM, 0);
PROTOCOL_VARIANT_ADD(ATMSVC, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD(ATMSVC, DCCP, 0);
PROTOCOL_VARIANT_ADD(ATMSVC, PACKET, 0);

/* Cf. rds_create */
PROTOCOL_VARIANT_ADD(RDS, SEQPACKET, 0);

/* Cf. pppox_create + pppoe_create */
PROTOCOL_VARIANT_ADD(PPPOX, STREAM, 0);
PROTOCOL_VARIANT_ADD(PPPOX, DGRAM, 0);
PROTOCOL_VARIANT_ADD(PPPOX, RAW, 0);
PROTOCOL_VARIANT_ADD(PPPOX, RDM, 0);
PROTOCOL_VARIANT_ADD(PPPOX, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD(PPPOX, DCCP, 0);
PROTOCOL_VARIANT_ADD(PPPOX, PACKET, 0);

/* Cf. llc_ui_create */
PROTOCOL_VARIANT_ADD_CAPS(LLC, DGRAM, 0);
PROTOCOL_VARIANT_ADD_CAPS(LLC, STREAM, 0);

/* Cf. can_create */
PROTOCOL_VARIANT_ADD(CAN, DGRAM, CAN_BCM);

/* Cf. tipc_sk_create */
PROTOCOL_VARIANT_ADD(TIPC, STREAM, 0);
PROTOCOL_VARIANT_ADD(TIPC, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD(TIPC, DGRAM, 0);
PROTOCOL_VARIANT_ADD(TIPC, RDM, 0);

/* Cf. l2cap_sock_create */
#ifndef __s390x__
PROTOCOL_VARIANT_ADD(BLUETOOTH, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD(BLUETOOTH, STREAM, 0);
PROTOCOL_VARIANT_ADD(BLUETOOTH, DGRAM, 0);
PROTOCOL_VARIANT_ADD_CAPS(BLUETOOTH, RAW, 0);
#endif

/* Cf. iucv_sock_create */
#ifdef __s390x__
PROTOCOL_VARIANT_ADD(IUCV, STREAM, 0);
PROTOCOL_VARIANT_ADD(IUCV, SEQPACKET, 0);
#endif

/* Cf. rxrpc_create */
PROTOCOL_VARIANT_ADD(RXRPC, DGRAM, PF_INET);

/* Cf. mISDN_sock_create */
#define ISDN_P_BASE 0 /* Cf. linux/mISDNif.h */
#define ISDN_P_TE_S0 0x01 /* Cf. linux/mISDNif.h */
PROTOCOL_VARIANT_ADD_CAPS(ISDN, RAW, ISDN_P_BASE);
PROTOCOL_VARIANT_ADD(ISDN, DGRAM, ISDN_P_TE_S0);

/* Cf. pn_socket_create */
PROTOCOL_VARIANT_ADD_CAPS(PHONET, DGRAM, 0);
PROTOCOL_VARIANT_ADD_CAPS(PHONET, SEQPACKET, 0);

/* Cf. ieee802154_create */
PROTOCOL_VARIANT_ADD_CAPS(IEEE802154, RAW, 0);
PROTOCOL_VARIANT_ADD(IEEE802154, DGRAM, 0);

/* Cf. caif_create */
PROTOCOL_VARIANT_ADD_CAPS(CAIF, SEQPACKET, 0);
PROTOCOL_VARIANT_ADD_CAPS(CAIF, STREAM, 0);

/* Cf. alg_create */
PROTOCOL_VARIANT_ADD(ALG, SEQPACKET, 0);

/* Cf. nfc_sock_create + rawsock_create */
PROTOCOL_VARIANT_ADD(NFC, SEQPACKET, 0);

/* Cf. vsock_create */
#if defined(__x86_64__) || defined(__aarch64__)
PROTOCOL_VARIANT_ADD(VSOCK, STREAM, 0);
PROTOCOL_VARIANT_ADD(VSOCK, SEQPACKET, 0);
#endif

/* Cf. qrtr_create */
PROTOCOL_VARIANT_ADD(QIPCRTR, DGRAM, 0);

/* Cf. mctp_pf_create */
PROTOCOL_VARIANT_ADD(MCTP, DGRAM, 0);
