// SPDX-License-Identifier: GPL-2.0
/*
 * Rockchip VEPU510 H.264 codec backend.
 *
 * Copyright (C) 2026 Jiaxing Hu <gahing@gahingwoo.com>
 *
 * VEPU510 emits complete Annex-B slice NAL units (nal_unit_header +
 * slice_header + slice_data) directly from hardware — the extensive
 * synt_sli0/synt_sli1/synt_sli2/synt_nal register set exists precisely
 * because the slice_header() syntax is generated by the hardware from
 * those fields (cross-checked against rockchip-linux/mpp's
 * hal_h264e_vepu510.c, which programs the identical fields from its own
 * software H264eSlice/H264ePps structs). What the hardware does *not*
 * generate is the SPS/PPS (parameter sets are a per-stream, not
 * per-frame, concept, and profile_idc/level_idc/VUI have no register
 * representation at all) — mpp's own `h264e_vepu_stream_amend_*` stage
 * confirms parameter sets are assembled in software around the hardware
 * slice payload, which is exactly what rkvenc_h264_gen_sps_pps() below
 * does, analogous to the upstream hantro JPEG encoder driver's software
 * JFIF header prepend.
 */

#include <linux/delay.h>
#include <linux/dma-mapping.h>
#include <linux/log2.h>

#include <media/v4l2-ctrls.h>
#include <media/videobuf2-dma-contig.h>

#include "rkvenc.h"
#include "rkvenc-regs.h"

/* SPS log2_max_frame_num_minus4 / log2_max_pic_order_cnt_lsb_minus4: both
 * fixed at 4 (8-bit fields) so frame_num/poc_lsb wrap well past any sane
 * GOP size while still fitting the 4-bit synt_sps.max_fnum/mpoc_lm4
 * hardware fields (valid range 0-12 per spec, 0-15 per register width).
 */
#define RKVENC_H264_LOG2_MAX_FRAME_NUM		4
#define RKVENC_H264_LOG2_MAX_POC_LSB		4

/* PARAM (0x1700-0x19cc) and SQI (0x2000-0x20b8) class content: mpp's own
 * *default-tuning-profile* constant tables (RDO lambda/cost tables and
 * subjective-quality tuning respectively), selected by a tuning knob this
 * driver doesn't expose rather than by resolution/QP/content -- so a
 * fixed constant table is the correct v1 implementation, not a
 * placeholder. Captured via wtrace from a real successful
 * rockchip-linux/mpp `mpi_enc_test` encode and cross-checked against the
 * declared class boundaries in mpp_rkvenc2.c's hw_info table (SQI's
 * declared range extends to 0x212c, but a real encode never touches past
 * 0x20b8, so this driver doesn't either). See the RC_ROI banner comment
 * in rkvenc-regs.h for why these classes are not actually optional
 * despite nothing in the userspace HAL ever documenting them as required.
 */
static const u32 rkvenc_par_class[] = {
	0x00030001, 0x00080006, 0x00030001, 0x00080006, 0x00030001, 0x00080006,
	0x00000fff, 0x10101010, 0x10101010, 0x16141a16, 0x13141512, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00020001, 0x002d0006,
	0x00000000, 0x00000000, 0x00101010, 0x00121112, 0x00101010, 0x00000000,
	0x00000103, 0x0500c010, 0x00000000, 0x04040404, 0x00000021, 0x00000000,
	0x00401004, 0x00806040, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000009, 0x0000000b, 0x0000000e, 0x00000011,
	0x00000016, 0x0000001b, 0x00000022, 0x0000002b, 0x00000036, 0x00000045,
	0x00000056, 0x0000006d, 0x00000089, 0x000000ad, 0x000000da, 0x00000112,
	0x00000159, 0x000001b3, 0x00000224, 0x000002b3, 0x00000366, 0x00000449,
	0x00000566, 0x000006cd, 0x00000891, 0x00000acb, 0x00000d9a, 0x000013c1,
	0x000018e4, 0x00001f5c, 0x00002783, 0x000031c8, 0x00003eb8, 0x00004f06,
	0x00006390, 0x00008e14, 0x0000b302, 0x0000e18a, 0x00011c29, 0x00016605,
	0x0001c313, 0x00027ae1, 0x00031fe6, 0x0003efcf, 0x0004f5c3, 0x0006e785,
	0x0008b2ef, 0x000af5c3, 0x000f1e7a, 0x00130c7f, 0x00180000, 0x001e3cf4,
};

static const u32 rkvenc_sqi_class[] = {
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00002f10,
	0x00180000, 0x00400030, 0x00200010, 0x00600030, 0x00180030, 0x00300060,
	0x03010301, 0x04010401, 0x03000300, 0x00000301, 0x09060906, 0x08060b06,
	0x14061409, 0x00001007, 0x0006000a, 0x00003151, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00070000, 0x0019000f,
	0x10101010, 0x00000010, 0x00000000, 0x00000000, 0x00000000, 0x00280014,
	0x00000048, 0x10101010, 0x00000000, 0x00000000, 0x00000000, 0x00100008,
	0x00000020, 0x10101010, 0x00000000, 0x04010401, 0x08081010,
};

static void rkvenc_write_table_relaxed(struct rkvenc_dev *dev, u32 base_off,
					const u32 *words, size_t count)
{
	size_t i;

	for (i = 0; i < count; i++)
		rkvenc_write_relaxed(dev, base_off + 4 * i, words[i]);
}

/* ---- minimal RBSP bit writer for SPS/PPS ---- */

struct rkvenc_bitwriter {
	u8 *buf;
	size_t size;
	size_t byte_pos;
	u8 bit_pos;
};

static void bw_init(struct rkvenc_bitwriter *bw, u8 *buf, size_t size)
{
	bw->buf = buf;
	bw->size = size;
	bw->byte_pos = 0;
	bw->bit_pos = 0;
	memset(buf, 0, size);
}

static void bw_put_bit(struct rkvenc_bitwriter *bw, u32 bit)
{
	if (bw->byte_pos >= bw->size)
		return;

	if (bit)
		bw->buf[bw->byte_pos] |= BIT(7 - bw->bit_pos);

	if (++bw->bit_pos == 8) {
		bw->bit_pos = 0;
		bw->byte_pos++;
	}
}

static void bw_put_bits(struct rkvenc_bitwriter *bw, u32 val, unsigned int n)
{
	int i;

	for (i = n - 1; i >= 0; i--)
		bw_put_bit(bw, (val >> i) & 1);
}

/* Exp-Golomb ue(v) */
static void bw_put_ue(struct rkvenc_bitwriter *bw, u32 val)
{
	u32 code = val + 1;
	unsigned int n = code ? fls(code) - 1 : 0;

	bw_put_bits(bw, 0, n);
	bw_put_bits(bw, code, n + 1);
}

/* Exp-Golomb se(v) */
static void bw_put_se(struct rkvenc_bitwriter *bw, int val)
{
	u32 code = val <= 0 ? (u32)(-val) * 2 : (u32)val * 2 - 1;

	bw_put_ue(bw, code);
}

static void bw_rbsp_trailing_bits(struct rkvenc_bitwriter *bw)
{
	bw_put_bit(bw, 1);
	while (bw->bit_pos != 0)
		bw_put_bit(bw, 0);
}

/* Emit one Annex-B NAL unit (start code + header + escaped RBSP) into out,
 * returns bytes written.
 */
static size_t rkvenc_write_nal(u8 *out, size_t out_size, u8 nal_ref_idc,
			       u8 nal_unit_type, const u8 *rbsp, size_t rbsp_len)
{
	static const u8 start_code[] = { 0x00, 0x00, 0x00, 0x01 };
	size_t pos = 0;
	unsigned int zero_run = 0;
	size_t i;

	if (out_size < sizeof(start_code) + 1)
		return 0;

	memcpy(out, start_code, sizeof(start_code));
	pos += sizeof(start_code);
	out[pos++] = (nal_ref_idc << 5) | nal_unit_type;

	for (i = 0; i < rbsp_len && pos < out_size; i++) {
		if (zero_run >= 2 && rbsp[i] <= 3) {
			out[pos++] = 0x03;
			zero_run = 0;
			if (pos >= out_size)
				break;
		}
		out[pos++] = rbsp[i];
		zero_run = rbsp[i] == 0 ? zero_run + 1 : 0;
	}

	return pos;
}

static const u8 rkvenc_h264_level_idc[] = {
	[V4L2_MPEG_VIDEO_H264_LEVEL_1_0] = 10,
	[V4L2_MPEG_VIDEO_H264_LEVEL_1B]  = 11,
	[V4L2_MPEG_VIDEO_H264_LEVEL_1_1] = 11,
	[V4L2_MPEG_VIDEO_H264_LEVEL_1_2] = 12,
	[V4L2_MPEG_VIDEO_H264_LEVEL_1_3] = 13,
	[V4L2_MPEG_VIDEO_H264_LEVEL_2_0] = 20,
	[V4L2_MPEG_VIDEO_H264_LEVEL_2_1] = 21,
	[V4L2_MPEG_VIDEO_H264_LEVEL_2_2] = 22,
	[V4L2_MPEG_VIDEO_H264_LEVEL_3_0] = 30,
	[V4L2_MPEG_VIDEO_H264_LEVEL_3_1] = 31,
	[V4L2_MPEG_VIDEO_H264_LEVEL_3_2] = 32,
	[V4L2_MPEG_VIDEO_H264_LEVEL_4_0] = 40,
	[V4L2_MPEG_VIDEO_H264_LEVEL_4_1] = 41,
	[V4L2_MPEG_VIDEO_H264_LEVEL_4_2] = 42,
};

static void rkvenc_h264_gen_sps_pps(struct rkvenc_ctx *ctx)
{
	struct rkvenc_h264_ctx *h264 = &ctx->h264;
	struct rkvenc_bitwriter bw;
	u8 rbsp[32];
	size_t rbsp_len, pos = 0;
	unsigned int width = ctx->coded_fmt.width;
	unsigned int height = ctx->coded_fmt.height;
	unsigned int mb_w = ALIGN(width, 16) / 16;
	unsigned int mb_h = ALIGN(height, 16) / 16;
	unsigned int crop_w = mb_w * 16 - width;
	unsigned int crop_h = mb_h * 16 - height;
	bool crop = crop_w || crop_h;
	bool is_main = h264->profile->val == V4L2_MPEG_VIDEO_H264_PROFILE_MAIN;
	u8 profile_idc = is_main ? 77 : 66;
	u8 level_idc = rkvenc_h264_level_idc[h264->level->val];
	bool cabac = h264->entropy_mode->val == V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC;

	/* SPS (nal_ref_idc=1, nal_unit_type=7) */
	bw_init(&bw, rbsp, sizeof(rbsp));
	bw_put_bits(&bw, profile_idc, 8);
	bw_put_bits(&bw, 0, 8); /* constraint_set0..5_flag + reserved_zero_2bits */
	bw_put_bits(&bw, level_idc, 8);
	bw_put_ue(&bw, 0); /* seq_parameter_set_id */
	bw_put_ue(&bw, RKVENC_H264_LOG2_MAX_FRAME_NUM);
	bw_put_ue(&bw, 0); /* pic_order_cnt_type */
	bw_put_ue(&bw, RKVENC_H264_LOG2_MAX_POC_LSB);
	bw_put_ue(&bw, 1); /* max_num_ref_frames */
	bw_put_bit(&bw, 0); /* gaps_in_frame_num_value_allowed_flag */
	bw_put_ue(&bw, mb_w - 1);
	bw_put_ue(&bw, mb_h - 1);
	bw_put_bit(&bw, 1); /* frame_mbs_only_flag */
	bw_put_bit(&bw, 1); /* direct_8x8_inference_flag */
	bw_put_bit(&bw, crop);
	if (crop) {
		bw_put_ue(&bw, 0);
		bw_put_ue(&bw, crop_w / 2);
		bw_put_ue(&bw, 0);
		bw_put_ue(&bw, crop_h / 2);
	}
	bw_put_bit(&bw, 0); /* vui_parameters_present_flag */
	bw_rbsp_trailing_bits(&bw);
	rbsp_len = bw.byte_pos;
	pos += rkvenc_write_nal(h264->sps_pps_nal + pos,
				sizeof(h264->sps_pps_nal) - pos, 1, 7, rbsp, rbsp_len);

	/* PPS (nal_ref_idc=1, nal_unit_type=8) */
	bw_init(&bw, rbsp, sizeof(rbsp));
	bw_put_ue(&bw, 0); /* pic_parameter_set_id */
	bw_put_ue(&bw, 0); /* seq_parameter_set_id */
	bw_put_bit(&bw, cabac);
	bw_put_bit(&bw, 0); /* bottom_field_pic_order_in_frame_present_flag */
	bw_put_ue(&bw, 0); /* num_slice_groups_minus1 */
	bw_put_ue(&bw, 0); /* num_ref_idx_l0_default_active_minus1 */
	bw_put_ue(&bw, 0); /* num_ref_idx_l1_default_active_minus1 */
	bw_put_bit(&bw, 0); /* weighted_pred_flag */
	bw_put_bits(&bw, 0, 2); /* weighted_bipred_idc */
	bw_put_se(&bw, (int)h264->i_qp->val - 26); /* pic_init_qp_minus26 */
	bw_put_se(&bw, 0); /* pic_init_qs_minus26 */
	bw_put_se(&bw, 0); /* chroma_qp_index_offset */
	bw_put_bit(&bw, 1); /* deblocking_filter_control_present_flag */
	bw_put_bit(&bw, 0); /* constrained_intra_pred_flag */
	bw_put_bit(&bw, 0); /* redundant_pic_cnt_present_flag */
	bw_rbsp_trailing_bits(&bw);
	rbsp_len = bw.byte_pos;
	pos += rkvenc_write_nal(h264->sps_pps_nal + pos,
				sizeof(h264->sps_pps_nal) - pos, 1, 8, rbsp, rbsp_len);

	h264->sps_pps_len = pos;
}

/* ---- controls ---- */

static int rkvenc_h264_s_ctrl(struct v4l2_ctrl *ctrl)
{
	return 0;
}

static const struct v4l2_ctrl_ops rkvenc_h264_ctrl_ops = {
	.s_ctrl = rkvenc_h264_s_ctrl,
};

static int rkvenc_h264_init_ctrls(struct rkvenc_ctx *ctx)
{
	struct v4l2_ctrl_handler *hdl = &ctx->ctrl_handler;
	struct rkvenc_h264_ctx *h264 = &ctx->h264;

	/* Advisory only in v1: the hardware rc_en=0 fixed-QP
	 * path (rc_qp) is what's actually wired up, not this bitrate value.
	 */
	h264->bitrate = v4l2_ctrl_new_std(hdl, &rkvenc_h264_ctrl_ops,
					  V4L2_CID_MPEG_VIDEO_BITRATE,
					  64000, 100000000, 1, 2000000);

	h264->profile = v4l2_ctrl_new_std_menu(hdl, &rkvenc_h264_ctrl_ops,
			V4L2_CID_MPEG_VIDEO_H264_PROFILE,
			V4L2_MPEG_VIDEO_H264_PROFILE_MAIN,
			BIT(V4L2_MPEG_VIDEO_H264_PROFILE_CONSTRAINED_BASELINE),
			V4L2_MPEG_VIDEO_H264_PROFILE_BASELINE);

	h264->level = v4l2_ctrl_new_std_menu(hdl, &rkvenc_h264_ctrl_ops,
			V4L2_CID_MPEG_VIDEO_H264_LEVEL,
			V4L2_MPEG_VIDEO_H264_LEVEL_4_2,
			BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1B),
			V4L2_MPEG_VIDEO_H264_LEVEL_4_0);

	h264->entropy_mode = v4l2_ctrl_new_std_menu(hdl, &rkvenc_h264_ctrl_ops,
			V4L2_CID_MPEG_VIDEO_H264_ENTROPY_MODE,
			V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC, 0,
			V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CAVLC);

	h264->gop_size = v4l2_ctrl_new_std(hdl, &rkvenc_h264_ctrl_ops,
					   V4L2_CID_MPEG_VIDEO_GOP_SIZE,
					   1, 300, 1, 30);

	h264->i_qp = v4l2_ctrl_new_std(hdl, &rkvenc_h264_ctrl_ops,
				       V4L2_CID_MPEG_VIDEO_H264_I_FRAME_QP,
				       0, 51, 1, 26);

	h264->p_qp = v4l2_ctrl_new_std(hdl, &rkvenc_h264_ctrl_ops,
				       V4L2_CID_MPEG_VIDEO_H264_P_FRAME_QP,
				       0, 51, 1, 28);

	return hdl->error;
}

/* ---- start/stop ---- */

static int rkvenc_h264_start(struct rkvenc_ctx *ctx)
{
	struct rkvenc_dev *dev = ctx->dev;
	struct rkvenc_h264_ctx *h264 = &ctx->h264;
	/* Exact formulas from mpp's recon-buffer sizing function (the one
	 * that feeds hal_bufs_setup()) — aligned_h has the same +16 fudge
	 * mpp applies, not just MPP_ALIGN(height, 16).
	 */
	unsigned int aligned_w = ALIGN(ctx->coded_fmt.width, 64);
	unsigned int aligned_h = ALIGN(ctx->coded_fmt.height, 16) + 16;
	size_t fbc_hdr_size = ALIGN((size_t)aligned_w * aligned_h / 64, SZ_8K);
	size_t fbc_bdy_size = (size_t)aligned_w * aligned_h * 3 / 2;
	size_t total_size;
	int i;

	memset(&h264->frame_num, 0,
	       sizeof(*h264) - offsetof(struct rkvenc_h264_ctx, frame_num));

	h264->pixel_hdr_size = fbc_hdr_size;
	h264->pixel_buf_size = fbc_hdr_size + fbc_bdy_size;
	h264->thumb_buf_size = ALIGN((aligned_w / 64) * (aligned_h / 64) * 256, SZ_8K);
	h264->smear_buf_size = ALIGN(aligned_w / 64, 16) * ALIGN(aligned_h / 16, 16);
	total_size = h264->pixel_buf_size + h264->thumb_buf_size + h264->smear_buf_size;

	for (i = 0; i < 2; i++) {
		h264->recn_buf_cpu[i] = dma_alloc_coherent(dev->dev, total_size,
							   &h264->recn_buf_dma[i],
							   GFP_KERNEL);
		if (!h264->recn_buf_cpu[i]) {
			if (i)
				dma_free_coherent(dev->dev, total_size,
						  h264->recn_buf_cpu[0],
						  h264->recn_buf_dma[0]);
			return -ENOMEM;
		}
	}

	h264->meiw_buf_cpu = dma_alloc_coherent(dev->dev, SZ_4K, &h264->meiw_buf_dma,
						GFP_KERNEL);
	if (!h264->meiw_buf_cpu) {
		for (i = 0; i < 2; i++)
			dma_free_coherent(dev->dev, total_size,
					  h264->recn_buf_cpu[i], h264->recn_buf_dma[i]);
		return -ENOMEM;
	}

	/* Catch-all scratch buffer for the auxiliary FRAME-class write
	 * pointers (see the field comment in rkvenc.h). Sized like a full
	 * recon buffer so even a full-frame-sized spurious write fits.
	 */
	rkvenc_h264_gen_sps_pps(ctx);

	return 0;
}

static void rkvenc_h264_stop(struct rkvenc_ctx *ctx)
{
	struct rkvenc_dev *dev = ctx->dev;
	struct rkvenc_h264_ctx *h264 = &ctx->h264;
	size_t total_size = h264->pixel_buf_size + h264->thumb_buf_size +
			     h264->smear_buf_size;
	int i;

	for (i = 0; i < 2; i++) {
		if (h264->recn_buf_cpu[i])
			dma_free_coherent(dev->dev, total_size,
					  h264->recn_buf_cpu[i], h264->recn_buf_dma[i]);
		h264->recn_buf_cpu[i] = NULL;
	}

	if (h264->meiw_buf_cpu)
		dma_free_coherent(dev->dev, SZ_4K, h264->meiw_buf_cpu, h264->meiw_buf_dma);
	h264->meiw_buf_cpu = NULL;
}

/* VEPU510-only quirk sequence, written unconditionally on every task by
 * the downstream vendor kernel driver (drivers/video/rockchip/mpp/
 * mpp_rkvenc2.c:rkvenc_run(), 0x74/0x308 block). Absent from
 * rockchip-linux/mpp's userspace HAL entirely (it never touches these
 * registers), so it cannot be cross-checked against the userspace source
 * — treated as an opaque required silicon workaround for holding the
 * encoder off "auto-restart" until this driver's IRQ model reads the
 * completion status.
 *
 * EXPERIMENT, RESULT NEGATIVE (see git log): disabling this quirk was
 * tried as a hypothesis for a genuine hardware-watchdog stall
 * (int_sta wdg_sta) seen on first board bring-up. The board hit the
 * exact same stall with this quirk disabled, so it is not the cause —
 * re-enabled per the vendor's "unconditionally required" claim, since
 * removing it demonstrated no benefit. See rkvenc-regs.h RC_ROI-class
 * comment for the next hypothesis (roi_qthd0-3 never written).
 */
static void rkvenc_vepu510_quirk(struct rkvenc_dev *dev)
{
	rkvenc_write(dev, RKVENC_REG_DVBM_HOLD, RKVENC_DVBM_HOLD_VAL);
	rkvenc_write(dev, RKVENC_REG_ENC_ID, RKVENC_ENC_ID_QUIRK_VAL);
}

static void rkvenc_h264_run(struct rkvenc_ctx *ctx)
{
	struct rkvenc_dev *dev = ctx->dev;
	struct rkvenc_h264_ctx *h264 = &ctx->h264;
	struct vb2_v4l2_buffer *src_buf = rkvenc_get_src_buf(ctx);
	struct vb2_v4l2_buffer *dst_buf = rkvenc_get_dst_buf(ctx);
	dma_addr_t src_dma = vb2_dma_contig_plane_dma_addr(&src_buf->vb2_buf, 0);
	dma_addr_t dst_dma = vb2_dma_contig_plane_dma_addr(&dst_buf->vb2_buf, 0);
	unsigned int width = ctx->coded_fmt.width;
	unsigned int height = ctx->coded_fmt.height;
	unsigned int aligned_w = ALIGN(width, 16);
	unsigned int aligned_h = ALIGN(height, 16);
	unsigned int uv_offset = ctx->src_fmt.bytesperline * ctx->src_fmt.height;
	unsigned int dst_size = vb2_plane_size(&dst_buf->vb2_buf, 0);
	bool is_idr = h264->gop_pos == 0;
	unsigned int header_len = is_idr ? h264->sps_pps_len : 0;
	unsigned int write_idx = h264->frame_num & 1;
	/* Frame 0 has no previously-written reference at all -- alias read to
	 * write (real hardware's refr_idx == curr_idx for frame 0, see the
	 * rkvenc_h264_ctx comment in rkvenc.h). From frame 1 on, buf[write_idx
	 * ^ 1] genuinely holds the previous frame's real reconstruction.
	 */
	unsigned int read_idx = h264->frame_num == 0 ? write_idx : (write_idx ^ 1);
	bool is_main = h264->profile->val == V4L2_MPEG_VIDEO_H264_PROFILE_MAIN;
	bool cabac = h264->entropy_mode->val == V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC;
	u32 qp = is_idr ? h264->i_qp->val : h264->p_qp->val;
	union rkvenc_reg_enc_pic enc_pic = { .val = 0 };
	union rkvenc_reg_enc_rsl enc_rsl = { .val = 0 };
	union rkvenc_reg_src_fill src_fill = { .val = 0 };
	union rkvenc_reg_src_fmt src_fmt = { .val = 0 };
	union rkvenc_reg_src_strd0 src_strd0 = { .val = 0 };
	union rkvenc_reg_src_strd1 src_strd1 = { .val = 0 };
	union rkvenc_reg_rc_cfg rc_cfg = { .val = 0 };
	union rkvenc_reg_rc_qp rc_qp = { .val = 0 };
	union rkvenc_reg_sli_splt sli_splt = { .val = 0 };
	union rkvenc_reg_rdo_cfg rdo_cfg = { .val = 0 };
	union rkvenc_reg_synt_nal synt_nal = { .val = 0 };
	union rkvenc_reg_synt_sps synt_sps = { .val = 0 };
	union rkvenc_reg_synt_pps synt_pps = { .val = 0 };
	union rkvenc_reg_synt_sli0 synt_sli0 = { .val = 0 };
	union rkvenc_reg_synt_sli1 synt_sli1 = { .val = 0 };
	union rkvenc_reg_synt_sli2 synt_sli2 = { .val = 0 };

	if (header_len)
		memcpy(vb2_plane_vaddr(&dst_buf->vb2_buf, 0), h264->sps_pps_nal, header_len);

	rkvenc_write_relaxed(dev, RKVENC_REG_DBG_CLR, RKVENC_DBG_CLR_VAL);

	/* Define every FRAME-class address/pointer register (0x270-0x2e8) by
	 * zeroing it before the specific pointers below overwrite the ones this
	 * driver actually uses. This matches the downstream vendor kernel, which
	 * writes its ENTIRE register file linearly every frame so no register
	 * ever carries stale bootloader/ATF/previous-session garbage. Doing this
	 * moved the long-standing rk_iommu write fault from a boot-varying
	 * garbage IOVA (the tell-tale 0x??b239?? stale-pointer signature) to a
	 * benign, deterministic 0x0.
	 *
	 * That residual write@0 (BUG-2) is a HW-synthesized write through one of
	 * these now-zero pointers (best candidate: the vrsp_rtn_en return-write
	 * to the zero online_addr; the vendor sets the same ENC_ID quirk with
	 * online_addr=0 and does NOT fault, so it is cosmetic). It is confirmed
	 * INDEPENDENT of the P-frame hang and harmless to the I-frame: a
	 * multi-agent evidence audit established the fault is a separate AXI
	 * transaction from the real recon write (rfpw=valid), it never lands
	 * (IOVA 0 pte invalid), and it cannot corrupt the reference the P-frame
	 * reads. An earlier attempt to redirect these pointers to scratch DMA
	 * buffers (colmvw/colmvr/lpfw/ebuft/ebufb) had NO measured effect on
	 * either bug and diverged from the vendor (which keeps them 0), so it was
	 * reverted -- zeroing alone is the vendor-matching behaviour.
	 */
	{
		u32 off;

		for (off = RKVENC_REG_FRAME_OFFSET; off <= RKVENC_REG_ADR_ROIR; off += 4)
			rkvenc_write_relaxed(dev, off, 0);
	}

	/* Source frame (NV12): adr_src0 = Y, adr_src1 = UV. adr_src2 (a 3rd
	 * plane pointer NV12 doesn't have) must equal adr_src1, not 0 — mpp's
	 * hal_h264e_vepu510.c sets it unconditionally to the same fd as
	 * adr_src1 even for 2-plane formats; confirmed via a real wtrace
	 * capture this is genuinely non-zero on a working encode.
	 */
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_SRC0, src_dma);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_SRC1, src_dma + uv_offset);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_SRC2, src_dma + uv_offset);

	/* All three of pixel(FBC)/thumb/smear are written by hardware on
	 * every frame regardless of feature use — see the rkvenc_h264_ctx
	 * comment in rkvenc.h. Leaving any of these at 0 IOMMU-faults in a
	 * tight retry loop instead of failing cleanly. The read side
	 * (rfpr/dspr/smear_rd) aliases the write side on frame 0 via
	 * read_idx == write_idx, see the read_idx comment above.
	 */
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPW_H_ADDR, h264->recn_buf_dma[write_idx]);
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPW_B_ADDR,
			     h264->recn_buf_dma[write_idx] + h264->pixel_hdr_size);
	rkvenc_write_relaxed(dev, RKVENC_REG_DSPW_ADDR,
			     h264->recn_buf_dma[write_idx] + h264->pixel_buf_size);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_SMEAR_WR,
			     h264->recn_buf_dma[write_idx] + h264->pixel_buf_size +
			     h264->thumb_buf_size);

	rkvenc_write_relaxed(dev, RKVENC_REG_RFPR_H_ADDR, h264->recn_buf_dma[read_idx]);
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPR_B_ADDR,
			     h264->recn_buf_dma[read_idx] + h264->pixel_hdr_size);
	rkvenc_write_relaxed(dev, RKVENC_REG_DSPR_ADDR,
			     h264->recn_buf_dma[read_idx] + h264->pixel_buf_size);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_SMEAR_RD,
			     h264->recn_buf_dma[read_idx] + h264->pixel_buf_size +
			     h264->thumb_buf_size);

	rkvenc_write_relaxed(dev, RKVENC_REG_MEIW_ADDR, h264->meiw_buf_dma);

	/* Interlaced-field recon addresses: this driver never encodes
	 * interlaced content, so rfpt/rfpb stay disabled -- but real hardware
	 * expects the literal sentinel 0xffffffff in rfpt_h/rfpt_b specifically
	 * (not a valid fd-embedded address), not a plain 0. rfpb_h/adr_rfpb_b
	 * are 0 on a real encode too.
	 */
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPT_H_ADDR, RKVENC_RFPT_DISABLED);
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPB_H_ADDR, 0);
	rkvenc_write_relaxed(dev, RKVENC_REG_RFPT_B_ADDR, RKVENC_RFPT_DISABLED);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_RFPB_B, 0);

	/* Bitstream ring buffer: hardware writes its complete slice NAL
	 * starting right after our software-written SPS/PPS prefix (if any).
	 */
	rkvenc_write_relaxed(dev, RKVENC_REG_BSBT_ADDR, dst_dma + dst_size - 1);
	rkvenc_write_relaxed(dev, RKVENC_REG_BSBB_ADDR, dst_dma + header_len);
	rkvenc_write_relaxed(dev, RKVENC_REG_ADR_BSBS, dst_dma + header_len);
	rkvenc_write_relaxed(dev, RKVENC_REG_BSBR_ADDR, dst_dma + header_len);

	enc_rsl.pic_wd8_m1 = aligned_w / 8 - 1;
	enc_rsl.pic_hd8_m1 = aligned_h / 8 - 1;
	rkvenc_write_relaxed(dev, RKVENC_REG_ENC_RSL, enc_rsl.val);

	src_fill.pic_wfill = aligned_w - width;
	src_fill.pic_hfill = aligned_h - height;
	rkvenc_write_relaxed(dev, RKVENC_REG_SRC_FILL, src_fill.val);

	src_fmt.src_cfmt = RKVENC_SRC_FMT_YUV420SP;
	src_fmt.out_fmt = 1; /* see RKVENC_SRC_FMT_YUV420SP comment in rkvenc-regs.h */
	rkvenc_write_relaxed(dev, RKVENC_REG_SRC_FMT, src_fmt.val);

	rkvenc_write_relaxed(dev, RKVENC_REG_SRC_PROC, 0);
	rkvenc_write_relaxed(dev, RKVENC_REG_PIC_OFST, 0);

	src_strd0.src_strd0 = ctx->src_fmt.bytesperline;
	rkvenc_write_relaxed(dev, RKVENC_REG_SRC_STRD0, src_strd0.val);
	src_strd1.src_strd1 = ctx->src_fmt.bytesperline;
	rkvenc_write_relaxed(dev, RKVENC_REG_SRC_STRD1, src_strd1.val);

	/* RC configuration: rc_en=1/aq_en=1 with a real (if approximate --
	 * see below) rc_adj/rc_dthd threshold ladder, but rc_qp_range=0 and
	 * rc_min_qp==rc_max_qp so the AQ engine has no room to actually move
	 * QP away from the requested value. This is genuine fixed-QP
	 * *output* via a real, non-degenerate RC *register configuration* --
	 * NOT the driver's original rc_en=0/all-zero-threshold design, which
	 * board bring-up proved reproducibly stalls the hardware (see the
	 * RC_ROI banner comment in rkvenc-regs.h for the full story and the
	 * exact real-hardware capture that pinned this down).
	 *
	 * bit_target is only a rough per-frame bit budget (bitrate control
	 * divided by an assumed 30fps -- v1 doesn't negotiate real frame
	 * intervals) feeding mpp's real threshold-ladder formula
	 * (setup_vepu510_rc_base()); since rc_qp_range=0 clamps AQ to a
	 * no-op regardless, the exact value only needs to be sane and
	 * non-degenerate, not accurate -- true adaptive bitrate tracking is
	 * a follow-up.
	 */
	{
		unsigned int mb_w = aligned_w / 16;
		unsigned int mb_h = aligned_h / 16;
		s32 bit_target = (s32)(h264->bitrate->val / 30);
		s32 mb_target_bits_mul_16 =
			(s32)(((s64)bit_target << 4) / (mb_w * mb_h));
		s32 mb_target_bits;
		s32 negative_bits_thd, positive_bits_thd;
		union rkvenc_reg_rc_adj0 rc_adj0 = { .val = 0 };
		union rkvenc_reg_rc_adj1 rc_adj1 = { .val = 0 };

		if (mb_target_bits_mul_16 >= 0x100000)
			mb_target_bits_mul_16 = 0x50000;

		mb_target_bits = (mb_target_bits_mul_16 * (s32)mb_w) >> 4;
		negative_bits_thd = 0 - 5 * mb_target_bits / 16;
		positive_bits_thd = 5 * mb_target_bits / 16;

		rc_cfg.rc_en = 1;
		rc_cfg.aq_en = 1;
		rc_cfg.rc_ctu_num = mb_w;
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_CFG, rc_cfg.val);

		rc_qp.rc_max_qp = qp;
		rc_qp.rc_min_qp = qp;
		/* EXPERIMENT, RESULT NEGATIVE (see git log): tried rc_qp_range=1
		 * (matching a real successful mpp capture's adaptive-RC value)
		 * instead of 0, as a hypothesis for the isolated rk_iommu fault
		 * below -- didn't stop it, and combined with other experimental
		 * changes at the time, board testing showed a real regression
		 * (every frame failing with a genuine hardware watchdog under
		 * multi-frame testing). Reverted to 0, which is confirmed safe
		 * for the fixed-QP output this driver actually wants (with
		 * rc_min_qp==rc_max_qp, AQ has no room to move QP regardless of
		 * range, so 0 vs 1 shouldn't matter for correctness -- but 0 is
		 * the value that's actually been confirmed not to regress).
		 */
		rc_qp.rc_qp_range = 0;
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_QP, rc_qp.val);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_TGT, (u32)mb_target_bits_mul_16);

		/* mpp's own constant qp_adj ladder, same for every frame
		 * regardless of content/resolution/QP.
		 */
		rc_adj0.qp_adj0 = -2;
		rc_adj0.qp_adj1 = -1;
		rc_adj0.qp_adj2 = 0;
		rc_adj0.qp_adj3 = 1;
		rc_adj0.qp_adj4 = 2;
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_ADJ0, rc_adj0.val);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_ADJ1, rc_adj1.val);

		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(0), (u32)(4 * negative_bits_thd));
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(1), (u32)negative_bits_thd);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(2), (u32)positive_bits_thd);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(3), (u32)(4 * positive_bits_thd));
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(4), RKVENC_RC_DTHD_SENTINEL);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(5), RKVENC_RC_DTHD_SENTINEL);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(6), RKVENC_RC_DTHD_SENTINEL);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(7), RKVENC_RC_DTHD_SENTINEL);
		rkvenc_write_relaxed(dev, RKVENC_REG_RC_DTHD(8), RKVENC_RC_DTHD_SENTINEL);
	}

	/* ROI QP-clamp thresholds: written unconditionally by mpp regardless
	 * of RC mode (see rkvenc-regs.h banner comment) — every area's
	 * [qpmin,qpmax] is set to this frame's QP so the clamp is a no-op
	 * rather than forcing every macroblock to QP 0.
	 */
	{
		union rkvenc_reg_roi_qthd0 roi_qthd0 = { .val = 0 };
		union rkvenc_reg_roi_qthd1 roi_qthd1 = { .val = 0 };
		union rkvenc_reg_roi_qthd2 roi_qthd2 = { .val = 0 };
		union rkvenc_reg_roi_qthd3 roi_qthd3 = { .val = 0 };

		roi_qthd0.qpmin_area0 = qp; roi_qthd0.qpmax_area0 = qp;
		roi_qthd0.qpmin_area1 = qp; roi_qthd0.qpmax_area1 = qp;
		roi_qthd0.qpmin_area2 = qp;
		rkvenc_write_relaxed(dev, RKVENC_REG_ROI_QTHD0, roi_qthd0.val);

		roi_qthd1.qpmax_area2 = qp;
		roi_qthd1.qpmin_area3 = qp; roi_qthd1.qpmax_area3 = qp;
		roi_qthd1.qpmin_area4 = qp; roi_qthd1.qpmax_area4 = qp;
		rkvenc_write_relaxed(dev, RKVENC_REG_ROI_QTHD1, roi_qthd1.val);

		roi_qthd2.qpmin_area5 = qp; roi_qthd2.qpmax_area5 = qp;
		roi_qthd2.qpmin_area6 = qp; roi_qthd2.qpmax_area6 = qp;
		roi_qthd2.qpmin_area7 = qp;
		rkvenc_write_relaxed(dev, RKVENC_REG_ROI_QTHD2, roi_qthd2.val);

		roi_qthd3.qpmax_area7 = qp;
		roi_qthd3.qpmap_mode = 1; /* matches mpp's hardcoded value */
		rkvenc_write_relaxed(dev, RKVENC_REG_ROI_QTHD3, roi_qthd3.val);
	}

	/* AQ activity LUT / MAD-statistics thresholds / chroma KLUT offset:
	 * see the banner comment above RKVENC_REG_AQ_TTHD in rkvenc-regs.h --
	 * real fields this driver never wrote at all until now, found by
	 * diffing against mpp's setup_vepu510_aq()/setup_vepu510_me()/
	 * setup_vepu510_rdo_pred(), all written unconditionally every frame
	 * (mpp's own default aq_tthd/aq_step tables are identical for I and P
	 * slices; klut_ofst is 6 for both in the non-IPC-tuning default this
	 * driver matches).
	 */
	{
		static const u8 aq_tthd[16] = {
			0, 0, 0, 0, 3, 3, 5, 5, 8, 8, 8, 15, 15, 20, 25, 25,
		};
		static const s32 aq_step[16] = {
			-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 7, 8,
		};
		union rkvenc_reg_aq_stp0 aq_stp0 = { .val = 0 };
		union rkvenc_reg_aq_stp1 aq_stp1 = { .val = 0 };
		union rkvenc_reg_aq_stp2 aq_stp2 = { .val = 0 };
		union rkvenc_reg_madi_st_thd madi_st_thd = { .val = 0 };
		union rkvenc_reg_madp_st_thd0 madp_st_thd0 = { .val = 0 };
		union rkvenc_reg_madp_st_thd1 madp_st_thd1 = { .val = 0 };
		union rkvenc_reg_klut_ofst klut_ofst = { .val = 0 };
		unsigned int i;

		for (i = 0; i < 4; i++) {
			u32 word = aq_tthd[4 * i] | (aq_tthd[4 * i + 1] << 8) |
				   (aq_tthd[4 * i + 2] << 16) | (aq_tthd[4 * i + 3] << 24);

			rkvenc_write_relaxed(dev, RKVENC_REG_AQ_TTHD + 4 * i, word);
		}

		aq_stp0.aq_stp_s0 = aq_step[0]; aq_stp0.aq_stp_0t1 = aq_step[1];
		aq_stp0.aq_stp_1t2 = aq_step[2]; aq_stp0.aq_stp_2t3 = aq_step[3];
		aq_stp0.aq_stp_3t4 = aq_step[4]; aq_stp0.aq_stp_4t5 = aq_step[5];
		rkvenc_write_relaxed(dev, RKVENC_REG_AQ_STP0, aq_stp0.val);

		/* aq_stp_7t8 is a hardcoded 0 in mpp's setup_vepu510_aq(), not
		 * aq_step[8] -- a genuine off-by-one quirk in the vendor HAL
		 * (aq_step[8..10] shift into aq_stp_8t9..10t11 instead), real
		 * hardware expects exactly this mapping so it's reproduced
		 * verbatim rather than "corrected".
		 */
		aq_stp1.aq_stp_5t6 = aq_step[6]; aq_stp1.aq_stp_6t7 = aq_step[7];
		aq_stp1.aq_stp_7t8 = 0; aq_stp1.aq_stp_8t9 = aq_step[8];
		aq_stp1.aq_stp_9t10 = aq_step[9]; aq_stp1.aq_stp_10t11 = aq_step[10];
		rkvenc_write_relaxed(dev, RKVENC_REG_AQ_STP1, aq_stp1.val);

		/* aq_stp2's middle two fields (12t13/13t14) don't match
		 * h264_P/I_aq_step_default's aq_step[12]/[13] verbatim -- cross-
		 * checked against the real vendor wtrace capture from the
		 * original I-frame bring-up (register 0x105c was 0x00839ca3
		 * there), which decodes to 3/5/7/7/8, not 3/4/5/7/8. Using the
		 * confirmed-real values for this one register instead of the
		 * source-derived table, since real silicon is the higher-truth
		 * source when the two disagree.
		 */
		aq_stp2.aq_stp_11t12 = aq_step[11]; aq_stp2.aq_stp_12t13 = 5;
		aq_stp2.aq_stp_13t14 = 7; aq_stp2.aq_stp_14t15 = aq_step[14];
		aq_stp2.aq_stp_b15 = aq_step[15];
		rkvenc_write_relaxed(dev, RKVENC_REG_AQ_STP2, aq_stp2.val);

		madi_st_thd.madi_th0 = 5;
		madi_st_thd.madi_th1 = 12;
		madi_st_thd.madi_th2 = 20;
		rkvenc_write_relaxed(dev, RKVENC_REG_MADI_ST_THD, madi_st_thd.val);

		madp_st_thd0.madp_th0 = 4 << 4;
		madp_st_thd0.madp_th1 = 9 << 4;
		rkvenc_write_relaxed(dev, RKVENC_REG_MADP_ST_THD0, madp_st_thd0.val);

		madp_st_thd1.madp_th2 = 15 << 4;
		rkvenc_write_relaxed(dev, RKVENC_REG_MADP_ST_THD1, madp_st_thd1.val);

		klut_ofst.chrm_klut_ofst = 6;
		rkvenc_write_relaxed(dev, RKVENC_REG_KLUT_OFST, klut_ofst.val);
	}

	/* PARAM/SQI: mpp's default-tuning constant tables -- see the comment
	 * on rkvenc_par_class/rkvenc_sqi_class above. SCL: this driver never
	 * uses a custom H.264 scaling list, so the whole class is zero --
	 * written explicitly every frame rather than relying on POR/leftover
	 * state, since real hardware still expects the class to have been
	 * written (see rkvenc-regs.h banner comment).
	 */
	rkvenc_write_table_relaxed(dev, RKVENC_REG_PAR_OFFSET, rkvenc_par_class,
				   ARRAY_SIZE(rkvenc_par_class));
	rkvenc_write_table_relaxed(dev, RKVENC_REG_SQI_OFFSET, rkvenc_sqi_class,
				   ARRAY_SIZE(rkvenc_sqi_class));
	{
		u32 off;

		for (off = RKVENC_REG_SCL_OFFSET;
		     off < RKVENC_REG_SCL_OFFSET + RKVENC_REG_SCL_SIZE; off += 4)
			rkvenc_write_relaxed(dev, off, 0);
	}

	/* ATR (anti-ringing) weights + smear_opt_cfg.stated_mode: patch the
	 * handful of PARAM/SQI words that are genuinely I/P-slice-dependent on
	 * top of the static blobs above -- see the CORRECTION banner comments
	 * on RKVENC_REG_ATR_THD1 and RKVENC_REG_SMEAR_OPT_CFG in rkvenc-regs.h.
	 * Values below are mpp's real setup_vepu510_anti_ringing()/
	 * setup_vepu510_anti_smear() constants for this driver's non-IPC scene
	 * mode, confirmed exactly against a real 3-frame wtrace capture.
	 */
	{
		union rkvenc_reg_atr_thd1 atr_thd1 = { .val = 0 };
		union rkvenc_reg_atr_wgt atr_wgt16 = { .val = 0 };
		union rkvenc_reg_atr_wgt atr_wgt8 = { .val = 0 };
		union rkvenc_reg_atr_wgt atr_wgt4 = { .val = 0 };
		union rkvenc_reg_smear_opt_cfg smear_opt_cfg = { .val = 0 };

		atr_thd1.thdqp = 45;
		if (is_idr) {
			atr_thd1.thd2 = 6;
			atr_wgt16.wgt0 = 16; atr_wgt16.wgt1 = 16; atr_wgt16.wgt2 = 16;
			atr_wgt8.wgt0 = 18; atr_wgt8.wgt1 = 17; atr_wgt8.wgt2 = 18;
			atr_wgt4.wgt0 = 16; atr_wgt4.wgt1 = 16; atr_wgt4.wgt2 = 16;
		} else {
			atr_thd1.thd2 = 7;
			atr_wgt16.wgt0 = 23; atr_wgt16.wgt1 = 22; atr_wgt16.wgt2 = 20;
			atr_wgt8.wgt0 = 24; atr_wgt8.wgt1 = 24; atr_wgt8.wgt2 = 24;
			atr_wgt4.wgt0 = 23; atr_wgt4.wgt1 = 22; atr_wgt4.wgt2 = 20;
		}
		rkvenc_write_relaxed(dev, RKVENC_REG_ATR_THD1, atr_thd1.val);
		rkvenc_write_relaxed(dev, RKVENC_REG_ATR_WGT16, atr_wgt16.val);
		rkvenc_write_relaxed(dev, RKVENC_REG_ATR_WGT8, atr_wgt8.val);
		rkvenc_write_relaxed(dev, RKVENC_REG_ATR_WGT4, atr_wgt4.val);

		smear_opt_cfg.rdo_smear_lvl16_multi = 16;
		smear_opt_cfg.rdo_smear_en = 0;
		smear_opt_cfg.stated_mode = (is_idr || h264->last_frame_was_idr) ? 1 : 2;
		/* Static approximation of a real per-block-statistics-derived
		 * value -- see the RKVENC_REG_SMEAR_OPT_CFG comment.
		 */
		smear_opt_cfg.rdo_smear_dlt_qp = is_idr ? -1 : -3;
		rkvenc_write_relaxed(dev, RKVENC_REG_SMEAR_OPT_CFG, smear_opt_cfg.val);
	}

	/* Single slice per frame in v1. */
	rkvenc_write_relaxed(dev, RKVENC_REG_SLI_SPLT, sli_splt.val);
	rkvenc_write_relaxed(dev, RKVENC_REG_SLI_BYTE, 0);
	rkvenc_write_relaxed(dev, RKVENC_REG_SLI_CNUM, 0);

	/* Motion-estimation search config — written unconditionally by mpp
	 * on every frame regardless of I/P (see rkvenc-regs.h banner
	 * comment); values are mpp's own hardcoded constants.
	 */
	{
		union rkvenc_reg_me_rnge me_rnge = { .val = 0 };
		union rkvenc_reg_me_cfg me_cfg = { .val = 0 };
		union rkvenc_reg_me_cach me_cach = { .val = 0 };

		me_rnge.cime_srch_dwnh = 15;
		me_rnge.cime_srch_uph = 15;
		me_rnge.cime_srch_rgtw = 12;
		me_rnge.cime_srch_lftw = 12;
		rkvenc_write_relaxed(dev, RKVENC_REG_ME_RNGE, me_rnge.val);

		me_cfg.srgn_max_num = 54;
		me_cfg.cime_dist_thre = 1024;
		me_cfg.rme_srch_h = 3;
		me_cfg.rme_srch_v = 3;
		rkvenc_write_relaxed(dev, RKVENC_REG_ME_CFG, me_cfg.val);

		me_cach.cime_zero_thre = 64;
		rkvenc_write_relaxed(dev, RKVENC_REG_ME_CACH, me_cach.val);
	}

	/* Matches setup_vepu510_rdo_pred()'s derivation in the vendor HAL.
	 * chrm_spcl/ccwa_e/atr_mult_sel_e are unconditional 1s in mpp
	 * regardless of profile/level/tune config -- see rkvenc-regs.h.
	 */
	rdo_cfg.rect_size = !is_main && rkvenc_h264_level_idc[h264->level->val] <= 30;
	rdo_cfg.vlc_lmt = !is_main && !cabac;
	rdo_cfg.chrm_spcl = 1;
	rdo_cfg.ccwa_e = 1;
	rdo_cfg.atr_mult_sel_e = 1;
	rkvenc_write_relaxed(dev, RKVENC_REG_RDO_CFG, rdo_cfg.val);

	/* mpp sets synt_nal.nal_ref_idc = slice->nal_reference_idc, which is
	 * NOT a flat 1 for every frame -- a real 3-frame capture showed 3 for
	 * the IDR slice and 2 for P slices (both real references, matching
	 * this driver's unconditional enc_pic.cur_frm_ref=1). This driver
	 * previously hardcoded 1 for both, a real spec-compliance gap in the
	 * hardware-generated slice NAL header (not known to be hang-related --
	 * the hardware just emits whatever value it's given).
	 */
	synt_nal.nal_ref_idc = is_idr ? 3 : 2;
	synt_nal.nal_unit_type = is_idr ? 5 : 1;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_NAL, synt_nal.val);

	synt_sps.max_fnum = RKVENC_H264_LOG2_MAX_FRAME_NUM;
	synt_sps.drct_8x8 = 1;
	synt_sps.mpoc_lm4 = RKVENC_H264_LOG2_MAX_POC_LSB;
	synt_sps.poc_type = 0;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_SPS, synt_sps.val);

	synt_pps.etpy_mode = cabac;
	synt_pps.csip_flag = 0;
	synt_pps.num_ref0_idx = 0;
	synt_pps.num_ref1_idx = 0;
	synt_pps.pic_init_qp = h264->i_qp->val;
	synt_pps.cb_ofst = 0;
	synt_pps.cr_ofst = 0;
	synt_pps.dbf_cp_flg = 1;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_PPS, synt_pps.val);

	synt_sli0.sli_type = is_idr ? RKVENC_SLI_TYPE_I : RKVENC_SLI_TYPE_P;
	synt_sli0.pps_id = 0;
	synt_sli0.cbc_init_idc = 0;
	synt_sli0.frm_num = h264->frame_num;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_SLI0, synt_sli0.val);

	synt_sli1.idr_pid = h264->idr_pic_id;
	synt_sli1.poc_lsb = h264->poc_lsb;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_SLI1, synt_sli1.val);

	synt_sli2.dis_dblk_idc = 0;
	synt_sli2.sli_alph_ofst = 0;
	synt_sli2.sli_beta_ofst = 0;
	rkvenc_write_relaxed(dev, RKVENC_REG_SYNT_SLI2, synt_sli2.val);

	enc_pic.enc_stnd = RKVENC_ENC_STND_H264;
	enc_pic.cur_frm_ref = 1;
	enc_pic.pic_qp = qp;
	enc_pic.rec_fbc_dis = 0;
	/* mpp's setup_vepu510_codec() sets this unconditionally to 1 on every
	 * frame; confirmed not just from source but from the real vendor
	 * wtrace capture used for the original I-frame bring-up (0x300 was
	 * 0x4000191c there, bit4 set) -- this driver had never set it at all.
	 */
	enc_pic.bs_scp = 1;
	/* mpp's hal_h264e_vepu510_gen_regs() sets this whenever a real
	 * motion-detection-info buffer is provided (mei_stor = task->md_info
	 * ? 1 : 0) -- this driver always provides one (meiw_buf_dma below),
	 * so this must always be 1 too. Previously left 0 despite the address
	 * being valid: a mismatch between "here's a real buffer" and "don't
	 * actually store to it" that plausibly only bites once the ME engine
	 * has real motion-vector output to write, i.e. genuine inter-frame
	 * (P-frame) search -- an I-frame's trivial/absent ME activity may
	 * never actually exercise the write-enable path this gates.
	 */
	enc_pic.mei_stor = 1;
	/* slen_fifo is deliberately left 0 for this FIRST ENC_PIC write. The
	 * vendor arms the slice-length FIFO in a two-step sequence: ENC_PIC is
	 * written with slen_fifo=0 during setup, then RE-written with
	 * slen_fifo=1 as the very last register before ENC_START. A real
	 * multi-frame wtrace capture shows this on EVERY frame (I and both P):
	 * 0x300 written twice, e.g. P-frame `0x00001a1c` (slen_fifo=0) early
	 * then `0x40001a1c` (slen_fifo=1) at the kick. This driver previously
	 * wrote ENC_PIC once with slen_fifo=1 and then wrote DUAL_CORE after
	 * it -- so it never reproduced the vendor's "arm the FIFO as the final
	 * action immediately before the kick" ordering. That two-step arm is
	 * the strongest-remaining register-level difference for the P-frame
	 * hang: the I-frame limps through without it, but a P-frame produces
	 * genuine slice-FIFO traffic that may depend on the FIFO being armed
	 * last. See the kick sequence below.
	 */
	enc_pic.slen_fifo = 0;

	/* First ENC_PIC write (slen_fifo=0) and DUAL_CORE, both in the
	 * vendor's early "config" position -- the capture writes 0x300
	 * (slen_fifo=0) and 0x304=0x14 together in the FRAME-class region,
	 * well before the kick, NOT interleaved into the kick tail.
	 *
	 * DUAL_CORE=0x14: see the union rkvenc_reg_dual_core comment in
	 * rkvenc-regs.h. Confirmed written once per frame (seq62/714/1366 in
	 * the multi-frame capture) even for this fully standalone single-core
	 * encode; leaving it 0 did NOT stop the isolated rk_iommu fault.
	 */
	rkvenc_write_relaxed(dev, RKVENC_REG_ENC_PIC, enc_pic.val);
	rkvenc_write_relaxed(dev, RKVENC_REG_DUAL_CORE, 0x14);

	/* Control-class (Vepu510ControlCfg) setup + the vendor's exact kick
	 * tail. The kick order is transcribed verbatim from a real multi-frame
	 * wtrace capture (the last writes of every frame, identical across I
	 * and both P frames):
	 *   ENC_WDG(0x38) -> DVBM_HOLD(0x74) -> ENC_ID(0x308) -> INT_EN(0x20)
	 *   -> ENC_PIC(0x300, slen_fifo=1) -> ENC_START(0x10)
	 * with ENC_PIC (FIFO-armed) as the final config write before the kick.
	 */
	{
		union rkvenc_reg_int_bits int_en = { .val = 0 };
		union rkvenc_reg_opt_strg opt_strg = { .val = 0 };
		union rkvenc_reg_dtrns_map dtrns_map = { .val = 0 };
		union rkvenc_reg_enc_strt enc_strt = { .val = 0 };

		int_en.enc_done = 1;
		int_en.lkt_node_done = 1;
		int_en.sclr_done = 1;
		int_en.vslc_done = 1; /* mirrors enc_pic.slen_fifo armed below */
		int_en.vbsf_oflw = 1;
		int_en.vbuf_lens = 1;
		int_en.enc_err = 1;
		int_en.vsrc_err = 1;
		int_en.wdg = 1;
		int_en.lkt_err_int = 1;
		int_en.lkt_err_stop = 1;
		int_en.lkt_force_stop = 1;
		int_en.jslc_done = 1;
		int_en.jbsf_oflw = 1;
		int_en.jbuf_lens = 1;

		/* Early config writes (the vendor emits these in its linear
		 * offset-ordered dump, well before the kick): INT_MASK, OPT_STRG,
		 * DTRNS_MAP. INT_EN itself is deferred to the kick tail below to
		 * match the capture (INT_EN is re-written right before ENC_PIC).
		 */
		rkvenc_write_relaxed(dev, RKVENC_REG_INT_MASK, 0);

		opt_strg.cke = 1;
		opt_strg.resetn_hw_en = 1;
		rkvenc_write_relaxed(dev, RKVENC_REG_OPT_STRG, opt_strg.val);

		dtrns_map.bsw_bus_edin = 7;
		rkvenc_write_relaxed(dev, RKVENC_REG_DTRNS_MAP, dtrns_map.val);

		/* ---- exact vendor kick tail ---- */
		rkvenc_write(dev, RKVENC_REG_ENC_WDG, rkvenc_calc_wdg(dev, width, height));
		rkvenc_vepu510_quirk(dev); /* DVBM_HOLD(0x74) + ENC_ID(0x308) */
		rkvenc_write_relaxed(dev, RKVENC_REG_INT_EN, int_en.val);

		/* Final ENC_PIC re-write with slen_fifo=1 -- arms the slice-length
		 * FIFO as the very last action before ENC_START, matching the
		 * capture exactly. This is the whole point of the two-step arm.
		 */
		enc_pic.slen_fifo = 1;
		rkvenc_write_relaxed(dev, RKVENC_REG_ENC_PIC, enc_pic.val);

		wmb(); /* all task registers visible before the kick below */

		enc_strt.lkt_num = 0;
		enc_strt.vepu_cmd = RKVENC_VEPU_CMD_ENC;
		rkvenc_write(dev, RKVENC_REG_ENC_START, enc_strt.val);
	}
}

static void rkvenc_h264_done(struct rkvenc_ctx *ctx, enum vb2_buffer_state state)
{
	struct rkvenc_dev *dev = ctx->dev;
	struct rkvenc_h264_ctx *h264 = &ctx->h264;
	struct vb2_v4l2_buffer *dst_buf = rkvenc_get_dst_buf(ctx);
	bool is_idr = h264->gop_pos == 0;

	if (state == VB2_BUF_STATE_DONE) {
		unsigned int header_len = is_idr ? h264->sps_pps_len : 0;
		u32 hw_len = rkvenc_read(dev, RKVENC_REG_ST_BS_LENGTH);

		vb2_set_plane_payload(&dst_buf->vb2_buf, 0, header_len + hw_len);
		dst_buf->flags |= is_idr ? V4L2_BUF_FLAG_KEYFRAME : V4L2_BUF_FLAG_PFRAME;

		h264->frame_num = (h264->frame_num + 1) &
				  GENMASK(RKVENC_H264_LOG2_MAX_FRAME_NUM + 3, 0);
		h264->poc_lsb = (h264->poc_lsb + 2) &
				GENMASK(RKVENC_H264_LOG2_MAX_POC_LSB + 3, 0);
		h264->last_frame_was_idr = is_idr;
		if (++h264->gop_pos >= h264->gop_size->val)
			h264->gop_pos = 0;
		if (h264->gop_pos == 0)
			h264->idr_pic_id++;
	}
}

static const struct rkvenc_coded_fmt_ops rkvenc_h264_ops = {
	.init_ctrls = rkvenc_h264_init_ctrls,
	.start = rkvenc_h264_start,
	.stop = rkvenc_h264_stop,
	.run = rkvenc_h264_run,
	.done = rkvenc_h264_done,
};

const struct rkvenc_coded_fmt_desc rkvenc_h264_fmt_desc = {
	.fourcc = V4L2_PIX_FMT_H264,
	.frmsize = {
		.frmsize_min_width = 176,
		.frmsize_max_width = 4096,
		.frmsize_step_width = 2,
		.frmsize_min_height = 144,
		.frmsize_max_height = 2560,
		.frmsize_step_height = 2,
	},
	.ops = &rkvenc_h264_ops,
};
