/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) 2015-2017  Dialog Semiconductor
 * Copyright (C) 2022  Raptor Engineering, LLC
 */

#ifndef __MFD_SONY_CRONOS_H__
#define __MFD_SONY_CRONOS_H__

#define CRONOS_SMC_DEVICE_ID				0x0134

#define CRONOS_SMC_SWITCH_BOOT_FLASH_SELECT_REG		0x00
#define CRONOS_SMC_SWITCH_RESET_CMD_REG			0x01
#define CRONOS_SMC_BMC_BOOT_FLASH_SELECT_REG		0x02
#define CRONOS_BMC_RESET_REG				0x03
#define CRONOS_WDT_CLR_REG				0x03
#define CRONOS_SMC_STATUS_2_REG				0x05
#define CRONOS_SMC_PAYLOAD_POWER_CTL_REG		0x0a
#define CRONOS_WDT_CTL_REG				0x0c
#define CRONOS_SMC_UART_MUX_REG				0x0e

#define CRONOS_SMC_BRIGHTNESS_RED_REG			0x17
#define CRONOS_SMC_BRIGHTNESS_GREEN_REG			0x18
#define CRONOS_SMC_BRIGHTNESS_BLUE_REG			0x19

#define CRONOS_LEDS_SMC_STATUS_REG			0x10
#define CRONOS_LEDS_SWITCH_STATUS_REG			0x11

#define CRONOS_LEDS_CCM3_STATUS_REG			0x12
#define CRONOS_LEDS_CCM2_STATUS_REG			0x13
#define CRONOS_LEDS_CCM4_STATUS_REG			0x14
#define CRONOS_LEDS_CCM1_STATUS_REG			0x15

#define CRONOS_LEDS_CCM_POWER_REG			0x16

#define CRONOS_SMC_BMC_MAC_LOW_REG			0x30
#define CRONOS_SMC_BMC_MAC_HIGH_REG			0x35

#define CRONOS_SMC_DEVICE_ID_LOW_REG			0x70
#define CRONOS_SMC_DEVICE_ID_HIGH_REG			0x71
#define CRONOS_SMC_REVISION_LOW_REG			0x72
#define CRONOS_SMC_REVISION_HIGH_REG			0x73

#define CRONOS_SMC_LEDS_BRIGHTNESS_SET_MASK		0x7F
#define CRONOS_LEDS_MAX_BRIGHTNESS			0x7F

#define CRONOS_BMC_RESET_VAL				0xc2

#define CRONOS_WDT_CLR_VAL				0xc3
#define CRONOS_WDT_ENABLE_MASK				0x80
#define CRONOS_WDT_ENABLE_VAL				0x80
#define CRONOS_WDT_DISABLE_VAL				0x00
#define CRONOS_WDT_TIMEOUT_MASK				0x07
#define CRONOS_WDT_CTL_RESET_VAL			0x00

struct sony_cronos_smc {
	struct device *dev;
	struct regmap *regmap;
};

#endif /* __MFD_SONY_CRONOS_H__ */
