# SPDX-License-Identifier: GPL-2.0

gb-cpc-y := cport.o header.o host.o protocol.o

# CPC core
obj-$(CONFIG_GREYBUS_CPC)	+= gb-cpc.o

gb-cpc-sdio-y := sdio.o
obj-$(CONFIG_GREYBUS_CPC_SDIO)	+= gb-cpc-sdio.o
