# SPDX-License-Identifier: GPL-2.0
TEST_PROGS := rxe_rping_between_netns.sh \
		rxe_ipv6.sh \
		rxe_socket_with_netns.sh \
		rxe_test_NETDEV_UNREGISTER.sh

TEST_PROGS += \
	rdma_cm_baseline.sh \
	rdma_cm_trace_sequence.sh \
	rdma_cm_counter_delta.sh \
	rdma_cm_fault_injection.sh

TEST_FILES += \
	rdma_common.sh \
	rdma_cm_review_loop.sh

include ../lib.mk
