# SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION. All rights reserved.
#
# Mellanox BlueField PKA Driver
#

obj-$(CONFIG_MLXBF_PKA) += mlxbf-pka.o

mlxbf-pka-objs := mlxbf_pka_drv.o
mlxbf-pka-objs += mlxbf_pka_dev.o
