# SPDX-License-Identifier: GPL-2.0
usb3hdcap-y := usb3hdcap-core.o usb3hdcap-video.o usb3hdcap-composite.o \
               usb3hdcap-hdmi.o usb3hdcap-audio.o
obj-$(CONFIG_VIDEO_USB3HDCAP) += usb3hdcap.o
