# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_COMMON_CLK_DAVINCI_DA8XX_CFGCHIP)	+= da8xx-cfgchip.o

obj-y += pll.o
obj-$(CONFIG_COMMON_CLK_DAVINCI_DA850)		+= pll-da850.o

obj-y += psc.o
obj-$(CONFIG_COMMON_CLK_DAVINCI_DA850)		+= psc-da850.o
