# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel multimedia device drivers.
#

# Please keep it alphabetically sorted by directory
# keep-sorted start skip_lines=1
obj-y        += \
		b2c2/		\
		ddbridge/	\
		dm1105/		\
		intel/ 		\
		mantis/		\
		netup_unidvb/	\
		ngene/		\
		pluto2/		\
		pt1/		\
		pt3/		\
		saa7146/	\
		smipcie/	\
		ttpci/
# keep-sorted end

# Please keep it alphabetically sorted by Kconfig name
# keep-sorted start
obj-$(CONFIG_VIDEO_BT848) += bt8xx/
obj-$(CONFIG_VIDEO_COBALT) += cobalt/
obj-$(CONFIG_VIDEO_CX18) += cx18/
obj-$(CONFIG_VIDEO_CX23885) += cx23885/
obj-$(CONFIG_VIDEO_CX25821) += cx25821/
obj-$(CONFIG_VIDEO_CX88) += cx88/
obj-$(CONFIG_VIDEO_DT3155) += dt3155/
obj-$(CONFIG_VIDEO_IVTV) += ivtv/
obj-$(CONFIG_VIDEO_MGB4) += mgb4/
obj-$(CONFIG_VIDEO_SAA7134) += saa7134/
obj-$(CONFIG_VIDEO_SAA7164) += saa7164/
obj-$(CONFIG_VIDEO_SOLO6X10) += solo6x10/
obj-$(CONFIG_VIDEO_TW5864) += tw5864/
obj-$(CONFIG_VIDEO_TW68) += tw68/
obj-$(CONFIG_VIDEO_TW686X) += tw686x/
obj-$(CONFIG_VIDEO_ZORAN) += zoran/
# keep-sorted end
