/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Rockchip CIF Driver
 *
 * Copyright (C) 2018 Rockchip Electronics Co., Ltd.
 * Copyright (C) 2023 Mehdi Djait <mehdi.djait@bootlin.com>
 */

#ifndef _CIF_REGS_H
#define _CIF_REGS_H

#define CIF_CTRL				0x00
#define CIF_INTEN				0x04
#define CIF_INTSTAT				0x08
#define CIF_FOR					0x0c
#define CIF_LINE_NUM_ADDR			0x10
#define CIF_FRM0_ADDR_Y				0x14
#define CIF_FRM0_ADDR_UV			0x18
#define CIF_FRM1_ADDR_Y				0x1c
#define CIF_FRM1_ADDR_UV			0x20
#define CIF_VIR_LINE_WIDTH			0x24
#define CIF_SET_SIZE				0x28
#define CIF_SCM_ADDR_Y				0x2c
#define CIF_SCM_ADDR_U				0x30
#define CIF_SCM_ADDR_V				0x34
#define CIF_WB_UP_FILTER			0x38
#define CIF_WB_LOW_FILTER			0x3c
#define CIF_WBC_CNT				0x40
#define CIF_CROP				0x44
#define CIF_SCL_CTRL				0x48
#define CIF_SCL_DST				0x4c
#define CIF_SCL_FCT				0x50
#define CIF_SCL_VALID_NUM			0x54
#define CIF_LINE_LOOP_CTR			0x58
#define CIF_FRAME_STATUS			0x60
#define CIF_CUR_DST				0x64
#define CIF_LAST_LINE				0x68
#define CIF_LAST_PIX				0x6c
#define CIF_FETCH_Y_LAST_LINE(VAL)		((VAL) & 0x1fff)

#define CIF_CTRL_ENABLE_CAPTURE			BIT(0)
#define CIF_CTRL_MODE_PINGPONG			BIT(1)
#define CIF_CTRL_MODE_LINELOOP			BIT(2)
#define CIF_CTRL_AXI_BURST_16			(0xf << 12)

#define CIF_INTEN_FRAME_END_EN			BIT(0)
#define CIF_INTEN_LINE_ERR_EN			BIT(2)
#define CIF_INTEN_BUS_ERR_EN			BIT(6)
#define CIF_INTEN_SCL_ERR_EN			BIT(7)
#define CIF_INTEN_PST_INF_FRAME_END_EN		BIT(9)

#define CIF_INTSTAT_CLS				0x3ff
#define CIF_INTSTAT_FRAME_END			BIT(0)
#define CIF_INTSTAT_LINE_END			BIT(1)
#define CIF_INTSTAT_LINE_ERR			BIT(2)
#define CIF_INTSTAT_PIX_ERR			BIT(3)
#define CIF_INTSTAT_DFIFO_OF			BIT(5)
#define CIF_INTSTAT_BUS_ERR			BIT(6)
#define CIF_INTSTAT_PRE_INF_FRAME_END		BIT(8)
#define CIF_INTSTAT_PST_INF_FRAME_END		BIT(9)
#define CIF_INTSTAT_FRAME_END_CLR		BIT(0)
#define CIF_INTSTAT_LINE_END_CLR		BIT(1)
#define CIF_INTSTAT_LINE_ERR_CLR		BIT(2)
#define CIF_INTSTAT_PST_INF_FRAME_END_CLR	BIT(9)
#define CIF_INTSTAT_ERR				0xfc

#define CIF_FRAME_STAT_CLS			0x00
#define CIF_FRAME_FRM0_STAT_CLS			0x20

#define CIF_FORMAT_VSY_HIGH_ACTIVE		BIT(0)
#define CIF_FORMAT_HSY_LOW_ACTIVE		BIT(1)

#define CIF_FORMAT_INPUT_MODE_YUV		(0x00 << 2)
#define CIF_FORMAT_INPUT_MODE_PAL		(0x02 << 2)
#define CIF_FORMAT_INPUT_MODE_NTSC		(0x03 << 2)
#define CIF_FORMAT_INPUT_MODE_BT1120		(0x07 << 2)
#define CIF_FORMAT_INPUT_MODE_RAW		(0x04 << 2)
#define CIF_FORMAT_INPUT_MODE_JPEG		(0x05 << 2)
#define CIF_FORMAT_INPUT_MODE_MIPI		(0x06 << 2)

#define CIF_FORMAT_YUV_INPUT_ORDER_UYVY		(0x00 << 5)
#define CIF_FORMAT_YUV_INPUT_ORDER_YVYU		BIT(5)
#define CIF_FORMAT_YUV_INPUT_ORDER_VYUY		BIT(6)
#define CIF_FORMAT_YUV_INPUT_ORDER_YUYV		(0x03 << 5)
#define CIF_FORMAT_YUV_INPUT_422		(0x00 << 7)
#define CIF_FORMAT_YUV_INPUT_420		BIT(7)

#define CIF_FORMAT_INPUT_420_ORDER_ODD		BIT(8)

#define CIF_FORMAT_CCIR_INPUT_ORDER_EVEN	BIT(9)

#define CIF_FORMAT_RAW_DATA_WIDTH_8		(0x00 << 11)
#define CIF_FORMAT_RAW_DATA_WIDTH_10		BIT(11)
#define CIF_FORMAT_RAW_DATA_WIDTH_12		(0x02 << 11)

#define CIF_FORMAT_YUV_OUTPUT_422		(0x00 << 16)
#define CIF_FORMAT_YUV_OUTPUT_420		BIT(16)

#define CIF_FORMAT_OUTPUT_420_ORDER_EVEN	(0x00 << 17)
#define CIF_FORMAT_OUTPUT_420_ORDER_ODD		BIT(17)

#define CIF_FORMAT_RAWD_DATA_LITTLE_ENDIAN	(0x00 << 18)
#define CIF_FORMAT_RAWD_DATA_BIG_ENDIAN		BIT(18)

#define CIF_FORMAT_UV_STORAGE_ORDER_UVUV	(0x00 << 19)
#define CIF_FORMAT_UV_STORAGE_ORDER_VUVU	BIT(19)

#define CIF_FORMAT_BT1120_CLOCK_SINGLE_EDGES	(0x00 << 24)
#define CIF_FORMAT_BT1120_CLOCK_DOUBLE_EDGES	BIT(24)
#define CIF_FORMAT_BT1120_TRANSMIT_INTERFACE	(0x00 << 25)
#define CIF_FORMAT_BT1120_TRANSMIT_PROGRESS	BIT(25)
#define CIF_FORMAT_BT1120_YC_SWAP		BIT(26)

#define CIF_SCL_CTRL_ENABLE_SCL_DOWN		BIT(0)
#define CIF_SCL_CTRL_ENABLE_SCL_UP		BIT(1)
#define CIF_SCL_CTRL_ENABLE_YUV_16BIT_BYPASS	BIT(4)
#define CIF_SCL_CTRL_ENABLE_RAW_16BIT_BYPASS	BIT(5)
#define CIF_SCL_CTRL_ENABLE_32BIT_BYPASS	BIT(6)
#define CIF_SCL_CTRL_DISABLE_32BIT_BYPASS	(0x00 << 6)

#define CIF_INTSTAT_F0_READY			BIT(0)
#define CIF_INTSTAT_F1_READY			BIT(1)

#define CIF_CROP_Y_SHIFT			16
#define CIF_CROP_X_SHIFT			0

#endif
