#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# generate_api_specs.sh - Generate C file that includes all API specification headers
#
# Usage: generate_api_specs.sh <srctree> <objtree>

SRCTREE="$1"
OBJTREE="$2"

if [ -z "$SRCTREE" ] || [ -z "$OBJTREE" ]; then
    echo "Usage: $0 <srctree> <objtree>" >&2
    exit 1
fi

# Generate header
cat <<EOF
/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Auto-generated file - DO NOT EDIT
 * Generated by: scripts/generate_api_specs.sh
 *
 * This file includes all kernel API specification headers
 */

#include <linux/kernel.h>
#include <linux/kernel_api_spec.h>
#include <linux/errno.h>
#include <linux/capability.h>
#include <uapi/linux/sched/types.h>

#ifdef CONFIG_KAPI_SPEC

EOF

# Find all .apispec.h files and generate includes
# We look in the object tree since that's where they're generated
find "$OBJTREE" -name "*.apispec.h" -type f 2>/dev/null | \
    grep -v "/generated_api_specs.c" | \
    sort | \
    while read -r apispec_file; do
        # Get relative path from objtree
        rel_path="${apispec_file#$OBJTREE/}"

        # Skip if file is empty
        if [ ! -s "$apispec_file" ]; then
            continue
        fi

        # Generate include statement
        # For includes from kernel/api/, we need to go up two levels
        echo "#include \"../../${rel_path}\""
    done

# Close the ifdef
cat <<EOF

#endif /* CONFIG_KAPI_SPEC */
EOF