# SPDX-License-Identifier: GPL-2.0
# ==========================================================================
# Rust shared definitions
# ==========================================================================

# The features in this list are the ones allowed for non-`rust/` code.
#
#   - Stable since Rust 1.81.0: `feature(lint_reasons)`.
#   - Stable since Rust 1.82.0: `feature(asm_const)`,
#     `feature(offset_of_nested)`, `feature(raw_ref_op)`.
#   - Stable since Rust 1.87.0: `feature(asm_goto)`.
#   - Expected to become stable: `feature(arbitrary_self_types)`.
#   - To be determined: `feature(used_with_arg)`.
#
# Please see https://github.com/Rust-for-Linux/linux/issues/2 for details on
# the unstable features in use.
rust_allowed_features := asm_const,asm_goto,arbitrary_self_types,lint_reasons,offset_of_nested,raw_ref_op,used_with_arg

# Common crate attrs for non-host, non-sysroot crates.
rust_common_crate_attrs := no_std feature($(rust_allowed_features))
