# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_GCC_PLUGIN_STACKLEAK
stackleak-cflags-y += -fplugin=$(objtree)/scripts/gcc-plugins/stackleak_plugin.so
stackleak-cflags-y += -fplugin-arg-stackleak_plugin-track-min-size=$(CONFIG_STACKLEAK_TRACK_MIN_SIZE)
stackleak-cflags-y += -fplugin-arg-stackleak_plugin-arch=$(SRCARCH)
stackleak-cflags-$(CONFIG_GCC_PLUGIN_STACKLEAK_VERBOSE) += -fplugin-arg-stackleak_plugin-verbose
DISABLE_STACKLEAK  := -fplugin-arg-stackleak_plugin-disable
endif

ifdef CONFIG_CC_IS_CLANG
stackleak-cflags-y += -fsanitize-coverage=stack-depth
stackleak-cflags-y += -fsanitize-coverage-stack-depth-callback-min=$(CONFIG_STACKLEAK_TRACK_MIN_SIZE)
DISABLE_STACKLEAK  := -fno-sanitize-coverage=stack-depth
endif

STACKLEAK_CFLAGS   := $(stackleak-cflags-y)

export STACKLEAK_CFLAGS DISABLE_STACKLEAK

KBUILD_CFLAGS += $(STACKLEAK_CFLAGS)
