# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Linux filesystem routines that are shared by client and server.
#

obj-$(CONFIG_SMBFS) += smb_common.o
smb_common-objs := common.o cifs_md4.o smb2maperror.o
