# SPDX-License-Identifier: GPL-2.0-only

acpm-protocol-objs			:= exynos-acpm.o exynos-acpm-pmic.o
acpm-protocol-$(CONFIG_DEBUG_FS)	+= exynos-acpm-debugfs.o
obj-$(CONFIG_EXYNOS_ACPM_PROTOCOL)	+= acpm-protocol.o
