/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
#ifndef INTERCONNECT_QCOM_IPQ5210_H
#define INTERCONNECT_QCOM_IPQ5210_H

#define MASTER_CNOC_PCIE0	0
#define SLAVE_CNOC_PCIE0	1
#define MASTER_CNOC_PCIE1	2
#define SLAVE_CNOC_PCIE1	3
#define MASTER_SNOC_PCIE0	4
#define SLAVE_SNOC_PCIE0	5
#define MASTER_SNOC_PCIE1	6
#define SLAVE_SNOC_PCIE1	7
#define MASTER_USB		8
#define SLAVE_USB		9

#endif /* INTERCONNECT_QCOM_IPQ5210_H */
