# SPDX-License-Identifier: (GPL-2.0-only OR MIT)

obj-$(CONFIG_COMMON_CLK_AMLOGIC) += clk-amlogic.o

clk-amlogic-y += clk.o
clk-amlogic-y += clk-basic.o
clk-amlogic-y += clk-composite.o
clk-amlogic-y += clk-noglitch.o
