/* SPDX-License-Identifier: GPL-2.0 */

/*
 * C implementation of Buchi automaton, automatically generated by
 * tools/verification/rvgen from the linear temporal logic specification.
 * For further information, see kernel documentation:
 *   Documentation/trace/rv/linear_temporal_logic.rst
 */

#include <linux/rv.h>

#define MONITOR_NAME rts

#define LTL_MONITOR_TYPE RV_MON_PER_CPU

enum ltl_atom {
	LTL_RT_TASK_ENQUEUED,
	LTL_SCHED_SWITCH,
	LTL_SCHED_SWITCH_DL,
	LTL_SCHED_SWITCH_RT,
	LTL_NUM_ATOM
};
static_assert(LTL_NUM_ATOM <= RV_MAX_LTL_ATOM);

static const char *ltl_atom_str(enum ltl_atom atom)
{
	static const char *const names[] = {
		"rt_ta_en",
		"sc_sw",
		"sc_sw_dl",
		"sc_sw_rt",
	};

	return names[atom];
}

enum ltl_buchi_state {
	S0,
	S1,
	S2,
	S3,
	S4,
	RV_NUM_BA_STATES
};
static_assert(RV_NUM_BA_STATES <= RV_MAX_BA_STATES);

static void ltl_start(unsigned int cpu, struct ltl_monitor *mon)
{
	bool sched_switch_rt = test_bit(LTL_SCHED_SWITCH_RT, mon->atoms);
	bool sched_switch_dl = test_bit(LTL_SCHED_SWITCH_DL, mon->atoms);
	bool sched_switch = test_bit(LTL_SCHED_SWITCH, mon->atoms);
	bool rt_task_enqueued = test_bit(LTL_RT_TASK_ENQUEUED, mon->atoms);
	bool val13 = !rt_task_enqueued;
	bool val8 = sched_switch_dl || val13;
	bool val9 = sched_switch_rt || val8;
	bool val6 = !sched_switch;
	bool val1 = !rt_task_enqueued;

	if (val1)
		__set_bit(S0, mon->states);
	if (val6)
		__set_bit(S1, mon->states);
	if (val9)
		__set_bit(S4, mon->states);
}

static void
ltl_possible_next_states(struct ltl_monitor *mon, unsigned int state, unsigned long *next)
{
	bool sched_switch_rt = test_bit(LTL_SCHED_SWITCH_RT, mon->atoms);
	bool sched_switch_dl = test_bit(LTL_SCHED_SWITCH_DL, mon->atoms);
	bool sched_switch = test_bit(LTL_SCHED_SWITCH, mon->atoms);
	bool rt_task_enqueued = test_bit(LTL_RT_TASK_ENQUEUED, mon->atoms);
	bool val13 = !rt_task_enqueued;
	bool val8 = sched_switch_dl || val13;
	bool val9 = sched_switch_rt || val8;
	bool val6 = !sched_switch;
	bool val1 = !rt_task_enqueued;

	switch (state) {
	case S0:
		if (val1)
			__set_bit(S0, next);
		if (val6)
			__set_bit(S1, next);
		if (val9)
			__set_bit(S4, next);
		break;
	case S1:
		if (val6)
			__set_bit(S1, next);
		if (val1 && val6)
			__set_bit(S2, next);
		if (val1 && val9)
			__set_bit(S3, next);
		if (val9)
			__set_bit(S4, next);
		break;
	case S2:
		if (val6)
			__set_bit(S1, next);
		if (val1 && val6)
			__set_bit(S2, next);
		if (val1 && val9)
			__set_bit(S3, next);
		if (val9)
			__set_bit(S4, next);
		break;
	case S3:
		if (val1)
			__set_bit(S0, next);
		if (val6)
			__set_bit(S1, next);
		if (val9)
			__set_bit(S4, next);
		break;
	case S4:
		if (val1)
			__set_bit(S0, next);
		if (val6)
			__set_bit(S1, next);
		if (val9)
			__set_bit(S4, next);
		break;
	}
}
