# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Visconti video input device driver
#

visconti-viif-objs = viif.o viif_capture.o viif_isp.o viif_csi2rx.o viif_common.o viif_params.o viif_stats.o

obj-$(CONFIG_VIDEO_VISCONTI_VIIF) += visconti-viif.o
