#!/bin/sh -e
# SPDX-License-Identifier: GPL-2.0-only
#
# ftracetest-ktap: Wrapper to integrate ftracetest with the kselftest runner
#
# Copyright (C) Arm Ltd., 2023

dir=$(cd "$(dirname "$0")" && pwd)
export PATH="$dir:$PATH"
"$dir/../ftrace/ftracetest" -K -v --rv "$dir"
