# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for linux/drivers/platform/x86/uniwill
# Uniwill X86 Platform Specific Drivers
#

obj-$(CONFIG_UNIWILL_LAPTOP)	+= uniwill-laptop.o
obj-$(CONFIG_UNIWILL_WMI)	+= uniwill-wmi.o
