[default.extend-words]
# All of these duplicated words tell typos not to touch them.
# They are case-insensitive but keep the case when fixed.
aack = "aack"
aer = "aer"
ahd = "ahd"
alo = "alo"
als = "als"
aout = "aout"
ba = "ba"
buid = "buid"
clen = "clen"
cmo = "cmo"
cpy = "cpy"
daa = "daa"
datas = "datas"
decie = "decie"
defin = "defin"
divde = "divde"
edn = "edn"
emac = "emac"
evn = "evn"
extint = "extint"
filp = "filp"
firsr = "firsr"
fram = "fram"
fre = "fre"
fpr = "fpr"
hypen = "hypen"
ihs = "ihs"
indx = "indx"
intack = "intack"
iput = "iput"
ist = "ist"
iy = "iy"
millenium = "millenium"
mmaped = "mmaped"
mminimal = "mminimal"
mport = "mport"
msis = "msis"
nam = "nam"
nax = "nax"
nd = "nd"
nin = "nin"
nto = "nto"
onl = "onl"
ot = "ot"
outout = "outout"
parm = "parm"
parms = "parms"
performa = "performa"
pevents = "pevents"
piar = "piar"
pn = "pn"
ptd = "ptd"
recal = "recal"
rela = "rela"
rto = "rto"
ser = "ser"
shw = "shw"
shs = "shs"
sie = "sie"
siz = "siz"
slq = "slq"
sxl = "sxl"
synopsys = "synopsys"
systemes = "systemes"
tbe = "tbe"
tge = "tge"
thr = "thr"
thre = "thre"
tne = "tne"
tpe = "tpe"
tpos = "tpos"
tre = "tre"
trun = "trun"
tou = "tou"
ue = "ue"
unline = "unline"
uupdate = "uupdate"
vas = "vas"
vor = "vor"
wil = "wil"

# These words are for typos which had two or more known fixes.
addresse = "address"
allowe = "allow"
arbitrer = "arbiter"
colose = "color"
concatination = "concatenation"
contants = "constants"
contigious = "contiguous"
defferent = "different"
fime = "fixme"
fo = "for"
fom = "from"
formt = "format"
matrics = "metrics"
mmaping = "mmapping"
multipler = "multiplier"
ony = "only"
partions = "partitions"
partioning = "partitioning"
pathes = "paths"
sensure = "ensure"
tranditional = "traditional"
verisions = "versions"
wether = "whether"
wll = "will"
