# SPDX-License-Identifier: GPL-2.0
#
# Makefile for industrial I/O flow sensor drivers
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_SENSIRION_SLF3S) += slf3s.o
obj-$(CONFIG_SENSIRION_SLF3S_KUNIT_TEST) += slf3s-kunit.o
