# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
%YAML 1.2
---
$id: http://devicetree.org/schemas/misc/nvidia,tegra-config-settings.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Config properties for a device

description:
  Config setting is the configuration based on chip/board/system
  characterization on interface/controller settings. This is needed for
  - making the controller internal configuration to better perform
  - making the interface to work proper by setting drive strength, slew
    rates etc
  - making the low power leakage.
  There are two types of recommended configuration settings
  - Controller register specific for internal operation of controller.
  - Pad control/Pinmux/pincontrol registers for interfacing.
  These configurations can further be categorized as static and dynamic.
  - Static config does not change until a controller is reset.
  - Dynamic config changes based on mode or condition, controller is
    operating in.

maintainers:
  - Thierry Reding <thierry.reding@gmail.com>

properties:
  $nodename:
    const: configsettings

patternProperties:
  "config-[a-z0-9_]+$":
    description:
      Config node representing properties of a device. Properties of
      each device are listed under a unique subnode and referenced from
      device node.
    type: object
    additionalProperties: false

    patternProperties:
      "^i2c-[a-z0-9_]+-cfg$":
        description: Config settings for I2C devices.
        type: object
        additionalProperties: false

        properties:
          nvidia,i2c-clk-divisor-hs-mode:
            description: I2C clock divisor for HS mode.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-clk-divisor-fs-mode:
            description: I2C clock divisor for FS mode.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-hs-sclk-high-period:
            description: I2C high speed sclk high period.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-hs-sclk-low-period:
            description: I2C high speed sclk low period.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-hs-stop-setup-time:
            description: I2C high speed stop setup time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-hs-start-hold-time:
            description: I2C high speed start hold time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-hs-start-setup-time:
            description: I2C high speed start setup time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-sclk-high-period:
            description: I2C sclk high period.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-sclk-low-period:
            description: I2C sclk low period.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-bus-free-time:
            description: I2C bus free time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-stop-setup-time:
            description: I2C stop setup time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff
          nvidia,i2c-start-hold-time:
            description: I2C start hold time.
            $ref: /schemas/types.yaml#/definitions/uint32
            minimum: 0
            maximum: 0xffff

additionalProperties: false

examples:
  - |
    configsettings {
        configi2c1: config-i2c3160000 {
            i2c-common-cfg {
                nvidia,i2c-hs-sclk-high-period = <0x03>;
                nvidia,i2c-hs-sclk-low-period = <0x08>;
            };
            i2c-fast-cfg {
                nvidia,i2c-clk-divisor-fs-mode = <0x3c>;
                nvidia,i2c-sclk-high-period = <0x02>;
            };
            i2c-fastplus-cfg {
                nvidia,i2c-clk-divisor-fs-mode = <0x4f>;
                nvidia,i2c-sclk-high-period = <0x07>;
            };
        };
    };
