# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the USB media device drivers
#

# DVB USB-only drivers. Please keep it alphabetically sorted by directory name
# keep-sorted start
obj-y += b2c2/
obj-y += dvb-usb-v2/
obj-y += dvb-usb/
obj-y += s2255/
obj-y += siano/
obj-y += ttusb-budget/
obj-y += ttusb-dec/
# keep-sorted end

# Please keep it alphabetically sorted by Kconfig name
# keep-sorted start
obj-$(CONFIG_DVB_AS102) += as102/
obj-$(CONFIG_USB_AIRSPY) += airspy/
obj-$(CONFIG_USB_GSPCA) += gspca/
obj-$(CONFIG_USB_HACKRF) += hackrf/
obj-$(CONFIG_USB_MSI2500) += msi2500/
obj-$(CONFIG_USB_PWC) += pwc/
obj-$(CONFIG_USB_VIDEO_CLASS) += uvc/
obj-$(CONFIG_VIDEO_AU0828) += au0828/
obj-$(CONFIG_VIDEO_CX231XX) += cx231xx/
obj-$(CONFIG_VIDEO_EM28XX) += em28xx/
obj-$(CONFIG_VIDEO_GO7007) += go7007/
obj-$(CONFIG_VIDEO_HDPVR) += hdpvr/
obj-$(CONFIG_VIDEO_PVRUSB2) += pvrusb2/
obj-$(CONFIG_VIDEO_STK1160) += stk1160/
obj-$(CONFIG_VIDEO_USBTV) += usbtv/
# keep-sorted end
