# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_QCOM_JENC) += qcom-jenc.o

qcom-jenc-objs += \
	qcom_jenc_dev.o \
	qcom_jenc_v4l2.o \
	qcom_jenc_ops.o \
	qcom_jenc_res.o \
	qcom_jenc_hdr.o
