/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef QCOM_JENC_V420_HW_INFO_H
#define QCOM_JENC_V420_HW_INFO_H

#include "qcom_jenc_defs.h"

#define JPEG_V420_HW_VER_STEP_POS 0
#define JPEG_V420_HW_VER_STEP_MSK \
	(0xffffu << JPEG_V420_HW_VER_STEP_POS)

#define JPEG_V420_HW_VER_MINOR_POS 16
#define JPEG_V420_HW_VER_MINOR_MSK \
	(0x0fffu << JPEG_V420_HW_VER_MINOR_POS)

#define JPEG_V420_HW_VER_MAJOR_POS 28
#define JPEG_V420_HW_VER_MAJOR_MSK \
	(0xfu << JPEG_V420_HW_VER_MAJOR_POS)

#define JPEG_V420_HW_CAP_ENCODE_MSK BIT_U32(0)
#define JPEG_V420_HW_CAP_DECODE_MSK BIT_U32(1)

#define JPEG_V420_HW_CAP_UPSCALE_POS 4
#define JPEG_V420_HW_CAP_UPSCALE_MSK \
	(0x7u << JPEG_V420_HW_CAP_UPSCALE_POS)

#define JPEG_V420_HW_CAP_DOWNSCALE_POS 8
#define JPEG_V420_HW_CAP_DOWNSCALE_MSK \
	(0x7u << JPEG_V420_HW_CAP_DOWNSCALE_POS)

#define JPEG_V420_RST_CMD_FE_RESET_MSK			BIT_U32(0)
#define JPEG_V420_RST_CMD_WE_RESET_MSK			BIT_U32(1)
#define JPEG_V420_RST_CMD_ENCODER_RESET_MSK		BIT_U32(4)
#define JPEG_V420_RST_CMD_DECODER_RESET_MSK		BIT_U32(5)
#define JPEG_V420_RST_CMD_BLOCK_FORMATTER_RST_MSK	BIT_U32(6)
#define JPEG_V420_RST_CMD_SCALE_RESET_MSK		BIT_U32(7)
#define JPEG_V420_RST_CMD_REGISTER_RESET_MSK		BIT_U32(13)
#define JPEG_V420_RST_CMD_MISR_RESET_MSK		BIT_U32(16)
#define JPEG_V420_RST_CMD_CORE_RESET_MSK		BIT_U32(17)
#define JPEG_V420_RST_CMD_JPEG_V420_DOMAIN_RESET_MSK	BIT_U32(29)
#define JPEG_V420_RST_CMD_RESET_BYPASS_MSK		BIT_U32(31)

#define JPEG_V420_CORE_CFG_FE_ENABLE_MSK	BIT_U32(0)
#define JPEG_V420_CORE_CFG_WE_ENABLE_MSK	BIT_U32(1)
#define JPEG_V420_CORE_CFG_ENC_ENABLE_MSK	BIT_U32(4)
#define JPEG_V420_CORE_CFG_SCALE_ENABLE_MSK	BIT_U32(7)
#define JPEG_V420_CORE_CFG_TESTBUS_ENABLE_MSK	BIT_U32(19)
#define JPEG_V420_CORE_CFG_MODE_MSK		BIT_U32(24)
#define JPEG_V420_CORE_CFG_CGC_DISABLE_MSK	BIT_U32(31)

#define JPEG_V420_CMD_HW_START_MSK		BIT_U32(0)
#define JPEG_V420_CMD_HW_STOP_MSK		BIT_U32(1)
#define JPEG_V420_CMD_CLR_RD_PLN0_QUEUE_MSK	BIT_U32(4)
#define JPEG_V420_CMD_CLR_RD_PLN1_QUEUE_MSK	BIT_U32(5)
#define JPEG_V420_CMD_CLR_RD_PLN2_QUEUE_MSK	BIT_U32(6)
#define JPEG_V420_CMD_CLR_WR_PLN0_QUEUE_MSK	BIT_U32(8)
#define JPEG_V420_CMD_CLR_WR_PLN1_QUEUE_MSK	BIT_U32(9)
#define JPEG_V420_CMD_CLR_WR_PLN2_QUEUE_MSK	BIT_U32(10)
#define JPEG_V420_CMD_APPLY_SWC_RD_PARAMS_MSK	BIT_U32(11)

#define JPEG_V420_CORE_STATE_STATUS_ENCODE_STATE_MSK	BIT_U32(0)
#define JPEG_V420_CORE_STATE_STATUS_SCALE_STATE_MSK	BIT_U32(2)
#define JPEG_V420_CORE_STATE_STATUS_REALTIME_STATE_MSK	BIT_U32(4)
#define JPEG_V420_CORE_STATE_STATUS_BUS_STATE_MSK	BIT_U32(8)
#define JPEG_V420_CORE_STATE_STATUS_CGC_STATE_MSK	BIT_U32(9)

#define JPEG_V420_FE_CFG_BYTE_ORDERING_POS 0
#define JPEG_V420_FE_CFG_BYTE_ORDERING_MSK \
	(0xfu << JPEG_V420_FE_CFG_BYTE_ORDERING_POS)

#define JPEG_V420_FE_CFG_BURST_LENGTH_MAX_POS 4
#define JPEG_V420_FE_CFG_BURST_LENGTH_MAX_MSK \
	(0xfu << JPEG_V420_FE_CFG_BURST_LENGTH_MAX_POS)

#define JPEG_V420_FE_CFG_MEMORY_FORMAT_POS 8
#define JPEG_V420_FE_CFG_MEMORY_FORMAT_MSK \
	(0x3u << JPEG_V420_FE_CFG_MEMORY_FORMAT_POS)

#define JPEG_V420_FE_CFG_CBCR_ORDER_MSK		BIT_U32(12)
#define JPEG_V420_FE_CFG_BOTTOM_VPAD_EN_MSK	BIT_U32(13)
#define JPEG_V420_FE_CFG_PLN0_EN_MSK		BIT_U32(16)
#define JPEG_V420_FE_CFG_PLN1_EN_MSK		BIT_U32(17)
#define JPEG_V420_FE_CFG_PLN2_EN_MSK		BIT_U32(18)
#define JPEG_V420_FE_CFG_SIXTEEN_MCU_EN_MSK	BIT_U32(21)
#define JPEG_V420_FE_CFG_MCUS_PER_BLOCK_MSK	BIT_U32(22)
#define JPEG_V420_FE_CFG_MAL_BOUNDARY_MSK	BIT_U32(24)
#define JPEG_V420_FE_CFG_MAL_EN_MSK		BIT_U32(27)

#define JPEG_V420_PLN_RD_OFFS_OFFSET_POS 0
#define JPEG_V420_PLN_RD_OFFS_OFFSET_MSK \
	(0x1fffffffu << JPEG_V420_PLN_RD_OFFS_OFFSET_POS)

#define JPEG_V420_PLN_RD_BUFF_SIZE_WIDTH_POS 0
#define JPEG_V420_PLN_RD_BUFF_SIZE_WIDTH_MSK \
	(0xffffu << JPEG_V420_PLN_RD_BUFF_SIZE_WIDTH_POS)

#define JPEG_V420_PLN_RD_BUFF_SIZE_HEIGHT_POS 16
#define JPEG_V420_PLN_RD_BUFF_SIZE_HEIGHT_MSK \
	(0xffffu << JPEG_V420_PLN_RD_BUFF_SIZE_HEIGHT_POS)

#define JPEG_V420_PLN_RD_STRIDE_STRIDE_POS 0
#define JPEG_V420_PLN_RD_STRIDE_STRIDE_MSK \
	(0xffffu << JPEG_V420_PLN_RD_STRIDE_STRIDE_POS)

#define JPEG_V420_PLN_RD_HINIT_FRACTIONAL_POS 0
#define JPEG_V420_PLN_RD_HINIT_FRACTIONAL_MSK \
	(0x1fffffu << JPEG_V420_PLN_RD_HINIT_FRACTIONAL_POS)

#define JPEG_V420_PLN_RD_VINIT_FRACTIONAL_POS 0
#define JPEG_V420_PLN_RD_VINIT_FRACTIONAL_MSK \
	(0x1fffffu << JPEG_V420_PLN_RD_VINIT_FRACTIONAL_POS)

#define JPEG_V420_WE_CFG_BYTE_ORDERING_POS 0
#define JPEG_V420_WE_CFG_BYTE_ORDERING_MSK \
	(0xfu << JPEG_V420_WE_CFG_BYTE_ORDERING_POS)

#define JPEG_V420_WE_CFG_BURST_LENGTH_MAX_POS 4
#define JPEG_V420_WE_CFG_BURST_LENGTH_MAX_MSK \
	(0xfu << JPEG_V420_WE_CFG_BURST_LENGTH_MAX_POS)

#define JPEG_V420_WE_CFG_MEMORY_FORMAT_POS 8
#define JPEG_V420_WE_CFG_MEMORY_FORMAT_MSK \
	(0x3u << JPEG_V420_WE_CFG_MEMORY_FORMAT_POS)

#define JPEG_V420_WE_CFG_CBCR_ORDER_MSK		BIT_U32(12)
#define JPEG_V420_WE_CFG_PLN0_EN_MSK		BIT_U32(16)
#define JPEG_V420_WE_CFG_PLN1_EN_MSK		BIT_U32(17)
#define JPEG_V420_WE_CFG_PLN2_EN_MSK		BIT_U32(18)
#define JPEG_V420_WE_CFG_MAL_BOUNDARY_MSK	BIT_U32(24)
#define JPEG_V420_WE_CFG_MAL_EN_MSK		BIT_U32(27)
#define JPEG_V420_WE_CFG_POP_BUFF_ON_EOS_MSK	BIT_U32(28)

#define JPEG_V420_PLN_WR_BUFF_SIZE_WIDTH_POS 0
#define JPEG_V420_PLN_WR_BUFF_SIZE_WIDTH_MSK \
	(0xffffu << JPEG_V420_PLN_WR_BUFF_SIZE_WIDTH_POS)

#define JPEG_V420_PLN_WR_BUFF_SIZE_HEIGHT_POS 16
#define JPEG_V420_PLN_WR_BUFF_SIZE_HEIGHT_MSK \
	(0xffffu << JPEG_V420_PLN_WR_BUFF_SIZE_HEIGHT_POS)

#define JPEG_V420_PLN_WR_STRIDE_STRIDE_POS 0
#define JPEG_V420_PLN_WR_STRIDE_STRIDE_MSK \
	(0xffffu << JPEG_V420_PLN_WR_STRIDE_STRIDE_POS)

#define JPEG_V420_PLN_WR_HINIT_INTEGER_POS 0
#define JPEG_V420_PLN_WR_HINIT_INTEGER_MSK \
	(0xffffu << JPEG_V420_PLN_WR_HINIT_INTEGER_POS)

#define JPEG_V420_PLN_WR_VINIT_INTEGER_POS 0
#define JPEG_V420_PLN_WR_VINIT_INTEGER_MSK \
	(0xffffu << JPEG_V420_PLN_WR_VINIT_INTEGER_POS)

#define JPEG_V420_PLN_WR_HSTEP_INTEGER_POS 0
#define JPEG_V420_PLN_WR_HSTEP_INTEGER_MSK \
	(0x1ffffu << JPEG_V420_PLN_WR_HSTEP_INTEGER_POS)

#define JPEG_V420_PLN_WR_VSTEP_INTEGER_POS 0
#define JPEG_V420_PLN_WR_VSTEP_INTEGER_MSK \
	(0x1ffffu << JPEG_V420_PLN_WR_VSTEP_INTEGER_POS)

#define JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_COL_POS 0
#define JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_COL_MSK \
	(0xffffu << JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_COL_POS)

#define JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_ROW_POS 16
#define JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_ROW_MSK \
	(0xffffu << JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_ROW_POS)

#define JPEG_V420_ENC_CFG_IMAGE_FORMAT_POS 0
#define JPEG_V420_ENC_CFG_IMAGE_FORMAT_MSK \
	(0x7u << JPEG_V420_ENC_CFG_IMAGE_FORMAT_POS)

#define JPEG_V420_ENC_CFG_APPLY_EOI_MSK		BIT_U32(7)
#define JPEG_V420_ENC_CFG_HUFFMAN_SEL_MSK	BIT_U32(8)
#define JPEG_V420_ENC_CFG_FSC_ENABLE_MSK	BIT_U32(11)
#define JPEG_V420_ENC_CFG_OUTPUT_DISABLE_MSK	BIT_U32(15)
#define JPEG_V420_ENC_CFG_RST_MARKER_PERIOD_MSK	BIT_U32(16)

#define JPEG_V420_ENC_IMG_SIZE_ENCODE_WIDTH_POS 0u
#define JPEG_V420_ENC_IMG_SIZE_ENCODE_WIDTH_MSK \
	(0x1fffu << JPEG_V420_ENC_IMG_SIZE_ENCODE_WIDTH_POS)

#define JPEG_V420_ENC_IMG_SIZE_ENCODE_HEIGHT_POS 16u
#define JPEG_V420_ENC_IMG_SIZE_ENCODE_HEIGHT_MSK \
	(0x1fffu << JPEG_V420_ENC_IMG_SIZE_ENCODE_HEIGHT_POS)

#define JPEG_V420_OUTPUT_SIZE_STATUS_OUT_SIZE_BYTES_POS 0
#define JPEG_V420_OUTPUT_SIZE_STATUS_OUT_SIZE_BYTES_MSK \
	(0x1fffffffu << JPEG_V420_OUTPUT_SIZE_STATUS_OUT_SIZE_BYTES_POS)

#define JPEG_V420_SCALE_CFG_HSCALE_ENABLE_MSK		BIT_U32(4)
#define JPEG_V420_SCALE_CFG_VSCALE_ENABLE_MSK		BIT_U32(5)
#define JPEG_V420_SCALE_CFG_UPSAMPLE_EN_MSK		BIT_U32(6)
#define JPEG_V420_SCALE_CFG_SUBSAMPLE_EN_MSK		BIT_U32(7)
#define JPEG_V420_SCALE_CFG_HSCALE_ALGO_MSK		BIT_U32(8)
#define JPEG_V420_SCALE_CFG_VSCALE_ALGO_MSK		BIT_U32(9)

#define JPEG_V420_SCALE_CFG_H_SCALE_FIR_ALGO_POS  12u
#define JPEG_V420_SCALE_CFG_H_SCALE_FIR_ALGO_MSK \
	(0x3u << JPEG_V420_SCALE_CFG_H_SCALE_FIR_ALGO_POS)

#define JPEG_V420_SCALE_CFG_V_SCALE_FIR_ALGO_POS  16u
#define JPEG_V420_SCALE_CFG_V_SCALE_FIR_ALGO_MSK \
	(0x3u << JPEG_V420_SCALE_CFG_V_SCALE_FIR_ALGO_POS)

#define JPEG_V420_SCALE_OUT_CFG_BLOCK_WIDTH_POS 0
#define JPEG_V420_SCALE_OUT_CFG_BLOCK_WIDTH_MSK \
	(0xffu << JPEG_V420_SCALE_OUT_CFG_BLOCK_WIDTH_POS)

#define JPEG_V420_SCALE_OUT_CFG_BLOCK_HEIGHT_POS 16
#define JPEG_V420_SCALE_OUT_CFG_BLOCK_HEIGHT_MSK \
	(0xfu << JPEG_V420_SCALE_OUT_CFG_BLOCK_HEIGHT_POS)

#define JPEG_V420_SCALE_PLN_HSTEP_FRACTIONAL_POS 0
#define JPEG_V420_SCALE_PLN_HSTEP_FRACTIONAL_MSK \
	(0x1fffffu << JPEG_V420_SCALE_PLN_HSTEP_FRACTIONAL_POS)

#define JPEG_V420_SCALE_PLN_HSTEP_INTEGER_POS 21
#define JPEG_V420_SCALE_PLN_HSTEP_INTEGER_MSK \
	(0x3fu << JPEG_V420_SCALE_PLN_HSTEP_INTEGER_POS)

#define JPEG_V420_SCALE_PLN_VSTEP_FRACTIONAL_POS 0
#define JPEG_V420_SCALE_PLN_VSTEP_FRACTIONAL_MSK \
	(0x1fffffu << JPEG_V420_SCALE_PLN_VSTEP_FRACTIONAL_POS)

#define JPEG_V420_SCALE_PLN_VSTEP_INTEGER_POS 21
#define JPEG_V420_SCALE_PLN_VSTEP_INTEGER_MSK \
	(0x3fu << JPEG_V420_SCALE_PLN_VSTEP_INTEGER_POS)

#define JPEG_V420_DMI_CFG_MEM_SEL_POS 0
#define JPEG_V420_DMI_CFG_MEM_SEL_MSK \
	(0x7u << JPEG_V420_DMI_CFG_MEM_SEL_POS)

#define JPEG_V420_DMI_CFG_AUTO_INC_EN_MSK	BIT_U32(4)

#define JPEG_V420_DMI_ADDR_ADDR_POS 0
#define JPEG_V420_DMI_ADDR_ADDR_MSK \
	(0x3ffu << JPEG_V420_DMI_ADDR_ADDR_POS)

#define JPEG_V420_TESTBUS_CFG_BUS_SEL_POS 0
#define JPEG_V420_TESTBUS_CFG_BUS_SEL_MSK \
	(0x3fu << JPEG_V420_TESTBUS_CFG_BUS_SEL_POS)

#define JPEG_V420_FE_VBPAD_CFG_BLOCK_ROW_POS 0
#define JPEG_V420_FE_VBPAD_CFG_BLOCK_ROW_MSK \
	(0x1fffu << JPEG_V420_FE_VBPAD_CFG_BLOCK_ROW_POS)

#define JPEG_V420_PLN_RD_HINIT_INT_INTEGER_POS 0
#define JPEG_V420_PLN_RD_HINIT_INT_INTEGER_MSK \
	(0x1ffffu << JPEG_V420_PLN_RD_HINIT_INT_INTEGER_POS)

#define JPEG_V420_PLN_RD_VINIT_INT_INTEGER_POS 0
#define JPEG_V420_PLN_RD_VINIT_INT_INTEGER_MSK \
	(0x1ffffu << JPEG_V420_PLN_RD_VINIT_INT_INTEGER_POS)

#define JPEG_V420_IRQ_STATUS_SESSION_DONE_MSK		BIT_U32(0)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN0_DONE_MSK	BIT_U32(4)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN1_DONE_MSK	BIT_U32(5)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN2_DONE_MSK	BIT_U32(6)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN0_REQ_ATTN_MSK	BIT_U32(7)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN1_REQ_ATTN_MSK	BIT_U32(8)
#define JPEG_V420_IRQ_STATUS_RD_BUF_PLN2_REQ_ATTN_MSK	BIT_U32(9)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_DONE_MSK	BIT_U32(10)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN1_DONE_MSK	BIT_U32(11)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN2_DONE_MSK	BIT_U32(12)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_REQ_ATTN_MSK	BIT_U32(13)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN1_REQ_ATTN_MSK	BIT_U32(14)
#define JPEG_V420_IRQ_STATUS_WR_BUF_PLN2_REQ_ATTN_MSK	BIT_U32(15)
#define JPEG_V420_IRQ_STATUS_DCD_UNESCAPED_FF_MSK	BIT_U32(19)
#define JPEG_V420_IRQ_STATUS_DCD_HUFFMAN_ERROR_MSK	BIT_U32(20)
#define JPEG_V420_IRQ_STATUS_DCD_COEFF_ERROR_MSK	BIT_U32(21)
#define JPEG_V420_IRQ_STATUS_DCD_MISSING_BITSTUFF_MSK	BIT_U32(22)
#define JPEG_V420_IRQ_STATUS_DCD_SCAN_UNDERFLOW_MSK	BIT_U32(23)
#define JPEG_V420_IRQ_STATUS_DCD_INVALID_RSM_MSK	BIT_U32(24)
#define JPEG_V420_IRQ_STATUS_DCD_INVALID_RSM_SEQ_MSK	BIT_U32(25)
#define JPEG_V420_IRQ_STATUS_DCD_MISSING_RSM_MSK	BIT_U32(26)
#define JPEG_V420_IRQ_STATUS_STOP_ACK_MSK		BIT_U32(27)
#define JPEG_V420_IRQ_STATUS_RESET_ACK_MSK		BIT_U32(28)

#define	JPEG_V420_IRQ_STATUS_RD_BUF_PLNS_DONE_MSK \
	(JPEG_V420_IRQ_STATUS_RD_BUF_PLN0_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLN1_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLN2_DONE_MSK)

#define	JPEG_V420_IRQ_STATUS_WR_BUF_PLNS_DONE_MSK \
	(JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLN1_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLN2_DONE_MSK)

#define	JPEG_V420_IRQ_STATUS_RD_BUF_PLNS_REQ_ATTN_MSK \
	(JPEG_V420_IRQ_STATUS_RD_BUF_PLN0_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLN1_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLN2_REQ_ATTN_MSK)

#define	JPEG_V420_IRQ_STATUS_WR_BUF_PLNS_REQ_ATTN_MSK \
	(JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLN1_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLN2_REQ_ATTN_MSK)

#define	JPEG_V420_IRQ_STATUS_SESION_ERROR_MSK \
	(JPEG_V420_IRQ_STATUS_DCD_UNESCAPED_FF_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_HUFFMAN_ERROR_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_COEFF_ERROR_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_MISSING_BITSTUFF_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_SCAN_UNDERFLOW_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_INVALID_RSM_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_INVALID_RSM_SEQ_MSK	| \
	 JPEG_V420_IRQ_STATUS_DCD_MISSING_RSM_MSK)

#define JPEG_V420_IRQ_STATUS_ALL_BITS \
	(JPEG_V420_IRQ_STATUS_SESSION_DONE_MSK		| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLNS_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_DONE_MSK	| \
	 JPEG_V420_IRQ_STATUS_RD_BUF_PLNS_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_WR_BUF_PLNS_REQ_ATTN_MSK	| \
	 JPEG_V420_IRQ_STATUS_SESION_ERROR_MSK		| \
	 JPEG_V420_IRQ_STATUS_STOP_ACK_MSK		| \
	 JPEG_V420_IRQ_STATUS_RESET_ACK_MSK)

static const u32 qcom_jpeg_v420_hw_reg_mask[] = {
	[JMSK_HW_VER_STEP]	= JPEG_V420_HW_VER_STEP_MSK,
	[JMSK_HW_VER_MINOR]	= JPEG_V420_HW_VER_MINOR_MSK,
	[JMSK_HW_VER_MAJOR]	= JPEG_V420_HW_VER_MAJOR_MSK,

	[JMSK_HW_CAP_ENCODE]	= JPEG_V420_HW_CAP_ENCODE_MSK,
	[JMSK_HW_CAP_DECODE]	= JPEG_V420_HW_CAP_DECODE_MSK,
	[JMSK_HW_CAP_UPSCALE]	= JPEG_V420_HW_CAP_UPSCALE_MSK,
	[JMSK_HW_CAP_DOWNSCALE]	= JPEG_V420_HW_CAP_DOWNSCALE_MSK,

	[JMSK_RST_CMD_COMMON]	=
		(JPEG_V420_RST_CMD_FE_RESET_MSK			|
		 JPEG_V420_RST_CMD_WE_RESET_MSK			|
		 JPEG_V420_RST_CMD_ENCODER_RESET_MSK		|
		 JPEG_V420_RST_CMD_BLOCK_FORMATTER_RST_MSK	|
		 JPEG_V420_RST_CMD_SCALE_RESET_MSK		|
		 JPEG_V420_RST_CMD_REGISTER_RESET_MSK		|
		 JPEG_V420_RST_CMD_MISR_RESET_MSK		|
		 JPEG_V420_RST_CMD_CORE_RESET_MSK		|
		 JPEG_V420_RST_CMD_JPEG_V420_DOMAIN_RESET_MSK),

	[JMSK_RST_CMD_FE_RESET]			= JPEG_V420_RST_CMD_FE_RESET_MSK,
	[JMSK_RST_CMD_WE_RESET]			= JPEG_V420_RST_CMD_WE_RESET_MSK,
	[JMSK_RST_CMD_ENCODER_RESET]		= JPEG_V420_RST_CMD_ENCODER_RESET_MSK,
	[JMSK_RST_CMD_DECODER_RESET]		= JPEG_V420_RST_CMD_DECODER_RESET_MSK,
	[JMSK_RST_CMD_BLOCK_FORMATTER_RST]	= JPEG_V420_RST_CMD_BLOCK_FORMATTER_RST_MSK,
	[JMSK_RST_CMD_SCALE_RESET]		= JPEG_V420_RST_CMD_SCALE_RESET_MSK,
	[JMSK_RST_CMD_REGISTER_RESET]		= JPEG_V420_RST_CMD_REGISTER_RESET_MSK,
	[JMSK_RST_CMD_MISR_RESET]		= JPEG_V420_RST_CMD_MISR_RESET_MSK,
	[JMSK_RST_CMD_CORE_RESET]		= JPEG_V420_RST_CMD_CORE_RESET_MSK,
	[JMSK_RST_CMD_JMSK_DOMAIN_RESET]	= JPEG_V420_RST_CMD_JPEG_V420_DOMAIN_RESET_MSK,
	[JMSK_RST_CMD_RESET_BYPASS]		= JPEG_V420_RST_CMD_RESET_BYPASS_MSK,

	[JMSK_CORE_CFG_FE_ENABLE]		= JPEG_V420_CORE_CFG_FE_ENABLE_MSK,
	[JMSK_CORE_CFG_WE_ENABLE]		= JPEG_V420_CORE_CFG_WE_ENABLE_MSK,
	[JMSK_CORE_CFG_ENC_ENABLE]		= JPEG_V420_CORE_CFG_ENC_ENABLE_MSK,
	[JMSK_CORE_CFG_SCALE_ENABLE]		= JPEG_V420_CORE_CFG_SCALE_ENABLE_MSK,
	[JMSK_CORE_CFG_TESTBUS_ENABLE]		= JPEG_V420_CORE_CFG_TESTBUS_ENABLE_MSK,
	[JMSK_CORE_CFG_MODE]			= JPEG_V420_CORE_CFG_MODE_MSK,
	[JMSK_CORE_CFG_CGC_DISABLE]		= JPEG_V420_CORE_CFG_CGC_DISABLE_MSK,

	[JMSK_CMD_HW_START]			= JPEG_V420_CMD_HW_START_MSK,
	[JMSK_CMD_HW_STOP]			= JPEG_V420_CMD_HW_STOP_MSK,

	[JMSK_CMD_CLR_RD_PLNS_QUEUE]		=
		(JPEG_V420_CMD_CLR_RD_PLN0_QUEUE_MSK |
		 JPEG_V420_CMD_CLR_RD_PLN1_QUEUE_MSK |
		 JPEG_V420_CMD_CLR_RD_PLN2_QUEUE_MSK),
	[JMSK_CMD_CLR_WR_PLNS_QUEUE]		=
		(JPEG_V420_CMD_CLR_WR_PLN0_QUEUE_MSK |
		 JPEG_V420_CMD_CLR_WR_PLN1_QUEUE_MSK |
		 JPEG_V420_CMD_CLR_WR_PLN2_QUEUE_MSK),

	[JMSK_CMD_APPLY_SWC_RD_PARAMS]	= JPEG_V420_CMD_APPLY_SWC_RD_PARAMS_MSK,

	[JMSK_CORE_STATUS_ENCODE_STATE]	= JPEG_V420_CORE_STATE_STATUS_ENCODE_STATE_MSK,
	[JMSK_CORE_STATUS_SCALE_STATE]	= JPEG_V420_CORE_STATE_STATUS_SCALE_STATE_MSK,
	[JMSK_CORE_STATUS_RT_STATE]	= JPEG_V420_CORE_STATE_STATUS_REALTIME_STATE_MSK,
	[JMSK_CORE_STATUS_BUS_STATE]	= JPEG_V420_CORE_STATE_STATUS_BUS_STATE_MSK,
	[JMSK_CORE_STATUS_CGC_STATE]	= JPEG_V420_CORE_STATE_STATUS_CGC_STATE_MSK,

	[JMSK_IRQ_STATUS_SESSION_DONE]	= JPEG_V420_IRQ_STATUS_SESSION_DONE_MSK,

	[JMSK_IRQ_STATUS_RD_BUF_PLN0_DONE]	= JPEG_V420_IRQ_STATUS_RD_BUF_PLN0_DONE_MSK,
	[JMSK_IRQ_STATUS_RD_BUF_PLN1_DONE]	= JPEG_V420_IRQ_STATUS_RD_BUF_PLN1_DONE_MSK,
	[JMSK_IRQ_STATUS_RD_BUF_PLN2_DONE]	= JPEG_V420_IRQ_STATUS_RD_BUF_PLN2_DONE_MSK,
	[JMSK_IRQ_STATUS_RD_BUF_PLNS_ATTN]	= JPEG_V420_IRQ_STATUS_RD_BUF_PLNS_REQ_ATTN_MSK,

	[JMSK_IRQ_STATUS_WR_BUF_PLN0_DONE]	= JPEG_V420_IRQ_STATUS_WR_BUF_PLN0_DONE_MSK,
	[JMSK_IRQ_STATUS_WR_BUF_PLN1_DONE]	= JPEG_V420_IRQ_STATUS_WR_BUF_PLN1_DONE_MSK,
	[JMSK_IRQ_STATUS_WR_BUF_PLN2_DONE]	= JPEG_V420_IRQ_STATUS_WR_BUF_PLN2_DONE_MSK,
	[JMSK_IRQ_STATUS_WR_BUF_PLNS_ATTN]	= JPEG_V420_IRQ_STATUS_WR_BUF_PLNS_REQ_ATTN_MSK,

	[JMSK_IRQ_STATUS_SESSION_ERROR]	= JPEG_V420_IRQ_STATUS_SESION_ERROR_MSK,

	[JMSK_IRQ_STATUS_STOP_ACK]	= JPEG_V420_IRQ_STATUS_STOP_ACK_MSK,
	[JMSK_IRQ_STATUS_RESET_ACK]	= JPEG_V420_IRQ_STATUS_RESET_ACK_MSK,

	[JMSK_IRQ_STATUS_ALL_BITS]	= JPEG_V420_IRQ_STATUS_ALL_BITS,

	[JMSK_FE_CFG_BYTE_ORDERING]	= JPEG_V420_FE_CFG_BYTE_ORDERING_MSK,
	[JMSK_FE_CFG_BURST_LENGTH_MAX]	= JPEG_V420_FE_CFG_BURST_LENGTH_MAX_MSK,
	[JMSK_FE_CFG_MEMORY_FORMAT]	= JPEG_V420_FE_CFG_MEMORY_FORMAT_MSK,
	[JMSK_FE_CFG_CBCR_ORDER]	= JPEG_V420_FE_CFG_CBCR_ORDER_MSK,
	[JMSK_FE_CFG_BOTTOM_VPAD_EN]	= JPEG_V420_FE_CFG_BOTTOM_VPAD_EN_MSK,
	[JMSK_FE_CFG_PLN0_EN]		= JPEG_V420_FE_CFG_PLN0_EN_MSK,
	[JMSK_FE_CFG_PLN1_EN]		= JPEG_V420_FE_CFG_PLN1_EN_MSK,
	[JMSK_FE_CFG_PLN2_EN]		= JPEG_V420_FE_CFG_PLN2_EN_MSK,
	[JMSK_FE_CFG_SIXTEEN_MCU_EN]	= JPEG_V420_FE_CFG_SIXTEEN_MCU_EN_MSK,
	[JMSK_FE_CFG_MCUS_PER_BLOCK]	= JPEG_V420_FE_CFG_MCUS_PER_BLOCK_MSK,
	[JMSK_FE_CFG_MAL_BOUNDARY]	= JPEG_V420_FE_CFG_MAL_BOUNDARY_MSK,
	[JMSK_FE_CFG_MAL_EN]		= JPEG_V420_FE_CFG_MAL_EN_MSK,

	[JMSK_FE_VBPAD_CFG_BLOCK_ROW]	= JPEG_V420_FE_VBPAD_CFG_BLOCK_ROW_MSK,

	[JMSK_PLNS_RD_OFFSET]		= JPEG_V420_PLN_RD_OFFS_OFFSET_MSK,
	[JMSK_PLNS_RD_BUF_SIZE_WIDTH]	= JPEG_V420_PLN_RD_BUFF_SIZE_WIDTH_MSK,
	[JMSK_PLNS_RD_BUF_SIZE_HEIGHT]	= JPEG_V420_PLN_RD_BUFF_SIZE_HEIGHT_MSK,
	[JMSK_PLNS_RD_STRIDE]		= JPEG_V420_PLN_RD_STRIDE_STRIDE_MSK,
	[JMSK_PLNS_RD_HINIT]		= JPEG_V420_PLN_RD_HINIT_FRACTIONAL_MSK,
	[JMSK_PLNS_RD_VINIT]		= JPEG_V420_PLN_RD_VINIT_FRACTIONAL_MSK,

	[JMSK_WE_CFG_BYTE_ORDERING]	= JPEG_V420_WE_CFG_BYTE_ORDERING_MSK,
	[JMSK_WE_CFG_BURST_LENGTH_MAX]	= JPEG_V420_WE_CFG_BURST_LENGTH_MAX_MSK,
	[JMSK_WE_CFG_MEMORY_FORMAT]	= JPEG_V420_WE_CFG_MEMORY_FORMAT_MSK,
	[JMSK_WE_CFG_CBCR_ORDER]	= JPEG_V420_WE_CFG_CBCR_ORDER_MSK,
	[JMSK_WE_CFG_PLN0_EN]		= JPEG_V420_WE_CFG_PLN0_EN_MSK,
	[JMSK_WE_CFG_PLN1_EN]		= JPEG_V420_WE_CFG_PLN1_EN_MSK,
	[JMSK_WE_CFG_PLN2_EN]		= JPEG_V420_WE_CFG_PLN2_EN_MSK,
	[JMSK_WE_CFG_MAL_BOUNDARY]	= JPEG_V420_WE_CFG_MAL_BOUNDARY_MSK,
	[JMSK_WE_CFG_MAL_EN]		= JPEG_V420_WE_CFG_MAL_EN_MSK,
	[JMSK_WE_CFG_POP_BUFF_ON_EOS]	= JPEG_V420_WE_CFG_POP_BUFF_ON_EOS_MSK,

	[JMSK_PLNS_WR_BUF_SIZE_WIDTH]	= JPEG_V420_PLN_WR_BUFF_SIZE_WIDTH_MSK,
	[JMSK_PLNS_WR_BUF_SIZE_HEIGHT]	= JPEG_V420_PLN_WR_BUFF_SIZE_HEIGHT_MSK,

	[JMSK_PLNS_WR_STRIDE]	= JPEG_V420_PLN_WR_STRIDE_STRIDE_MSK,
	[JMSK_PLNS_WR_HINIT]	= JPEG_V420_PLN_WR_HINIT_INTEGER_MSK,
	[JMSK_PLNS_WR_VINIT]	= JPEG_V420_PLN_WR_VINIT_INTEGER_MSK,
	[JMSK_PLNS_WR_HSTEP]	= JPEG_V420_PLN_WR_HSTEP_INTEGER_MSK,
	[JMSK_PLNS_WR_VSTEP]	= JPEG_V420_PLN_WR_VSTEP_INTEGER_MSK,

	[JMSK_PLNS_WR_BLOCK_CFG_PER_COL]	= JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_COL_MSK,
	[JMSK_PLNS_WR_BLOCK_CFG_PER_RAW]	= JPEG_V420_PLN_WR_BLK_CFG_BLOCKS_PER_ROW_MSK,

	[JMSK_SCALE_CFG_HSCALE_ENABLE]		= JPEG_V420_SCALE_CFG_HSCALE_ENABLE_MSK,
	[JMSK_SCALE_CFG_VSCALE_ENABLE]		= JPEG_V420_SCALE_CFG_VSCALE_ENABLE_MSK,
	[JMSK_SCALE_CFG_UPSAMPLE_EN]		= JPEG_V420_SCALE_CFG_UPSAMPLE_EN_MSK,
	[JMSK_SCALE_CFG_SUBSAMPLE_EN]		= JPEG_V420_SCALE_CFG_SUBSAMPLE_EN_MSK,
	[JMSK_SCALE_CFG_HSCALE_ALGO]		= JPEG_V420_SCALE_CFG_HSCALE_ALGO_MSK,
	[JMSK_SCALE_CFG_VSCALE_ALGO]		= JPEG_V420_SCALE_CFG_VSCALE_ALGO_MSK,
	[JMSK_SCALE_CFG_H_SCALE_FIR_ALGO]	= JPEG_V420_SCALE_CFG_H_SCALE_FIR_ALGO_MSK,
	[JMSK_SCALE_CFG_V_SCALE_FIR_ALGO]	= JPEG_V420_SCALE_CFG_V_SCALE_FIR_ALGO_MSK,

	[JMSK_SCALE_PLNS_OUT_CFG_BLK_WIDTH]	= JPEG_V420_SCALE_OUT_CFG_BLOCK_WIDTH_MSK,
	[JMSK_SCALE_PLNS_OUT_CFG_BLK_HEIGHT]	= JPEG_V420_SCALE_OUT_CFG_BLOCK_HEIGHT_MSK,

	[JMSK_SCALE_PLNS_HSTEP_FRACTIONAL]	= JPEG_V420_SCALE_PLN_HSTEP_FRACTIONAL_MSK,
	[JMSK_SCALE_PLNS_HSTEP_INTEGER]		= JPEG_V420_SCALE_PLN_HSTEP_INTEGER_MSK,
	[JMSK_SCALE_PLNS_VSTEP_FRACTIONAL]	= JPEG_V420_SCALE_PLN_VSTEP_FRACTIONAL_MSK,
	[JMSK_SCALE_PLNS_VSTEP_INTEGER]		= JPEG_V420_SCALE_PLN_VSTEP_INTEGER_MSK,

	[JMSK_ENC_CFG_IMAGE_FORMAT]		= JPEG_V420_ENC_CFG_IMAGE_FORMAT_MSK,
	[JMSK_ENC_CFG_APPLY_EOI]		= JPEG_V420_ENC_CFG_APPLY_EOI_MSK,
	[JMSK_ENC_CFG_HUFFMAN_SEL]		= JPEG_V420_ENC_CFG_HUFFMAN_SEL_MSK,
	[JMSK_ENC_CFG_FSC_ENABLE]		= JPEG_V420_ENC_CFG_FSC_ENABLE_MSK,
	[JMSK_ENC_CFG_OUTPUT_DISABLE]		= JPEG_V420_ENC_CFG_OUTPUT_DISABLE_MSK,
	[JMSK_ENC_CFG_RST_MARKER_PERIOD]	= JPEG_V420_ENC_CFG_RST_MARKER_PERIOD_MSK,
	[JMSK_ENC_IMAGE_SIZE_WIDTH]		= JPEG_V420_ENC_IMG_SIZE_ENCODE_WIDTH_MSK,
	[JMSK_ENC_IMAGE_SIZE_HEIGHT]		= JPEG_V420_ENC_IMG_SIZE_ENCODE_HEIGHT_MSK,
};

static const struct qcom_jpeg_reg_offs qcom_jpeg_v420_hw_reg_offs = {
	.hw_version	= 0x000,
	.hw_capability	= 0x004,
	.reset_cmd	= 0x008,
	.core_cfg	= 0x00c,
	.hw_cmd		= 0x010,
	.int_mask	= 0x018,
	.int_clr	= 0x01c,
	.int_status	= 0x020,
	.enc_core_state = 0x014,

	.fe = {
		.pntr	= { 0x038, 0x044, 0x050 },
		.offs	= { 0x03c, 0x048, 0x054 },
		.bsize	= { 0x060, 0x068, 0x070 },
		.stride	= { 0x064, 0x06c, 0x08c },
		.hinit	= { 0x074, 0x078, 0x07c },
		.vinit	= { 0x080, 0x084, 0x088 },
		.pntr_cnt	= 0x05c,
		.vbpad_cfg	= 0x2e8
	},
	.fe_cfg	= 0x024,

	.we = {
		.pntr	= { 0x0cc, 0x0d0, 0x0d4 },
		.bsize	= { 0x0e8, 0x0ec, 0x0f0 },
		.stride	= { 0x0f4, 0x0f8, 0x0fc },
		.hinit	= { 0x100, 0x104, 0x108 },
		.hstep	= { 0x118, 0x11c, 0x120 },
		.vinit	= { 0x10c, 0x110, 0x114 },
		.vstep	= { 0x124, 0x128, 0x12c },
		.blocks	= { 0x130, 0x134, 0x138 },
		.pntr_cnt = 0x0e4
	},
	.we_cfg	= 0x0c0,

	.scale = {
		.hstep	= { 0x27c, 0x280, 0x284 },
		.vstep	= { 0x28c, 0x290, 0x294 },
	},
	.scale_cfg	= 0x26c,
	.scale_out_cfg	= { 0x270, 0x274, 0x278 },

	.enc_cfg	= 0x13c,
	.enc_img_size	= 0x140,
	.enc_out_size	= 0x180,

	.dmi_cfg	= 0x298,
	.dmi_data	= 0x2a0,
	.dmi_addr	= 0x29c,
};

#endif /* QCOM_JENC_V420_HW_INFO_H */
