/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef QCOM_JENC_DEFS_H_
#define QCOM_JENC_DEFS_H_

#include <linux/bitfield.h>
#include <linux/io.h>
#include <linux/types.h>
#include <linux/videodev2.h>
#include <media/videobuf2-core.h>

/* Offline JPEG encoder constraints */
#define QCOM_JPEG_HW_MAX_WIDTH	8192
#define QCOM_JPEG_HW_MAX_HEIGHT	8192
#define QCOM_JPEG_HW_MIN_WIDTH	128
#define QCOM_JPEG_HW_MIN_HEIGHT	96

#define QCOM_JPEG_HW_DEF_HSTEP	16
#define QCOM_JPEG_HW_DEF_VSTEP	16

#define QCOM_JPEG_HW_DEF_WIDTH	1920
#define QCOM_JPEG_HW_DEF_HEIGHT	1088

#define QCOM_JPEG_MAX_PLANES	3

#define QCOM_JPEG_QUALITY_MIN	1
#define QCOM_JPEG_QUALITY_DEF	95
#define QCOM_JPEG_QUALITY_MAX	100
#define QCOM_JPEG_QUALITY_MID	(QCOM_JPEG_QUALITY_MAX / 2)
#define QCOM_JPEG_QUALITY_UNT	1

enum qcom_soc_perf_level {
	/* Idle/suspend state, not for active encode performance selection. */
	QCOM_SOC_PERF_SUSPEND = 0,
	QCOM_SOC_PERF_LOWSVS,
	QCOM_SOC_PERF_SVS,
	QCOM_SOC_PERF_SVS_L1,
	QCOM_SOC_PERF_NOMINAL,
	QCOM_SOC_PERF_TURBO,
	QCOM_SOC_PERF_LEVEL_MAX,
};

enum qcom_jpeg_mask_id {
	JMSK_HW_VER_STEP,
	JMSK_HW_VER_MINOR,
	JMSK_HW_VER_MAJOR,

	JMSK_HW_CAP_ENCODE,
	JMSK_HW_CAP_DECODE,
	JMSK_HW_CAP_UPSCALE,
	JMSK_HW_CAP_DOWNSCALE,

	JMSK_RST_CMD_COMMON,
	JMSK_RST_CMD_FE_RESET,
	JMSK_RST_CMD_WE_RESET,
	JMSK_RST_CMD_ENCODER_RESET,
	JMSK_RST_CMD_DECODER_RESET,
	JMSK_RST_CMD_BLOCK_FORMATTER_RST,
	JMSK_RST_CMD_SCALE_RESET,
	JMSK_RST_CMD_REGISTER_RESET,
	JMSK_RST_CMD_MISR_RESET,
	JMSK_RST_CMD_CORE_RESET,
	JMSK_RST_CMD_JMSK_DOMAIN_RESET,
	JMSK_RST_CMD_RESET_BYPASS,

	JMSK_CMD_HW_START,
	JMSK_CMD_HW_STOP,
	JMSK_CMD_CLR_RD_PLNS_QUEUE,
	JMSK_CMD_CLR_WR_PLNS_QUEUE,
	JMSK_CMD_APPLY_SWC_RD_PARAMS,

	JMSK_CORE_CFG_FE_ENABLE,
	JMSK_CORE_CFG_WE_ENABLE,
	JMSK_CORE_CFG_ENC_ENABLE,
	JMSK_CORE_CFG_SCALE_ENABLE,
	JMSK_CORE_CFG_TESTBUS_ENABLE,
	JMSK_CORE_CFG_MODE,
	JMSK_CORE_CFG_CGC_DISABLE,

	JMSK_CORE_STATUS_ENCODE_STATE,
	JMSK_CORE_STATUS_SCALE_STATE,
	JMSK_CORE_STATUS_RT_STATE,
	JMSK_CORE_STATUS_BUS_STATE,
	JMSK_CORE_STATUS_CGC_STATE,

	JMSK_IRQ_STATUS_SESSION_DONE,
	JMSK_IRQ_STATUS_RD_BUF_PLN0_DONE,
	JMSK_IRQ_STATUS_RD_BUF_PLN1_DONE,
	JMSK_IRQ_STATUS_RD_BUF_PLN2_DONE,
	JMSK_IRQ_STATUS_RD_BUF_PLNS_ATTN,
	JMSK_IRQ_STATUS_WR_BUF_PLN0_DONE,
	JMSK_IRQ_STATUS_WR_BUF_PLN1_DONE,
	JMSK_IRQ_STATUS_WR_BUF_PLN2_DONE,
	JMSK_IRQ_STATUS_WR_BUF_PLNS_ATTN,
	JMSK_IRQ_STATUS_SESSION_ERROR,
	JMSK_IRQ_STATUS_STOP_ACK,
	JMSK_IRQ_STATUS_RESET_ACK,

	JMSK_IRQ_STATUS_ALL_BITS,

	JMSK_FE_CFG_BYTE_ORDERING,
	JMSK_FE_CFG_BURST_LENGTH_MAX,
	JMSK_FE_CFG_MEMORY_FORMAT,
	JMSK_FE_CFG_CBCR_ORDER,
	JMSK_FE_CFG_BOTTOM_VPAD_EN,
	JMSK_FE_CFG_PLN0_EN,
	JMSK_FE_CFG_PLN1_EN,
	JMSK_FE_CFG_PLN2_EN,
	JMSK_FE_CFG_SIXTEEN_MCU_EN,
	JMSK_FE_CFG_MCUS_PER_BLOCK,
	JMSK_FE_CFG_MAL_BOUNDARY,
	JMSK_FE_CFG_MAL_EN,

	JMSK_FE_VBPAD_CFG_BLOCK_ROW,

	JMSK_PLNS_RD_OFFSET,
	JMSK_PLNS_RD_BUF_SIZE_WIDTH,
	JMSK_PLNS_RD_BUF_SIZE_HEIGHT,
	JMSK_PLNS_RD_STRIDE,
	JMSK_PLNS_RD_HINIT,
	JMSK_PLNS_RD_VINIT,

	JMSK_WE_CFG_BYTE_ORDERING,
	JMSK_WE_CFG_BURST_LENGTH_MAX,
	JMSK_WE_CFG_MEMORY_FORMAT,
	JMSK_WE_CFG_CBCR_ORDER,
	JMSK_WE_CFG_PLN0_EN,
	JMSK_WE_CFG_PLN1_EN,
	JMSK_WE_CFG_PLN2_EN,
	JMSK_WE_CFG_MAL_BOUNDARY,
	JMSK_WE_CFG_MAL_EN,
	JMSK_WE_CFG_POP_BUFF_ON_EOS,

	JMSK_PLNS_WR_BUF_SIZE_WIDTH,
	JMSK_PLNS_WR_BUF_SIZE_HEIGHT,

	JMSK_PLNS_WR_STRIDE,
	JMSK_PLNS_WR_HINIT,
	JMSK_PLNS_WR_VINIT,
	JMSK_PLNS_WR_HSTEP,
	JMSK_PLNS_WR_VSTEP,
	JMSK_PLNS_WR_BLOCK_CFG_PER_COL,
	JMSK_PLNS_WR_BLOCK_CFG_PER_RAW,

	JMSK_ENC_CFG_IMAGE_FORMAT,
	JMSK_ENC_CFG_APPLY_EOI,
	JMSK_ENC_CFG_HUFFMAN_SEL,
	JMSK_ENC_CFG_FSC_ENABLE,
	JMSK_ENC_CFG_OUTPUT_DISABLE,
	JMSK_ENC_CFG_RST_MARKER_PERIOD,
	JMSK_ENC_IMAGE_SIZE_WIDTH,
	JMSK_ENC_IMAGE_SIZE_HEIGHT,

	JMSK_SCALE_CFG_HSCALE_ENABLE,
	JMSK_SCALE_CFG_VSCALE_ENABLE,
	JMSK_SCALE_CFG_UPSAMPLE_EN,
	JMSK_SCALE_CFG_SUBSAMPLE_EN,
	JMSK_SCALE_CFG_HSCALE_ALGO,
	JMSK_SCALE_CFG_VSCALE_ALGO,
	JMSK_SCALE_CFG_H_SCALE_FIR_ALGO,
	JMSK_SCALE_CFG_V_SCALE_FIR_ALGO,

	JMSK_SCALE_PLNS_OUT_CFG_BLK_WIDTH,
	JMSK_SCALE_PLNS_OUT_CFG_BLK_HEIGHT,

	JMSK_SCALE_PLNS_HSTEP_FRACTIONAL,
	JMSK_SCALE_PLNS_HSTEP_INTEGER,
	JMSK_SCALE_PLNS_VSTEP_FRACTIONAL,
	JMSK_SCALE_PLNS_VSTEP_INTEGER,

	JMSK_DMI_CFG,
	JMSK_DMI_ADDR,
	JMSK_DMI_DATA,

	JMSK_TESTBUS_CFG,
	JMSK_FE_VBPAD_CFG,

	JMSK_PLN0_RD_HINIT_INT,
	JMSK_PLN1_RD_HINIT_INT,
	JMSK_PLN2_RD_HINIT_INT,
	JMSK_PLN0_RD_VINIT_INT,
	JMSK_PLN1_RD_VINIT_INT,
	JMSK_PLN2_RD_VINIT_INT,
	JMSK_ID_MAX
};

struct qcom_jpeg_reg_offs {
	u32 hw_version;
	u32 hw_capability;
	u32 reset_cmd;
	u32 core_cfg;
	u32 int_mask;
	u32 int_clr;
	u32 int_status;
	u32 hw_cmd;
	u32 enc_core_state;

	struct {
		u32 pntr[QCOM_JPEG_MAX_PLANES];
		u32 offs[QCOM_JPEG_MAX_PLANES];
		u32 cnsmd[QCOM_JPEG_MAX_PLANES];
		u32 bsize[QCOM_JPEG_MAX_PLANES];
		u32 stride[QCOM_JPEG_MAX_PLANES];
		u32 hinit[QCOM_JPEG_MAX_PLANES];
		u32 vinit[QCOM_JPEG_MAX_PLANES];
		u32 pntr_cnt;
		u32 vbpad_cfg;
	} fe;
	u32 fe_cfg;

	struct {
		u32 pntr[QCOM_JPEG_MAX_PLANES];
		u32 cnsmd[QCOM_JPEG_MAX_PLANES];
		u32 bsize[QCOM_JPEG_MAX_PLANES];
		u32 stride[QCOM_JPEG_MAX_PLANES];
		u32 hinit[QCOM_JPEG_MAX_PLANES];
		u32 hstep[QCOM_JPEG_MAX_PLANES];
		u32 vinit[QCOM_JPEG_MAX_PLANES];
		u32 vstep[QCOM_JPEG_MAX_PLANES];
		u32 blocks[QCOM_JPEG_MAX_PLANES];
		u32 pntr_cnt;
	} we;
	u32 we_cfg;

	struct {
		u32 hstep[QCOM_JPEG_MAX_PLANES];
		u32 vstep[QCOM_JPEG_MAX_PLANES];
	} scale;
	u32 scale_cfg;
	u32 scale_out_cfg[QCOM_JPEG_MAX_PLANES];

	u32 enc_cfg;
	u32 enc_img_size;
	u32 enc_out_size;

	u32 dmi_cfg;
	u32 dmi_data;
	u32 dmi_addr;
};

#endif /* QCOM_JENC_DEFS_H_ */
