/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright (c) 2026 Roman Vivchar.
 */

#ifndef _DT_BINDINGS_GCE_MT6572_H
#define _DT_BINDINGS_GCE_MT6572_H

/* GCE HW thread priority */
#define CMDQ_THR_PRIO_NORMAL		0
#define CMDQ_THR_PRIO_HIGHEST		1

/* GCE SUBSYS */
#define SUBSYS_14XXXXXX			0
#define SUBSYS_15XXXXXX			1

/* GCE HW EVENT */
#define CMDQ_EVENT_MUTEX0		0
#define CMDQ_EVENT_MUTEX1		1
#define CMDQ_EVENT_MUTEX2		2
#define CMDQ_EVENT_MUTEX3		3
#define CMDQ_EVENT_MUTEX4		4
#define CMDQ_EVENT_MUTEX5		5
#define CMDQ_EVENT_MUTEX6		6
#define CMDQ_EVENT_MUTEX7		7

#define CMDQ_EVENT_DISP_WDMA_EOF	12
#define CMDQ_EVENT_DISP_RDMA_EOF	13
#define CMDQ_EVENT_DISP_BLS_EOF		14
#define CMDQ_EVENT_DISP_COLOR_EOF	15
#define CMDQ_EVENT_DISP_OVL_EOF		16
#define CMDQ_EVENT_MDP_TDSHP_EOF	17
#define CMDQ_EVENT_MDP_RSZ1_EOF		18
#define CMDQ_EVENT_MDP_RSZ0_EOF		19
#define CMDQ_EVENT_MDP_RDMA_EOF		20
#define CMDQ_EVENT_MDP_WDMA_EOF		21
#define CMDQ_EVENT_MDP_WROT_EOF		22

#define CMDQ_EVENT_MDP_WROT_SOF		24
#define CMDQ_EVENT_MDP_RSZ0_SOF		25
#define CMDQ_EVENT_MDP_RSZ1_SOF		26
#define CMDQ_EVENT_DISP_OVL_SOF		27
#define CMDQ_EVENT_MDP_WDMA_SOF		28
#define CMDQ_EVENT_MDP_RDMA_SOF		29
#define CMDQ_EVENT_DISP_WDMA_SOF	30
#define CMDQ_EVENT_DISP_COLOR_SOF	31
#define CMDQ_EVENT_MDP_TDSHP_SOF	32
#define CMDQ_EVENT_DISP_BLS_SOF		33
#define CMDQ_EVENT_DISP_RDMA_SOF	34
#define CMDQ_EVENT_CAM_MDP		35

#endif
